// Code generated by protoc-gen-go. DO NOT EDIT.
// source: buff.proto

/*
Package scene is a generated protocol buffer package.

It is generated from these files:
	buff.proto
	common.proto
	item.proto
	message_type.proto
	monster.proto
	player.proto
	scene.proto

It has these top-level messages:
	ObjectBuffData
	Position
	SceneItemData
	SceneMonsterData
	ScenePlayerData
	ScenePlayerShowData
	CSPing
	SCPing
	CSEnterScene
	SCEnterScene
	SCObjectEnterScope
	ExitObject
	SCObjectExitScope
	ObjectMoveData
	CSObjectMove
	SCObjectMove
	ObjectAttackData
	CSObjectAttack
	SCObjectAttack
	ObjectDamage
	SCObjectDamage
	SCObjectBuff
	SCObjectBuffRemove
	SCObjectBattle
	SCPlayerDataChanged
	CSPlayerRelive
	ObjectReliveData
	SCPlayerRelive
	CSItemGet
	SCItemGet
	SCExitScene
	SCObjectFixPosition
	SCMonsterCampChanged
	SCItemOwnerChanged
	CSWorldEnterScene
	CSEnterPortal
	SCEnterPortal
	CSReenterScene
	CSSceneHeartBeat
	SCSceneHeartBeat
	CSPetAttack
	SCPetAttack
*/
package scene

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ObjectBuffData struct {
	Uid              *int64   `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	ObjecType        *int32   `protobuf:"varint,2,req,name=objecType" json:"objecType,omitempty"`
	BuffId           *int32   `protobuf:"varint,3,req,name=buffId" json:"buffId,omitempty"`
	BuffTime         *float32 `protobuf:"fixed32,4,req,name=buffTime" json:"buffTime,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ObjectBuffData) Reset()                    { *m = ObjectBuffData{} }
func (m *ObjectBuffData) String() string            { return proto.CompactTextString(m) }
func (*ObjectBuffData) ProtoMessage()               {}
func (*ObjectBuffData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ObjectBuffData) GetUid() int64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *ObjectBuffData) GetObjecType() int32 {
	if m != nil && m.ObjecType != nil {
		return *m.ObjecType
	}
	return 0
}

func (m *ObjectBuffData) GetBuffId() int32 {
	if m != nil && m.BuffId != nil {
		return *m.BuffId
	}
	return 0
}

func (m *ObjectBuffData) GetBuffTime() float32 {
	if m != nil && m.BuffTime != nil {
		return *m.BuffTime
	}
	return 0
}

func init() {
	proto.RegisterType((*ObjectBuffData)(nil), "scene.ObjectBuffData")
}

func init() { proto.RegisterFile("buff.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 118 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2a, 0x4d, 0x4b,
	0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2d, 0x4e, 0x4e, 0xcd, 0x4b, 0x55, 0x0a, 0xe2,
	0xe2, 0xf3, 0x4f, 0xca, 0x4a, 0x4d, 0x2e, 0x71, 0x2a, 0x4d, 0x4b, 0x73, 0x49, 0x2c, 0x49, 0x14,
	0xe2, 0xe6, 0x62, 0x2e, 0xcd, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd2, 0x60, 0x16, 0x12, 0xe4, 0xe2,
	0xcc, 0x07, 0x49, 0x87, 0x54, 0x16, 0xa4, 0x4a, 0x30, 0x29, 0x30, 0x69, 0xb0, 0x0a, 0xf1, 0x71,
	0xb1, 0x81, 0x8c, 0xf1, 0x4c, 0x91, 0x60, 0x06, 0xf3, 0x05, 0xb8, 0x38, 0x40, 0xfc, 0x90, 0xcc,
	0xdc, 0x54, 0x09, 0x16, 0x05, 0x26, 0x0d, 0x26, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa0, 0x83,
	0x74, 0x31, 0x67, 0x00, 0x00, 0x00,
}
