package team

import (
	"fgame/fgame/common/lang"
	gamecommon "fgame/fgame/game/common/common"
)

var (
	ErrorTeamPlayerInTeam                = gamecommon.CodeError(lang.TeamPlayerInTeam)
	ErrorTeamCreateHouseInOther          = gamecommon.CodeError(lang.TeamCreateHouseInOther)
	ErrorTeamCreateHouseNoCaptain        = gamecommon.CodeError(lang.TeamCreateHouseNoCaptain)
	ErrorTeamPlayerOff                   = gamecommon.CodeError(lang.TeamPlayerOff)
	ErrorTeamPlayerFull                  = gamecommon.CodeError(lang.TeamPlayerFull)
	ErrorTeamDissolve                    = gamecommon.CodeError(lang.TeamDissolve)
	ErrorTeamCaptainIsOther              = gamecommon.CodeError(lang.TeamCaptainIsOther)
	ErrorTeamPlayerNoMember              = gamecommon.CodeError(lang.TeamPlayerNoMember)
	ErrorTeamApplyNoExist                = gamecommon.CodeError(lang.TeamApplyNoExist)
	ErrorTeamPlayerNotInTeam             = gamecommon.CodeError(lang.TeamPlayerNotInTeam)
	ErrorTeamInInit                      = gamecommon.CodeError(lang.TeamInInit)
	ErrorTeamInMatch                     = gamecommon.CodeError(lang.TeamInMatch)
	ErrorTeamNotInMatch                  = gamecommon.CodeError(lang.TeamNotInMatch)
	ErrorTeamNoExist                     = gamecommon.CodeError(lang.TeamNoExist)
	ErrorTeamInMatchLevelLow             = gamecommon.CodeError(lang.TeamInMatchLevelLow)
	ErrorTeamInMatchInviteJion           = gamecommon.CodeError(lang.TeamInMatchInviteJion)
	ErrorTeamInMatchInCross              = gamecommon.CodeError(lang.TeamInMatchInCross)
	ErrorTeamInMatchInFuBen              = gamecommon.CodeError(lang.TeamInMatchInFuBen)
	ErrorTeamInMatchInPvp                = gamecommon.CodeError(lang.TeamInMatchInPvp)
	ErrorTeamInMatchNoActivityTime       = gamecommon.CodeError(lang.TeamInMatchNoActivityTime)
	ErrorTeamInMatchJionFail             = gamecommon.CodeError(lang.TeamInMatchJionFail)
	ErrorTeamInMatchDealAgreeFail        = gamecommon.CodeError(lang.TeamInMatchDealAgreeFail)
	ErrorTeamInMatchInLianYuLineUp       = gamecommon.CodeError(lang.TeamInMatchInLianYuLineUp)
	ErrorTeamInMatchInGodSiegeLineUp     = gamecommon.CodeError(lang.TeamInMatchInGodSiegeLineUp)
	ErrorTeamInTeamCopyBattle            = gamecommon.CodeError(lang.TeamInTeamCopyBattle)
	ErrorTeamInTeamCopyJionFail          = gamecommon.CodeError(lang.TeamInTeamCopyJionFail)
	ErrorTeamMemberPlayerOffline         = gamecommon.CodeError(lang.TeamMemberPlayerOffline)
	ErrorTeamNotInTeamCopyBattle         = gamecommon.CodeError(lang.TeamNotInTeamCopyBattle)
	ErrorTeamBattlePuroseIsNormal        = gamecommon.CodeError(lang.TeamBattlePuroseIsNormal)
	ErrorTeamCreateHouseLevelLow         = gamecommon.CodeError(lang.TeamCreateHouseLevelLow)
	ErrorTeamCreateHouseSelfLevelLow     = gamecommon.CodeError(lang.TeamCreateHouseSelfLevelLow)
	ErrorTeamApplyJoinFuncNoOpen         = gamecommon.CodeError(lang.TeamApplyJoinFuncNoOpen)
	ErrorTeamHouseIsBatting              = gamecommon.CodeError(lang.TeamHouseIsBatting)
	ErrorTeamInMatchSelfInCross          = gamecommon.CodeError(lang.TeamInMatchSelfInCross)
	ErrorTeamInMatchSelfInLianYuLineUp   = gamecommon.CodeError(lang.TeamInMatchSelfInLianYuLineUp)
	ErrorTeamInMatchInSelfGodSiegeLineUp = gamecommon.CodeError(lang.TeamInMatchInSelfGodSiegeLineUp)
	ErrorTeamInMatchSelfInFuBen          = gamecommon.CodeError(lang.TeamInMatchSelfInFuBen)
	ErrorTeamInMatchSelfInPvp            = gamecommon.CodeError(lang.TeamInMatchSelfInPvp)
	ErrorTeamRushMatchIsExist            = gamecommon.CodeError(lang.TeamRushMatchIsExist)
	ErrorTeamRushMatchCaptainOffline     = gamecommon.CodeError(lang.TeamRushMatchCaptainOffline)
	ErrorTeamInMatchInSelfShenMoLineUp   = gamecommon.CodeError(lang.TeamInMatchInSelfShenMoLineUp)
	ErrorTeamJionByLeavedInCd            = gamecommon.CodeError(lang.TeamJionByLeavedInCd)
)
