package handler

import (
	"fgame/fgame/common/codec"
	uipb "fgame/fgame/common/codec/pb/ui"
	gamecodec "fgame/fgame/game/codec"
)

func init() {
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_FIRST_CHARGE_TYPE), (*uipb.CSOpenActivityFirstCharge)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_FIRST_CHARGE_TYPE), (*uipb.SCOpenActivityFirstCharge)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_FIRST_CHARGE_NOTICE_TYPE), (*uipb.SCOpenActivityFirstChargeNotice)(nil))

	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_WELFARE_LOGIN_RECEIVE_REW_TYPE), (*uipb.CSOpenActivityWelfareLoginReceiveRew)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_WELFARE_LOGIN_RECEIVE_REW_TYPE), (*uipb.SCOpenActivityWelfareLoginReceiveRew)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_WELFARE_UPLEVEL_RECEIVE_REW_TYPE), (*uipb.CSOpenActivityWelfareUplevelReceiveRew)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_WELFARE_UPLEVEL_RECEIVE_REW_TYPE), (*uipb.SCOpenActivityWelfareUplevelReceiveRew)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_WELFARE_ONLINE_RECEIVE_REW_TYPE), (*uipb.CSOpenActivityWelfareOnlineReceiveRew)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_WELFARE_ONLINE_RECEIVE_REW_TYPE), (*uipb.SCOpenActivityWelfareOnlineReceiveRew)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_WELFARE_ONLINE_DREW_TYPE), (*uipb.CSOpenActivityWelfareOnlineDrew)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_WELFARE_ONLINE_DREW_TYPE), (*uipb.SCOpenActivityWelfareOnlineDrew)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_WELFARE_ONLINE_DATE_NOTICE_TYPE), (*uipb.SCOpenActivityWelfareOnlineDataNotice)(nil))

	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_REALM_INFO_TYPE), (*uipb.CSOpenActivityRealmInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_REALM_INFO_TYPE), (*uipb.SCOpenActivityRealmInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_REALM_REWARDS_TYPE), (*uipb.CSOpenActivityRealmRewards)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_REALM_REWARDS_TYPE), (*uipb.SCOpenActivityRealmRewards)(nil))

	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_LOGIN_INFO_TYPE), (*uipb.CSOpenActivityLoginInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_LOGIN_INFO_TYPE), (*uipb.SCOpenActivityLoginInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_UPLEVEL_INFO_TYPE), (*uipb.CSOpenActivityUplevelInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_UPLEVEL_INFO_TYPE), (*uipb.SCOpenActivityUplevelInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_ONLINE_INFO_TYPE), (*uipb.CSOpenActivityOnlineInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_ONLINE_INFO_TYPE), (*uipb.SCOpenActivityOnlineInfo)(nil))

	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_INVEST_LEVEL_BUY_TYPE), (*uipb.CSOpenActivityInvestLevelBuy)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_INVEST_LEVEL_BUY_TYPE), (*uipb.SCOpenActivityInvestLevelBuy)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_INVEST_DAY_BUY_TYPE), (*uipb.CSOpenActivityInvestDayBuy)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_INVEST_DAY_BUY_TYPE), (*uipb.SCOpenActivityInvestDayBuy)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_INVEST_LEVEL_RECEIVE_REW_TYPE), (*uipb.CSOpenActivityInvestLevelReceiveRew)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_INVEST_LEVEL_RECEIVE_REW_TYPE), (*uipb.SCOpenActivityInvestLevelReceiveRew)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_INVEST_DAY_RECEIVE_REW_TYPE), (*uipb.CSOpenActivityInvestDayReceiveRew)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_INVEST_DAY_RECEIVE_REW_TYPE), (*uipb.SCOpenActivityInvestDayReceiveRew)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_INVEST_LEVEL_INFO_TYPE), (*uipb.CSOpenActivityInvestLevelInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_INVEST_LEVEL_INFO_TYPE), (*uipb.SCOpenActivityInvestLevelInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_INVEST_DAY_INFO_TYPE), (*uipb.CSOpenActivityInvestDayInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_INVEST_DAY_INFO_TYPE), (*uipb.SCOpenActivityInvestDayInfo)(nil))

	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_FEEDBACK_CHARGE_RECEIVE_REW_TYPE), (*uipb.CSOpenActivityFeedbackChargeReceiveRew)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_FEEDBACK_CHARGE_RECEIVE_REW_TYPE), (*uipb.SCOpenActivityFeedbackChargeReceiveRew)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_FEEDBACK_COST_RECEIVE_REW_TYPE), (*uipb.CSOpenActivityFeedbackCostReceiveRew)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_FEEDBACK_COST_RECEIVE_REW_TYPE), (*uipb.SCOpenActivityFeedbackCostReceiveRew)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_FEEDBACK_COST_NOTICE_TYPE), (*uipb.SCOpenActivityFeedbackCostNotice)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_FEEDBACK_CHARGE_NOTICE_TYPE), (*uipb.SCOpenActivityFeedbackChargeNotice)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_FEEDBACK_CHARGE_INFO_TYPE), (*uipb.CSOpenActivityFeedbackChargeInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_FEEDBACK_CHARGE_INFO_TYPE), (*uipb.SCOpenActivityFeedbackChargeInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_FEEDBACK_COST_INFO_TYPE), (*uipb.CSOpenActivityFeedbackCostInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_FEEDBACK_COST_INFO_TYPE), (*uipb.SCOpenActivityFeedbackCostInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_FEEDBACK_CYCLE_CHARGE_NOTICE_TYPE), (*uipb.SCOpenActivityFeedbackCycleChargeNotice)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_FEEDBACK_CYCLE_CHARGE_INFO_TYPE), (*uipb.CSOpenActivityFeedbackCycleChargeInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_FEEDBACK_CYCLE_CHARGE_INFO_TYPE), (*uipb.SCOpenActivityFeedbackCycleChargeInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_FEEDBACK_CYCLE_CHARGE_REWARDS_TYPE), (*uipb.CSOpenActivityFeedbackCycleChargeRewards)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_FEEDBACK_CYCLE_CHARGE_REWARDS_TYPE), (*uipb.SCOpenActivityFeedbackCycleChargeRewards)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_FEEDBACK_GOLD_LABA_ATTEND_TYPE), (*uipb.CSOpenActivityFeedbackGoldLaBaAttend)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_FEEDBACK_GOLD_LABA_ATTEND_TYPE), (*uipb.SCOpenActivityFeedbackGoldLaBaAttend)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_FEEDBACK_GOLD_LABA_INFO_TYPE), (*uipb.CSOpenActivityFeedbackGoldLaBaInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_FEEDBACK_GOLD_LABA_INFO_TYPE), (*uipb.SCOpenActivityFeedbackGoldLaBaInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_FEEDBACK_GOLD_PIG_INFO_TYPE), (*uipb.CSOpenActivityFeedbackGoldPigInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_FEEDBACK_GOLD_PIG_INFO_TYPE), (*uipb.SCOpenActivityFeedbackGoldPigInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_FEEDBACK_DEVELOP_INFO_TYPE), (*uipb.CSOpenActivityFeedbackDevelopInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_FEEDBACK_DEVELOP_INFO_TYPE), (*uipb.SCOpenActivityFeedbackDevelopInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_FEEDBACK_DEVELOP_REVIVE_TYPE), (*uipb.CSOpenActivityFeedbackDevelopRevive)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_FEEDBACK_DEVELOP_REVIVE_TYPE), (*uipb.SCOpenActivityFeedbackDevelopRevive)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_FEEDBACK_DEVELOP_RECEIVE_TYPE), (*uipb.CSOpenActivityFeedbackDevelopReceive)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_FEEDBACK_DEVELOP_RECEIVE_TYPE), (*uipb.SCOpenActivityFeedbackDevelopReceive)(nil))

	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_RANK_MOUNT_TYPE), (*uipb.CSOpenActivityRankMountList)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_RANK_MOUNT_TYPE), (*uipb.SCOpenActivityRankMountList)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_RANK_WING_TYPE), (*uipb.CSOpenActivityRankWingList)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_RANK_WING_TYPE), (*uipb.SCOpenActivityRankWingList)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_RANK_BODYSHIELD_TYPE), (*uipb.CSOpenActivityRankBodyShieldList)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_RANK_BODYSHIELD_TYPE), (*uipb.SCOpenActivityRankBodyShieldList)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_RANK_CHARGE_TYPE), (*uipb.CSOpenActivityRankChargeList)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_RANK_CHARGE_TYPE), (*uipb.SCOpenActivityRankChargeList)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_RANK_COST_TYPE), (*uipb.CSOpenActivityRankCostList)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_RANK_COST_TYPE), (*uipb.SCOpenActivityRankCostList)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_RANK_SHENFA_TYPE), (*uipb.CSOpenActivityRankShenFaList)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_RANK_SHENFA_TYPE), (*uipb.SCOpenActivityRankShenFaList)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_RANK_LINGYU_TYPE), (*uipb.CSOpenActivityRankLingYuList)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_RANK_LINGYU_TYPE), (*uipb.SCOpenActivityRankLingYuList)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_RANK_FEATHER_TYPE), (*uipb.CSOpenActivityRankFeatherList)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_RANK_FEATHER_TYPE), (*uipb.SCOpenActivityRankFeatherList)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_RANK_SHIELD_TYPE), (*uipb.CSOpenActivityRankShieldList)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_RANK_SHIELD_TYPE), (*uipb.SCOpenActivityRankShieldList)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_RANK_MY_GET_TYPE), (*uipb.CSOpenActivityRankMyGet)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_RANK_MY_GET_TYPE), (*uipb.SCOpenActivityRankMyGet)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_RANK_CHARM_TYPE), (*uipb.CSOpenActivityRankCharmList)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_RANK_CHARM_TYPE), (*uipb.SCOpenActivityRankCharmList)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_RANK_ANQI_TYPE), (*uipb.CSOpenActivityRankAnqiList)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_RANK_ANQI_TYPE), (*uipb.SCOpenActivityRankAnqiList)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_RANK_FABAO_TYPE), (*uipb.CSOpenActivityRankFaBaoList)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_RANK_FABAO_TYPE), (*uipb.SCOpenActivityRankFaBaoList)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_RANK_ADVANCED_TYPE), (*uipb.CSOpenActivityRankAdvancedList)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_RANK_ADVANCED_TYPE), (*uipb.SCOpenActivityRankAdvancedList)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_RANK_COUNT_TYPE), (*uipb.CSOpenActivityRankCountList)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_RANK_COUNT_TYPE), (*uipb.SCOpenActivityRankCountList)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_RANK_PROPERTY_TYPE), (*uipb.CSOpenActivityRankPropertyList)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_RANK_PROPERTY_TYPE), (*uipb.SCOpenActivityRankPropertyList)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_RANK_CHARGE_NOTICE_TYPE), (*uipb.SCOpenActivityRankChargeNotice)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_RANK_COST_NOTICE_TYPE), (*uipb.SCOpenActivityRankCostNotice)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_RANK_END_BROADCAST_TYPE), (*uipb.SCOpenActivityEndBroadcast)(nil))

	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_GIFT_CODE_TYPE), (*uipb.CSOpenActivityGiftCode)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_GIFT_CODE_TYPE), (*uipb.SCOpenActivityGiftCode)(nil))

	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_CYCLE_CHARGE_NOTICE_TYPE), (*uipb.SCOpenActivityCycleChargeNotice)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_CYCLE_CHARGE_INFO_TYPE), (*uipb.CSOpenActivityCycleChargeInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_CYCLE_CHARGE_INFO_TYPE), (*uipb.SCOpenActivityCycleChargeInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_CYCLE_CHARGE_REWARDS_TYPE), (*uipb.CSOpenActivityCycleChargeRewards)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_CYCLE_CHARGE_REWARDS_TYPE), (*uipb.SCOpenActivityCycleChargeRewards)(nil))

	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_MERGE_ACTIVITY_SINGLE_CHARGE_INFO_TYPE), (*uipb.CSMergeActivitySingleChargeInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_MERGE_ACTIVITY_SINGLE_CHARGE_INFO_TYPE), (*uipb.SCMergeActivitySingleChargeInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_MERGE_ACTIVITY_SINGLE_CHARGE_REWARDS_TYPE), (*uipb.CSMergeActivitySingleChargeRewards)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_MERGE_ACTIVITY_SINGLE_CHARGE_REWARDS_TYPE), (*uipb.SCMergeActivitySingleChargeRewards)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_MERGE_ACTIVITY_SINGLE_CHARGE_NOTICE_TYPE), (*uipb.SCMergeActivitySingleChargeNotice)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_CYCLE_SINGLE_CHARGE_INFO_TYPE), (*uipb.CSOpenActivityCycleSingleChargeInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_CYCLE_SINGLE_CHARGE_INFO_TYPE), (*uipb.SCOpenActivityCycleSingleChargeInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_CYCLE_SINGLE_CHARGE_REWARDS_TYPE), (*uipb.CSOpenActivityCycleSingleChargeRewards)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_CYCLE_SINGLE_CHARGE_REWARDS_TYPE), (*uipb.SCOpenActivityCycleSingleChargeRewards)(nil))

	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_MERGE_ACTIVITY_GOLD_BOWL_INFO_TYPE), (*uipb.CSMergeActivityGoldBowlInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_MERGE_ACTIVITY_GOLD_BOWL_INFO_TYPE), (*uipb.SCMergeActivityGoldBowlInfo)(nil))

	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_MERGE_ACTIVITY_LUCKY_DREW_ATTEND_TYPE), (*uipb.CSMergeActivityLuckDrewAttend)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_MERGE_ACTIVITY_LUCKY_DREW_ATTEND_TYPE), (*uipb.SCMergeActivityLuckDrewAttend)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_MERGE_ACTIVITY_BOMB_ORE_ATTEND_TYPE), (*uipb.CSMergeActivityLuckBombOreAttend)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_MERGE_ACTIVITY_BOMB_ORE_ATTEND_TYPE), (*uipb.SCMergeActivityLuckBombOreAttend)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_CHARGE_DREW_TIMES_NOTICE_TYPE), (*uipb.SCOpenActivityChargeDrewTimesNotice)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_CHARGE_DREW_INFO_TYPE), (*uipb.CSOpenActivityChargeDrewInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_CHARGE_DREW_INFO_TYPE), (*uipb.SCOpenActivityChargeDrewInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_CHARGE_DREW_ATTEND_TYPE), (*uipb.CSOpenActivityChargeDrewAttend)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_CHARGE_DREW_ATTEND_TYPE), (*uipb.SCOpenActivityChargeDrewAttend)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_DREW_LOG_INCR_TYPE), (*uipb.CSOpenActivityDrewLogIncr)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_DREW_LOG_INCR_TYPE), (*uipb.SCOpenActivityDrewLogIncr)(nil))

	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_MERGE_ACTIVITY_ADVANCED_INFO_TYPE), (*uipb.CSMergeActivityAdvancedInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_MERGE_ACTIVITY_ADVANCED_INFO_TYPE), (*uipb.SCMergeActivityAdvancedInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_MERGE_ACTIVITY_ADVANCED_REWARDS_TYPE), (*uipb.CSMergeActivityAdvancedRewards)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_MERGE_ACTIVITY_ADVANCED_REWARDS_TYPE), (*uipb.SCMergeActivityAdvancedRewards)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_MERGE_ACTIVITY_ADVANCED_BLESS_INFO_TYPE), (*uipb.CSMergeActivityAdvancedBlessInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_MERGE_ACTIVITY_ADVANCED_BLESS_INFO_TYPE), (*uipb.SCMergeActivityAdvancedBlessInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_MERGE_ACTIVITY_ADVANCED_BLESS_REWARDS_TYPE), (*uipb.CSMergeActivityAdvancedBlessRewards)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_MERGE_ACTIVITY_ADVANCED_BLESS_REWARDS_TYPE), (*uipb.SCMergeActivityAdvancedBlessRewards)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_ADVANCED_REW_INFO_TYPE), (*uipb.CSOpenActivityAdvancedRewInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_ADVANCED_REW_INFO_TYPE), (*uipb.SCOpenActivityAdvancedRewInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_ADVANCED_RECEIVE_REW_TYPE), (*uipb.CSOpenActivityAdvancedReceiveRew)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_ADVANCED_RECEIVE_REW_TYPE), (*uipb.SCOpenActivityAdvancedReceiveRew)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_ADVANCED_POWER_REW_INFO_TYPE), (*uipb.CSOpenActivityAdvancedPowerRewInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_ADVANCED_POWER_REW_INFO_TYPE), (*uipb.SCOpenActivityAdvancedPowerRewInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_ADVANCED_POWER_RECEIVE_REW_TYPE), (*uipb.CSOpenActivityAdvancedPowerReceiveRew)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_ADVANCED_POWER_RECEIVE_REW_TYPE), (*uipb.SCOpenActivityAdvancedPowerReceiveRew)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_ADVANCED_REW_EXTENDED_INFO_TYPE), (*uipb.CSOpenActivityAdvancedRewExtendedInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_ADVANCED_REW_EXTENDED_INFO_TYPE), (*uipb.SCOpenActivityAdvancedRewExtendedInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_ADVANCED_REW_EXTENDED_RECEIVE_TYPE), (*uipb.CSOpenActivityAdvancedRewExtendedReceive)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_ADVANCED_REW_EXTENDED_RECEIVE_TYPE), (*uipb.SCOpenActivityAdvancedRewExtendedReceive)(nil))

	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_MERGE_ACTIVITY_DISCOUNT_INFO_TYPE), (*uipb.CSMergeActivityDiscountInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_MERGE_ACTIVITY_DISCOUNT_INFO_TYPE), (*uipb.SCMergeActivityDiscountInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_MERGE_ACTIVITY_DISCOUNT_BUY_TYPE), (*uipb.CSMergeActivityDiscountBuy)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_MERGE_ACTIVITY_DISCOUNT_BUY_TYPE), (*uipb.SCMergeActivityDiscountBuy)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_DISCOUNT_ZHUANSHENG_INFO_TYPE), (*uipb.CSOpenActivityDiscountZhuanShengInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_DISCOUNT_ZHUANSHENG_INFO_TYPE), (*uipb.SCOpenActivityDiscountZhuanShengInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_DISCOUNT_ZHUANSHENG_BUY_TYPE), (*uipb.CSOpenActivityDiscountZhuanShengBuy)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_DISCOUNT_ZHUANSHENG_BUY_TYPE), (*uipb.SCOpenActivityDiscountZhuanShengBuy)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_DISCOUNT_ZHUANSHENG_BUY_ALL_TYPE), (*uipb.CSOpenActivityDiscountZhuanShengBuyAll)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_DISCOUNT_ZHUANSHENG_BUY_ALL_TYPE), (*uipb.SCOpenActivityDiscountZhuanShengBuyAll)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_DISCOUNT_ZHUANSHENG_RECEIVE_GIFT_TYPE), (*uipb.CSOpenActivityDiscountZhuanShengReceiveGift)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_DISCOUNT_ZHUANSHENG_RECEIVE_GIFT_TYPE), (*uipb.SCOpenActivityDiscountZhuanShengReceiveGift)(nil))

	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_KANJIA_INFO_TYPE), (*uipb.CSOpenActivityKanJiaInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_KANJIA_INFO_TYPE), (*uipb.SCOpenActivityKanJiaInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_KANJIA_TYPE), (*uipb.CSOpenActivityKanJia)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_KANJIA_TYPE), (*uipb.SCOpenActivityKanJia)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_KANJIA_BUY_TYPE), (*uipb.CSOpenActivityKanJiaBuy)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_KANJIA_BUY_TYPE), (*uipb.SCOpenActivityKanJiaBuy)(nil))

	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_COST_REWARDS_COST_INFO_TYPE), (*uipb.CSOpenActivityCostRewardsCostInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_COST_REWARDS_COST_INFO_TYPE), (*uipb.SCOpenActivityCostRewardsCostInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_CHARGE_REWARDS_LIMIT_INFO_TYPE), (*uipb.CSOpenActivityChargeRewardsLimitInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_CHARGE_REWARDS_LIMIT_INFO_TYPE), (*uipb.SCOpenActivityChargeRewardsLimitInfo)(nil))

	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_LABA_LOG_INCR_TYPE), (*uipb.CSOpenActivityLaBaLogIncr)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_LABA_LOG_INCR_TYPE), (*uipb.SCOpenActivityLaBaLogIncr)(nil))

	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_TIMES_REW_INFO_TYPE), (*uipb.CSOpenActivityTimesRewInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_TIMES_REW_INFO_TYPE), (*uipb.SCOpenActivityTimesRewInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_TIMES_REW_RECEIVE_TYPE), (*uipb.CSOpenActivityTimesRewReceive)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_TIMES_REW_RECEIVE_TYPE), (*uipb.SCOpenActivityTimesRewReceive)(nil))

	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_MADE_RES_INFO_TYPE), (*uipb.CSOpenActivityMadeResInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_MADE_RES_INFO_TYPE), (*uipb.SCOpenActivityMadeResInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_MADE_RES_TYPE), (*uipb.CSOpenActivityMadeRes)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_MADE_RES_TYPE), (*uipb.SCOpenActivityMadeRes)(nil))

	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_TAOCAN_INFO_TYPE), (*uipb.SCOpenActivityTaoCanInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_TAOCAN_BUY_TYPE), (*uipb.CSOpenActivityTaoCanBuy)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_TAOCAN_BUY_TYPE), (*uipb.SCOpenActivityTaoCanBuy)(nil))

	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_CRAZY_BOX_TIMES_NOTICE_TYPE), (*uipb.SCOpenActivityCrazyBoxTimesNotice)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_CRAZY_BOX_INFO_TYPE), (*uipb.CSOpenActivityCrazyBoxInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_CRAZY_BOX_INFO_TYPE), (*uipb.SCOpenActivityCrazyBoxInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_CRAZY_BOX_ATTEND_TYPE), (*uipb.CSOpenActivityCrazyBoxAttend)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_CRAZY_BOX_ATTEND_TYPE), (*uipb.SCOpenActivityCrazyBoxAttend)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_CRAZY_BOX_LOG_INCR_TYPE), (*uipb.CSOpenActivityCrazyBoxLogIncr)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_CRAZY_BOX_LOG_INCR_TYPE), (*uipb.SCOpenActivityCrazyBoxLogIncr)(nil))

	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_COMMON_INFO_TYPE), (*uipb.CSOpenActivityGetInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_COMMON_INFO_TYPE), (*uipb.SCOpenActivityGetInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_COMMON_RECEIVE_REW_TYPE), (*uipb.CSOpenActivityReceiveRew)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_COMMON_RECEIVE_REW_TYPE), (*uipb.SCOpenActivityReceiveRew)(nil))

	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_DEVELOP_FEED_TYPE), (*uipb.CSOpenActivityDevelopFeed)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_DEVELOP_FEED_TYPE), (*uipb.SCOpenActivityDevelopFeed)(nil))

	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_FEEDBACK_HOUSE_INVEST_NOTICE_TYPE), (*uipb.SCOpenActivityFeedbackHouseInvestNotice)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_FEEDBACK_HOUSE_INVEST_INFO_TYPE), (*uipb.CSOpenActivityFeedbackHouseInvestInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_FEEDBACK_HOUSE_INVEST_INFO_TYPE), (*uipb.SCOpenActivityFeedbackHouseInvestInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_FEEDBACK_HOUSE_INVEST_ADVENCED_TYPE), (*uipb.CSOpenActivityFeedbackHouseInvestAdvenced)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_FEEDBACK_HOUSE_INVEST_ADVENCED_TYPE), (*uipb.SCOpenActivityFeedbackHouseInvestAdvenced)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_FEEDBACK_HOUSE_INVEST_DECOR_TYPE), (*uipb.CSOpenActivityFeedbackHouseInvestDecor)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_FEEDBACK_HOUSE_INVEST_DECOR_TYPE), (*uipb.SCOpenActivityFeedbackHouseInvestDecor)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_FEEDBACK_HOUSE_INVEST_SELL_TYPE), (*uipb.CSOpenActivityFeedbackHouseInvestSell)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_FEEDBACK_HOUSE_INVEST_SELL_TYPE), (*uipb.SCOpenActivityFeedbackHouseInvestSell)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_SMASH_EGG_INFO_TYPE), (*uipb.CSOpenActivitySmashEggInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_SMASH_EGG_INFO_TYPE), (*uipb.SCOpenActivitySmashEggInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_SMASH_EGG_ATTEND_TYPE), (*uipb.CSOpenActivitySmashEggAttend)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_SMASH_EGG_ATTEND_TYPE), (*uipb.SCOpenActivitySmashEggAttend)(nil))

	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_SYSTEM_ACTIVATE_TYPE), (*uipb.CSOpenActivitySystemActivate)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_SYSTEM_ACTIVATE_TYPE), (*uipb.SCOpenActivitySystemActivate)(nil))

	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_ALLIANCE_CHEER_POOL_CHANGED_TYPE), (*uipb.SCOpenActivityAllianceCheerPoolChanged)(nil))

	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_OPEN_SERVER_TIME_CHANGED_TYPE), (*uipb.SCOpenActivityOpenServerTimeChanged)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_XUN_HUAN_INFO_TYPE), (*uipb.SCOpenActivityXunHuanInfo)(nil))

	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_COST_DREW_ATTEND_TYPE), (*uipb.CSOpenActivityCostDrewAttend)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_COST_DREW_ATTEND_TYPE), (*uipb.SCOpenActivityCostDrewAttend)(nil))

	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_CYCLE_SINGLE_CHARGE_MAX_REW_INFO_NOTICE_TYPE), (*uipb.SCOpenActivityCycleSingleChargeMaxRewInfoNotice)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_FEEDBACK_CHARGE_RETURN_MULTIPLE_NOTICE_TYPE), (*uipb.SCOpenActivityFeedbackChargeReturnMultipleNotice)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_PERIOD_CHARGE_NOTICE_TYPE), (*uipb.SCOpenActivityPeriodChargeNotice)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_RANK_MARRY_DEVELOP_TYPE), (*uipb.CSOpenActivityRankMarryDevelopList)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_RANK_MARRY_DEVELOP_TYPE), (*uipb.SCOpenActivityRankMarryDevelopList)(nil))

	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_INVEST_NEW_LEVEL_INFO_TYPE), (*uipb.CSOpenActivityInvestNewLevelInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_INVEST_NEW_LEVEL_INFO_TYPE), (*uipb.SCOpenActivityInvestNewLevelInfo)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_INVEST_NEW_LEVEL_BUY_TYPE), (*uipb.CSOpenActivityInvestNewLevelBuy)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_INVEST_NEW_LEVEL_BUY_TYPE), (*uipb.SCOpenActivityInvestNewLevelBuy)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_INVEST_NEW_LEVEL_RECEIVE_REW_TYPE), (*uipb.CSOpenActivityInvestNewLevelReceiveRew)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_INVEST_NEW_LEVEL_RECEIVE_REW_TYPE), (*uipb.SCOpenActivityInvestNewLevelReceiveRew)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_INVEST_UP_LEVEL_TYPE), (*uipb.CSOpenActivityInvestUpLevel)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_INVEST_UP_LEVEL_TYPE), (*uipb.SCOpenActivityInvestUpLevel)(nil))

	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_RANKING_DROP_DOWN_NOTICE_TYPE), (*uipb.SCOpenActivityRankingDropDownNotice)(nil))

	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_BEACH_SHOP_ACTIVITE_TYPE), (*uipb.CSOpenActivityBeachShopActivate)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_BEACH_SHOP_ACTIVITE_TYPE), (*uipb.SCOpenActivityBeachShopActivate)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_BEACH_SHOP_BUY_TYPE), (*uipb.CSOpenActivityBeachBuy)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_BEACH_SHOP_BUY_TYPE), (*uipb.SCOpenActivityBeachBuy)(nil))

	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_SINGLE_CHARGE_ALL_MULTIPLE_NOTICE), (*uipb.SCOpenActivityCycleSingleChargeAllRewInfoNotice)(nil))

	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_YUN_YIN_BUY_TYPE), (*uipb.CSOpenActivityYunYinBuy)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_YUN_YIN_BUY_TYPE), (*uipb.SCOpenActivityYunYinBuy)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_REW_POOLS_DREW_TYPE), (*uipb.CSOpenActivityRewPoolsDrew)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_REW_POOLS_DREW_TYPE), (*uipb.SCOpenActivityRewPoolsDrew)(nil))

	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_RECEIVE_REW_MULTIPLE_TYPE), (*uipb.CSOpenActivityReceiveRewMultiple)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_RECEIVE_REW_MULTIPLE_TYPE), (*uipb.SCOpenActivityReceiveRewMultiple)(nil))

	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_CS_OPEN_ACTIVITY_CS_NEW_INVEST_DAY_BUY_TYPE), (*uipb.CSOpenActivityNewInvestDayBuy)(nil))
	gamecodec.RegisterMsg(codec.MessageType(uipb.MessageType_SC_OPEN_ACTIVITY_CS_NEW_INVEST_DAY_BUY_TYPE), (*uipb.SCOpenActivityNewInvestDayBuy)(nil))
}
