package delete

import (
	model "fgame/fgame/tools/dbdelete/model"
	tool "fgame/fgame/tools/dbdelete/tool"
	"fmt"
)

type playerMySqlDelete struct {
}

func (d *playerMySqlDelete) DeleteTable(p_db *model.DBConfigInfo, p_serverid int, p_table string, p_mysqlPath string) error {
	whereSql := fmt.Sprintf("EXISTS(select 1 from t_player where playerId=t_player.id and t_player.serverId=%d)", p_serverid)
	return tool.DeleteTable(p_db, p_table, whereSql, p_mysqlPath)
}

func (d *playerMySqlDelete) IsServer() bool {
	return false
}

var (
	playerTableArray = []string{
		"t_biaoche",
		"t_player_activity",
		"t_player_alchemy",
		"t_player_alliance",
		"t_player_alliance_skill",
		"t_player_anqi",
		"t_player_arena",
		"t_player_battle_property",
		"t_player_biaoche",
		"t_player_body_shield",
		"t_player_buff",
		"t_player_charge",
		"t_player_chess",
		"t_player_cross",
		"t_player_dan",
		"t_player_dragon",
		"t_player_email",
		"t_player_emperor_worship",
		"t_player_equipment_slot",
		"t_player_fashion",
		"t_player_fashion_wear",
		"t_player_first_charge",
		"t_player_first_charge_record",
		"t_player_found",
		"t_player_found_back",
		"t_player_four_god",
		"t_player_friend_black",
		"t_player_friend_invite",
		"t_player_friend_log",
		"t_player_func_open",
		"t_player_gamble",
		"t_player_gold_equip_slot",
		"t_player_huiyuan",
		"t_player_inventory",
		"t_player_item",
		"t_player_item_use",
		"t_player_juexue",
		"t_player_juexue_use",
		"t_player_lingyu",
		"t_player_lingyu_other",
		"t_player_lucky",
		"t_player_major_num",
		"t_player_marry",
		"t_player_marry_heroism",
		"t_player_mining",
		"t_player_moonlove",
		"t_player_mount",
		"t_player_mount_other",
		"t_player_onearena",
		"t_player_onearena_kun",
		"t_player_onearena_record",
		"t_player_onearena_robbed",
		"t_player_open_activity",
		"t_player_open_activity_charge",
		"t_player_open_activity_cost",
		"t_player_pk",
		"t_player_property",
		"t_player_quest",
		"t_player_relive",
		"t_player_scene",
		"t_player_secret_card",
		"t_player_shenfa",
		"t_player_shenfa_other",
		"t_player_shop",
		"t_player_skill",
		"t_player_skill_cd",
		"t_player_soul",
		"t_player_soul_embed",
		"t_player_soulruins",
		"t_player_soulruins_num",
		"t_player_soulruins_rewchapter",
		"t_player_tianjieta",
		"t_player_title",
		"t_player_title_wear",
		"t_player_tumo",
		"t_player_view_wedcard",
		"t_player_vip",
		"t_player_weapon",
		"t_player_weapon_info",
		"t_player_wing",
		"t_player_wing_other",
		"t_player_wing_trial",
		"t_player_xianfu",
		"t_player_xinfa",
		"t_player_xuechi",
		"t_player_fashion_trial",
		"t_player_pushwed_record",
		"t_player_compensate",
		"t_player_massacre",
		"t_player_tower",
		"t_player_tianshu",
		"t_player_myboss",
		"t_player_addition_sys_slot",
		"t_player_system_skill",
		"t_player_activity_num_record",
		"t_player_foe",
		"t_player_unreal_boss",
		"t_player_fabao_other",
		"t_player_fabao",
		"t_player_addition_sys_level",
		"t_player_xuedun",
		"t_player_material",
		"t_player_liveness",
		"t_player_liveness_quest",
		"t_player_xianti",
		"t_player_xianti_other",
		"t_player_cycle_charge_record",
		"t_player_foe_protect",
		"t_player_foe_feedback",
		"t_player_friend_feedback",
		"t_player_friend_add_rew",
		"t_player_daily",
		"t_player_bagua",
		"t_player_outland_boss",
		"t_player_open_activity_mail",
		"t_player_yuanbao_songbuting",
		"t_player_liveness_cross_five",
		"t_player_team_copy",
		"t_player_cache",
		"t_player_dense_wat",
		"t_player_dianxing",
		"t_player_tianmo",
		"t_player_wardrobe",
		"t_player_wardrobe_peiyang",
		"t_player_shihunfan",
		"t_player_lingtong_info",
		"t_player_lingtong",
		"t_player_lingtong_fashion",
		"t_player_lingtong_fashion_info",
		"t_player_lingtong_develop",
		"t_player_lingtong_other",
		"t_player_lingtong_power",
		"t_player_lingtong_fashion_trial",
		"t_player_cycle_cost_record",
		"t_player_kaifumubiao",
		"t_player_quest_crossday",
		"t_player_fei_sheng",
		"t_player_shenmo",
		"t_player_hongbao",
		"t_player_chat",
		"t_player_activity_pk",
		"t_player_friend_admire",
		"t_player_supreme_title_wear",
		"t_player_supreme_title",
		"t_player_equipbaoku",
		"t_player_activity_rank",
		"t_player_equipbaoku_shop",
		"t_player_mingge_pan",
		"t_player_mingge_pan_refined",
		"t_player_mingge_mingli",
		"t_player_tulong_equip_slot",
		"t_player_tulong_suit_skill",
		"t_player_shenqi_debris",
		"t_player_shenqi_smelt",
		"t_player_shenqi_qiling",
		"t_player_shenqi",
		"t_player_hunt",
		"t_player_zhenfa",
		"t_player_zhenqi",
		"t_player_zhenqi_xianhuo",
		"t_player_yinglingpu",
		"t_player_yinglingpu_suipian",
		"t_player_activity_add_num",
		"t_player_pregnant",
		"t_player_baby",
		"t_player_baby_toy_slot",
		"t_player_friend_marry_develop_send_log",
		"t_player_friend_marry_develop_recv_log",
		"t_player_marry_jinian",
		"t_player_marry_dingqing",
		"t_player_marry_jinian_sj",
		"t_player_qiyu",
		"t_player_trade_log",
		"t_player_shenyu",
		"t_player_xian_tao",
		"t_player_house",
		"t_player_trade_recycle",
		"t_player_activity_collect",
		"t_player_addition_sys_awake",
		"t_player_addition_sys_tongling",
		"t_player_alliance_yuxi",
		"t_player_week",
		"t_player_goldequip_log",
		"t_player_goldequip_setting",
		"t_player_fushi",
		"t_player_item_skill",
		"t_player_power_record",
		"t_player_shop_discount",

		"t_player_feisheng_receive",
		"t_player_qixue",
		"t_player_chuangshi_yugao",
		"t_player_mingge_buchang",
		"t_player_charm_add_log",
		"t_player_feedbackfee",
		"t_player_feedbackfee_record",
		"t_player_arenapvp",
		"t_player_arenapvp_guess_log",
		"t_player_daliwan",
		"t_player_wushuangweapon_slot",
		"t_player_jieyi",
		"t_player_zhenxi_boss",
		"t_player_new_first_charge_record",
		"t_player_boss_relive",
		"t_player_wushuang_settings",
		"t_player_goldequip",
		"t_player_mingge",
		"t_player_shenghen",
		"t_player_zhenfa_power",
		"t_player_tulong_equip",
		"t_player_baby_power",
		"t_player_addition_sys_lingzhu",
		"t_player_xianzun_card",
		"t_player_wushuang_buchang",
		"t_player_privilege_charge",
	}
)
var (
	playerDel = &playerMySqlDelete{}
)

func init() {

	for _, value := range playerTableArray {
		registerDelete(value, playerDel)
	}
}
