// Code generated by protoc-gen-go. DO NOT EDIT.
// source: battle.proto

package cross

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type PlayerBattleData struct {
	Level            *int32 `protobuf:"varint,1,opt,name=level" json:"level,omitempty"`
	ZhuanSheng       *int32 `protobuf:"varint,2,opt,name=zhuanSheng" json:"zhuanSheng,omitempty"`
	SoulAwakenNum    *int32 `protobuf:"varint,3,opt,name=soulAwakenNum" json:"soulAwakenNum,omitempty"`
	Vip              *int32 `protobuf:"varint,4,opt,name=vip" json:"vip,omitempty"`
	IsHuiYuan        *bool  `protobuf:"varint,5,opt,name=isHuiYuan" json:"isHuiYuan,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerBattleData) Reset()                    { *m = PlayerBattleData{} }
func (m *PlayerBattleData) String() string            { return proto.CompactTextString(m) }
func (*PlayerBattleData) ProtoMessage()               {}
func (*PlayerBattleData) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *PlayerBattleData) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *PlayerBattleData) GetZhuanSheng() int32 {
	if m != nil && m.ZhuanSheng != nil {
		return *m.ZhuanSheng
	}
	return 0
}

func (m *PlayerBattleData) GetSoulAwakenNum() int32 {
	if m != nil && m.SoulAwakenNum != nil {
		return *m.SoulAwakenNum
	}
	return 0
}

func (m *PlayerBattleData) GetVip() int32 {
	if m != nil && m.Vip != nil {
		return *m.Vip
	}
	return 0
}

func (m *PlayerBattleData) GetIsHuiYuan() bool {
	if m != nil && m.IsHuiYuan != nil {
		return *m.IsHuiYuan
	}
	return false
}

type SIPlayerBattleDataChanged struct {
	PlayerBattleData *PlayerBattleData `protobuf:"bytes,1,req,name=playerBattleData" json:"playerBattleData,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *SIPlayerBattleDataChanged) Reset()                    { *m = SIPlayerBattleDataChanged{} }
func (m *SIPlayerBattleDataChanged) String() string            { return proto.CompactTextString(m) }
func (*SIPlayerBattleDataChanged) ProtoMessage()               {}
func (*SIPlayerBattleDataChanged) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *SIPlayerBattleDataChanged) GetPlayerBattleData() *PlayerBattleData {
	if m != nil {
		return m.PlayerBattleData
	}
	return nil
}

func init() {
	proto.RegisterType((*PlayerBattleData)(nil), "cross.PlayerBattleData")
	proto.RegisterType((*SIPlayerBattleDataChanged)(nil), "cross.SIPlayerBattleDataChanged")
}

func init() { proto.RegisterFile("battle.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x4a, 0x2c, 0x29,
	0xc9, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4d, 0x2e, 0xca, 0x2f, 0x2e, 0x56,
	0xca, 0xe1, 0x12, 0x08, 0xc8, 0x49, 0xac, 0x4c, 0x2d, 0x72, 0x02, 0x4b, 0xba, 0x24, 0x96, 0x24,
	0x0a, 0xf1, 0x72, 0xb1, 0xe6, 0xa4, 0x96, 0xa5, 0xe6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x0a,
	0x09, 0x71, 0x71, 0x55, 0x65, 0x94, 0x26, 0xe6, 0x05, 0x67, 0xa4, 0xe6, 0xa5, 0x4b, 0x30, 0x81,
	0xc5, 0x44, 0xb9, 0x78, 0x8b, 0xf3, 0x4b, 0x73, 0x1c, 0xcb, 0x13, 0xb3, 0x53, 0xf3, 0xfc, 0x4a,
	0x73, 0x25, 0x98, 0xc1, 0xc2, 0xdc, 0x5c, 0xcc, 0x65, 0x99, 0x05, 0x12, 0x2c, 0x60, 0x8e, 0x20,
	0x17, 0x67, 0x66, 0xb1, 0x47, 0x69, 0x66, 0x64, 0x69, 0x62, 0x9e, 0x04, 0xab, 0x02, 0xa3, 0x06,
	0x87, 0x92, 0x1f, 0x97, 0x64, 0xb0, 0x27, 0xba, 0x7d, 0xce, 0x19, 0x89, 0x79, 0xe9, 0xa9, 0x29,
	0x42, 0x86, 0x5c, 0x02, 0x05, 0x68, 0x52, 0x12, 0x8c, 0x0a, 0x4c, 0x1a, 0xdc, 0x46, 0xe2, 0x7a,
	0x60, 0xc7, 0xea, 0xa1, 0xeb, 0x04, 0x04, 0x00, 0x00, 0xff, 0xff, 0x4f, 0xa7, 0x26, 0xc0, 0xd3,
	0x00, 0x00, 0x00,
}
