// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chuangshi.proto

package cross

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ChuangShiData struct {
	Pos              *int32 `protobuf:"varint,1,req,name=pos" json:"pos,omitempty"`
	CampType         *int32 `protobuf:"varint,2,req,name=campType" json:"campType,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ChuangShiData) Reset()                    { *m = ChuangShiData{} }
func (m *ChuangShiData) String() string            { return proto.CompactTextString(m) }
func (*ChuangShiData) ProtoMessage()               {}
func (*ChuangShiData) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

func (m *ChuangShiData) GetPos() int32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

func (m *ChuangShiData) GetCampType() int32 {
	if m != nil && m.CampType != nil {
		return *m.CampType
	}
	return 0
}

type SIChuangShiEnterCity struct {
	CityId           *int64 `protobuf:"varint,1,req,name=cityId" json:"cityId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SIChuangShiEnterCity) Reset()                    { *m = SIChuangShiEnterCity{} }
func (m *SIChuangShiEnterCity) String() string            { return proto.CompactTextString(m) }
func (*SIChuangShiEnterCity) ProtoMessage()               {}
func (*SIChuangShiEnterCity) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{1} }

func (m *SIChuangShiEnterCity) GetCityId() int64 {
	if m != nil && m.CityId != nil {
		return *m.CityId
	}
	return 0
}

type ISChuangShiEnterCity struct {
	IsLineUp         *bool  `protobuf:"varint,1,req,name=isLineUp" json:"isLineUp,omitempty"`
	SceneId          *int64 `protobuf:"varint,2,req,name=sceneId" json:"sceneId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ISChuangShiEnterCity) Reset()                    { *m = ISChuangShiEnterCity{} }
func (m *ISChuangShiEnterCity) String() string            { return proto.CompactTextString(m) }
func (*ISChuangShiEnterCity) ProtoMessage()               {}
func (*ISChuangShiEnterCity) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{2} }

func (m *ISChuangShiEnterCity) GetIsLineUp() bool {
	if m != nil && m.IsLineUp != nil {
		return *m.IsLineUp
	}
	return false
}

func (m *ISChuangShiEnterCity) GetSceneId() int64 {
	if m != nil && m.SceneId != nil {
		return *m.SceneId
	}
	return 0
}

type ISChuangShiKillPlayer struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ISChuangShiKillPlayer) Reset()                    { *m = ISChuangShiKillPlayer{} }
func (m *ISChuangShiKillPlayer) String() string            { return proto.CompactTextString(m) }
func (*ISChuangShiKillPlayer) ProtoMessage()               {}
func (*ISChuangShiKillPlayer) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{3} }

type SIChuangShiSceneFinish struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SIChuangShiSceneFinish) Reset()                    { *m = SIChuangShiSceneFinish{} }
func (m *SIChuangShiSceneFinish) String() string            { return proto.CompactTextString(m) }
func (*SIChuangShiSceneFinish) ProtoMessage()               {}
func (*SIChuangShiSceneFinish) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{4} }

type ISChuangShiSceneFinish struct {
	Win              *bool  `protobuf:"varint,1,req,name=win" json:"win,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ISChuangShiSceneFinish) Reset()                    { *m = ISChuangShiSceneFinish{} }
func (m *ISChuangShiSceneFinish) String() string            { return proto.CompactTextString(m) }
func (*ISChuangShiSceneFinish) ProtoMessage()               {}
func (*ISChuangShiSceneFinish) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{5} }

func (m *ISChuangShiSceneFinish) GetWin() bool {
	if m != nil && m.Win != nil {
		return *m.Win
	}
	return false
}

func init() {
	proto.RegisterType((*ChuangShiData)(nil), "cross.ChuangShiData")
	proto.RegisterType((*SIChuangShiEnterCity)(nil), "cross.SIChuangShiEnterCity")
	proto.RegisterType((*ISChuangShiEnterCity)(nil), "cross.ISChuangShiEnterCity")
	proto.RegisterType((*ISChuangShiKillPlayer)(nil), "cross.ISChuangShiKillPlayer")
	proto.RegisterType((*SIChuangShiSceneFinish)(nil), "cross.SIChuangShiSceneFinish")
	proto.RegisterType((*ISChuangShiSceneFinish)(nil), "cross.ISChuangShiSceneFinish")
}

func init() { proto.RegisterFile("chuangshi.proto", fileDescriptor6) }

var fileDescriptor6 = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0xcf, 0x31, 0x4b, 0xc5, 0x30,
	0x14, 0x05, 0x60, 0x6c, 0xa9, 0x96, 0x2b, 0xda, 0x12, 0x6a, 0xed, 0x28, 0x01, 0xc5, 0xa9, 0xbb,
	0x73, 0x55, 0x08, 0x3a, 0x08, 0xd1, 0x1f, 0x10, 0xd2, 0x60, 0x2e, 0xd4, 0x24, 0x24, 0x11, 0xc9,
	0xbf, 0x97, 0xe6, 0xc1, 0x23, 0xc3, 0x5b, 0xef, 0x39, 0x1f, 0x87, 0x0b, 0x9d, 0xd4, 0xbf, 0xc2,
	0x7c, 0x07, 0x8d, 0xb3, 0xf3, 0x36, 0x5a, 0xd2, 0x48, 0x6f, 0x43, 0xa0, 0x33, 0x5c, 0x2d, 0x39,
	0xe1, 0x1a, 0x9f, 0x45, 0x14, 0xe4, 0x12, 0x6a, 0x67, 0xc3, 0x74, 0x76, 0x57, 0x3d, 0x36, 0xa4,
	0x87, 0x56, 0x8a, 0x1f, 0xf7, 0x99, 0x9c, 0x9a, 0xaa, 0xfd, 0x42, 0x1f, 0x60, 0xe0, 0xec, 0x28,
	0x5e, 0x4c, 0x54, 0x7e, 0xc1, 0x98, 0xc8, 0x35, 0x9c, 0x4b, 0x8c, 0x89, 0xad, 0x59, 0xd6, 0xf4,
	0x09, 0x06, 0xc6, 0x4f, 0xf4, 0x7a, 0x68, 0x31, 0xbc, 0xa3, 0x51, 0x5f, 0x2e, 0x37, 0x5b, 0xd2,
	0xc1, 0x45, 0x90, 0xca, 0x28, 0xb6, 0xe6, 0x89, 0x9a, 0xde, 0xc2, 0x4d, 0x41, 0xdf, 0x70, 0xdb,
	0x3e, 0x36, 0x91, 0x94, 0xa7, 0x13, 0x8c, 0xc5, 0x36, 0xdf, 0xd1, 0x2b, 0x1a, 0x0c, 0x9a, 0xde,
	0xc3, 0x58, 0x90, 0x22, 0xd9, 0xdf, 0xf9, 0x43, 0x73, 0x98, 0xfa, 0x0f, 0x00, 0x00, 0xff, 0xff,
	0x96, 0x8e, 0x55, 0x63, 0x05, 0x01, 0x00, 0x00,
}
