// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dense_wat.proto

package cross

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type DenseWatData struct {
	Num              *int32 `protobuf:"varint,1,req,name=num" json:"num,omitempty"`
	EndTime          *int64 `protobuf:"varint,2,req,name=endTime" json:"endTime,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DenseWatData) Reset()                    { *m = DenseWatData{} }
func (m *DenseWatData) String() string            { return proto.CompactTextString(m) }
func (*DenseWatData) ProtoMessage()               {}
func (*DenseWatData) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{0} }

func (m *DenseWatData) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

func (m *DenseWatData) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

type ISDenseWatSync struct {
	DensWatData      *DenseWatData `protobuf:"bytes,1,req,name=densWatData" json:"densWatData,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *ISDenseWatSync) Reset()                    { *m = ISDenseWatSync{} }
func (m *ISDenseWatSync) String() string            { return proto.CompactTextString(m) }
func (*ISDenseWatSync) ProtoMessage()               {}
func (*ISDenseWatSync) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{1} }

func (m *ISDenseWatSync) GetDensWatData() *DenseWatData {
	if m != nil {
		return m.DensWatData
	}
	return nil
}

type SIDenseWatSync struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SIDenseWatSync) Reset()                    { *m = SIDenseWatSync{} }
func (m *SIDenseWatSync) String() string            { return proto.CompactTextString(m) }
func (*SIDenseWatSync) ProtoMessage()               {}
func (*SIDenseWatSync) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{2} }

func init() {
	proto.RegisterType((*DenseWatData)(nil), "cross.DenseWatData")
	proto.RegisterType((*ISDenseWatSync)(nil), "cross.ISDenseWatSync")
	proto.RegisterType((*SIDenseWatSync)(nil), "cross.SIDenseWatSync")
}

func init() { proto.RegisterFile("dense_wat.proto", fileDescriptor9) }

var fileDescriptor9 = []byte{
	// 140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0x49, 0xcd, 0x2b,
	0x4e, 0x8d, 0x2f, 0x4f, 0x2c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4d, 0x2e, 0xca,
	0x2f, 0x2e, 0x96, 0xe2, 0xca, 0x2c, 0x49, 0xcd, 0x85, 0x08, 0x29, 0xe9, 0x70, 0xf1, 0xb8, 0x80,
	0x54, 0x85, 0x27, 0x96, 0xb8, 0x24, 0x96, 0x24, 0x0a, 0x71, 0x73, 0x31, 0xe7, 0x95, 0xe6, 0x4a,
	0x30, 0x2a, 0x30, 0x69, 0xb0, 0x0a, 0xf1, 0x73, 0xb1, 0xa7, 0xe6, 0xa5, 0x84, 0x64, 0xe6, 0xa6,
	0x4a, 0x30, 0x29, 0x30, 0x69, 0x30, 0x2b, 0x59, 0x71, 0xf1, 0x79, 0x06, 0xc3, 0xd4, 0x07, 0x57,
	0xe6, 0x25, 0x0b, 0x69, 0x70, 0x71, 0x83, 0x6c, 0x81, 0x6a, 0x07, 0xeb, 0xe3, 0x36, 0x12, 0xd6,
	0x03, 0x5b, 0xa4, 0x87, 0x6c, 0xb2, 0x92, 0x00, 0x17, 0x5f, 0xb0, 0x27, 0xb2, 0x5e, 0x40, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x49, 0x12, 0x79, 0x84, 0xa0, 0x00, 0x00, 0x00,
}
