// Code generated by protoc-gen-go. DO NOT EDIT.
// source: connect.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	connect.proto

It has these top-level messages:
	Message
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Body []byte `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "pb.Message")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Connection service

type ConnectionClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (Connection_ConnectClient, error)
}

type connectionClient struct {
	cc *grpc.ClientConn
}

func NewConnectionClient(cc *grpc.ClientConn) ConnectionClient {
	return &connectionClient{cc}
}

func (c *connectionClient) Connect(ctx context.Context, opts ...grpc.CallOption) (Connection_ConnectClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Connection_serviceDesc.Streams[0], c.cc, "/pb.Connection/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &connectionConnectClient{stream}
	return x, nil
}

type Connection_ConnectClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type connectionConnectClient struct {
	grpc.ClientStream
}

func (x *connectionConnectClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *connectionConnectClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Connection service

type ConnectionServer interface {
	Connect(Connection_ConnectServer) error
}

func RegisterConnectionServer(s *grpc.Server, srv ConnectionServer) {
	s.RegisterService(&_Connection_serviceDesc, srv)
}

func _Connection_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConnectionServer).Connect(&connectionConnectServer{stream})
}

type Connection_ConnectServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type connectionConnectServer struct {
	grpc.ServerStream
}

func (x *connectionConnectServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *connectionConnectServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Connection_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Connection",
	HandlerType: (*ConnectionServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _Connection_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "connect.proto",
}

func init() { proto.RegisterFile("connect.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 109 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0xcf, 0xcb,
	0x4b, 0x4d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x92, 0xe5,
	0x62, 0xf7, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x15, 0x12, 0xe2, 0x62, 0x49, 0xca, 0x4f, 0xa9,
	0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x09, 0x02, 0xb3, 0x8d, 0xcc, 0xb9, 0xb8, 0x9c, 0x21, 0x7a,
	0x32, 0xf3, 0xf3, 0x84, 0x34, 0xb9, 0xd8, 0xa1, 0x3c, 0x21, 0x6e, 0xbd, 0x82, 0x24, 0x3d, 0xa8,
	0x4e, 0x29, 0x64, 0x8e, 0x12, 0x83, 0x06, 0xa3, 0x01, 0x63, 0x12, 0x1b, 0xd8, 0x0a, 0x63, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x1b, 0xf7, 0x6f, 0x36, 0x73, 0x00, 0x00, 0x00,
}
