// Code generated by protoc-gen-go. DO NOT EDIT.
// source: baby.proto

package ui

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type DongFangInfo struct {
	PregnantTime     *int64 `protobuf:"varint,1,opt,name=pregnantTime" json:"pregnantTime,omitempty"`
	TonicPro         *int32 `protobuf:"varint,2,opt,name=tonicPro" json:"tonicPro,omitempty"`
	BabyNum          *int32 `protobuf:"varint,3,opt,name=babyNum" json:"babyNum,omitempty"`
	ChaoshengNum     *int32 `protobuf:"varint,4,opt,name=chaoshengNum" json:"chaoshengNum,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DongFangInfo) Reset()                    { *m = DongFangInfo{} }
func (m *DongFangInfo) String() string            { return proto.CompactTextString(m) }
func (*DongFangInfo) ProtoMessage()               {}
func (*DongFangInfo) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{0} }

func (m *DongFangInfo) GetPregnantTime() int64 {
	if m != nil && m.PregnantTime != nil {
		return *m.PregnantTime
	}
	return 0
}

func (m *DongFangInfo) GetTonicPro() int32 {
	if m != nil && m.TonicPro != nil {
		return *m.TonicPro
	}
	return 0
}

func (m *DongFangInfo) GetBabyNum() int32 {
	if m != nil && m.BabyNum != nil {
		return *m.BabyNum
	}
	return 0
}

func (m *DongFangInfo) GetChaoshengNum() int32 {
	if m != nil && m.ChaoshengNum != nil {
		return *m.ChaoshengNum
	}
	return 0
}

type TalentInfo struct {
	SkillId          *int32 `protobuf:"varint,1,req,name=skillId" json:"skillId,omitempty"`
	Status           *int32 `protobuf:"varint,2,req,name=status" json:"status,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *TalentInfo) Reset()                    { *m = TalentInfo{} }
func (m *TalentInfo) String() string            { return proto.CompactTextString(m) }
func (*TalentInfo) ProtoMessage()               {}
func (*TalentInfo) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{1} }

func (m *TalentInfo) GetSkillId() int32 {
	if m != nil && m.SkillId != nil {
		return *m.SkillId
	}
	return 0
}

func (m *TalentInfo) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

type BabyInfo struct {
	ActivateTimes    *int32        `protobuf:"varint,1,req,name=activateTimes" json:"activateTimes,omitempty"`
	TalentList       []*TalentInfo `protobuf:"bytes,2,rep,name=talentList" json:"talentList,omitempty"`
	BabyName         *string       `protobuf:"bytes,3,req,name=babyName" json:"babyName,omitempty"`
	Sex              *int32        `protobuf:"varint,4,req,name=sex" json:"sex,omitempty"`
	Danbei           *int32        `protobuf:"varint,5,req,name=danbei" json:"danbei,omitempty"`
	Quality          *int32        `protobuf:"varint,6,req,name=quality" json:"quality,omitempty"`
	LearnLevel       *int32        `protobuf:"varint,7,req,name=learnLevel" json:"learnLevel,omitempty"`
	BabyId           *int64        `protobuf:"varint,8,req,name=babyId" json:"babyId,omitempty"`
	LockTims         *int32        `protobuf:"varint,9,req,name=lockTims" json:"lockTims,omitempty"`
	RefreshTimes     *int32        `protobuf:"varint,10,req,name=refreshTimes" json:"refreshTimes,omitempty"`
	LearnExp         *int32        `protobuf:"varint,11,req,name=learnExp" json:"learnExp,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *BabyInfo) Reset()                    { *m = BabyInfo{} }
func (m *BabyInfo) String() string            { return proto.CompactTextString(m) }
func (*BabyInfo) ProtoMessage()               {}
func (*BabyInfo) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{2} }

func (m *BabyInfo) GetActivateTimes() int32 {
	if m != nil && m.ActivateTimes != nil {
		return *m.ActivateTimes
	}
	return 0
}

func (m *BabyInfo) GetTalentList() []*TalentInfo {
	if m != nil {
		return m.TalentList
	}
	return nil
}

func (m *BabyInfo) GetBabyName() string {
	if m != nil && m.BabyName != nil {
		return *m.BabyName
	}
	return ""
}

func (m *BabyInfo) GetSex() int32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func (m *BabyInfo) GetDanbei() int32 {
	if m != nil && m.Danbei != nil {
		return *m.Danbei
	}
	return 0
}

func (m *BabyInfo) GetQuality() int32 {
	if m != nil && m.Quality != nil {
		return *m.Quality
	}
	return 0
}

func (m *BabyInfo) GetLearnLevel() int32 {
	if m != nil && m.LearnLevel != nil {
		return *m.LearnLevel
	}
	return 0
}

func (m *BabyInfo) GetBabyId() int64 {
	if m != nil && m.BabyId != nil {
		return *m.BabyId
	}
	return 0
}

func (m *BabyInfo) GetLockTims() int32 {
	if m != nil && m.LockTims != nil {
		return *m.LockTims
	}
	return 0
}

func (m *BabyInfo) GetRefreshTimes() int32 {
	if m != nil && m.RefreshTimes != nil {
		return *m.RefreshTimes
	}
	return 0
}

func (m *BabyInfo) GetLearnExp() int32 {
	if m != nil && m.LearnExp != nil {
		return *m.LearnExp
	}
	return 0
}

type ToySlotInfo struct {
	Level            *int32 `protobuf:"varint,1,req,name=level" json:"level,omitempty"`
	SlotId           *int32 `protobuf:"varint,2,req,name=slotId" json:"slotId,omitempty"`
	ItemId           *int32 `protobuf:"varint,3,req,name=itemId" json:"itemId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ToySlotInfo) Reset()                    { *m = ToySlotInfo{} }
func (m *ToySlotInfo) String() string            { return proto.CompactTextString(m) }
func (*ToySlotInfo) ProtoMessage()               {}
func (*ToySlotInfo) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{3} }

func (m *ToySlotInfo) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *ToySlotInfo) GetSlotId() int32 {
	if m != nil && m.SlotId != nil {
		return *m.SlotId
	}
	return 0
}

func (m *ToySlotInfo) GetItemId() int32 {
	if m != nil && m.ItemId != nil {
		return *m.ItemId
	}
	return 0
}

type ToySuitInfo struct {
	SuitType         *int32         `protobuf:"varint,1,req,name=suitType" json:"suitType,omitempty"`
	SlotInfo         []*ToySlotInfo `protobuf:"bytes,2,rep,name=slotInfo" json:"slotInfo,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *ToySuitInfo) Reset()                    { *m = ToySuitInfo{} }
func (m *ToySuitInfo) String() string            { return proto.CompactTextString(m) }
func (*ToySuitInfo) ProtoMessage()               {}
func (*ToySuitInfo) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{4} }

func (m *ToySuitInfo) GetSuitType() int32 {
	if m != nil && m.SuitType != nil {
		return *m.SuitType
	}
	return 0
}

func (m *ToySuitInfo) GetSlotInfo() []*ToySlotInfo {
	if m != nil {
		return m.SlotInfo
	}
	return nil
}

type CSBabyInfo struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSBabyInfo) Reset()                    { *m = CSBabyInfo{} }
func (m *CSBabyInfo) String() string            { return proto.CompactTextString(m) }
func (*CSBabyInfo) ProtoMessage()               {}
func (*CSBabyInfo) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{5} }

type SCBabyInfo struct {
	DongfangInfo     *DongFangInfo  `protobuf:"bytes,1,req,name=dongfangInfo" json:"dongfangInfo,omitempty"`
	BabyInfoList     []*BabyInfo    `protobuf:"bytes,2,rep,name=babyInfoList" json:"babyInfoList,omitempty"`
	ToySuitInfoList  []*ToySuitInfo `protobuf:"bytes,3,rep,name=toySuitInfoList" json:"toySuitInfoList,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *SCBabyInfo) Reset()                    { *m = SCBabyInfo{} }
func (m *SCBabyInfo) String() string            { return proto.CompactTextString(m) }
func (*SCBabyInfo) ProtoMessage()               {}
func (*SCBabyInfo) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{6} }

func (m *SCBabyInfo) GetDongfangInfo() *DongFangInfo {
	if m != nil {
		return m.DongfangInfo
	}
	return nil
}

func (m *SCBabyInfo) GetBabyInfoList() []*BabyInfo {
	if m != nil {
		return m.BabyInfoList
	}
	return nil
}

func (m *SCBabyInfo) GetToySuitInfoList() []*ToySuitInfo {
	if m != nil {
		return m.ToySuitInfoList
	}
	return nil
}

type CSBabyDongFang struct {
	IsUseItem        *bool  `protobuf:"varint,1,req,name=isUseItem" json:"isUseItem,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSBabyDongFang) Reset()                    { *m = CSBabyDongFang{} }
func (m *CSBabyDongFang) String() string            { return proto.CompactTextString(m) }
func (*CSBabyDongFang) ProtoMessage()               {}
func (*CSBabyDongFang) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{7} }

func (m *CSBabyDongFang) GetIsUseItem() bool {
	if m != nil && m.IsUseItem != nil {
		return *m.IsUseItem
	}
	return false
}

type SCBabyDongFang struct {
	IsUseItem        *bool       `protobuf:"varint,1,req,name=isUseItem" json:"isUseItem,omitempty"`
	IsBorn           *bool       `protobuf:"varint,2,req,name=isBorn" json:"isBorn,omitempty"`
	DropInfo         []*DropInfo `protobuf:"bytes,3,rep,name=dropInfo" json:"dropInfo,omitempty"`
	BabyInfo         *BabyInfo   `protobuf:"bytes,4,opt,name=babyInfo" json:"babyInfo,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *SCBabyDongFang) Reset()                    { *m = SCBabyDongFang{} }
func (m *SCBabyDongFang) String() string            { return proto.CompactTextString(m) }
func (*SCBabyDongFang) ProtoMessage()               {}
func (*SCBabyDongFang) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{8} }

func (m *SCBabyDongFang) GetIsUseItem() bool {
	if m != nil && m.IsUseItem != nil {
		return *m.IsUseItem
	}
	return false
}

func (m *SCBabyDongFang) GetIsBorn() bool {
	if m != nil && m.IsBorn != nil {
		return *m.IsBorn
	}
	return false
}

func (m *SCBabyDongFang) GetDropInfo() []*DropInfo {
	if m != nil {
		return m.DropInfo
	}
	return nil
}

func (m *SCBabyDongFang) GetBabyInfo() *BabyInfo {
	if m != nil {
		return m.BabyInfo
	}
	return nil
}

type CSBabyBornAccelerate struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSBabyBornAccelerate) Reset()                    { *m = CSBabyBornAccelerate{} }
func (m *CSBabyBornAccelerate) String() string            { return proto.CompactTextString(m) }
func (*CSBabyBornAccelerate) ProtoMessage()               {}
func (*CSBabyBornAccelerate) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{9} }

type SCBabyBornAccelerate struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCBabyBornAccelerate) Reset()                    { *m = SCBabyBornAccelerate{} }
func (m *SCBabyBornAccelerate) String() string            { return proto.CompactTextString(m) }
func (*SCBabyBornAccelerate) ProtoMessage()               {}
func (*SCBabyBornAccelerate) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{10} }

type CSBabyEatTonic struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSBabyEatTonic) Reset()                    { *m = CSBabyEatTonic{} }
func (m *CSBabyEatTonic) String() string            { return proto.CompactTextString(m) }
func (*CSBabyEatTonic) ProtoMessage()               {}
func (*CSBabyEatTonic) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{11} }

type SCBabyEatTonic struct {
	AddPro           *int32 `protobuf:"varint,1,req,name=addPro" json:"addPro,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCBabyEatTonic) Reset()                    { *m = SCBabyEatTonic{} }
func (m *SCBabyEatTonic) String() string            { return proto.CompactTextString(m) }
func (*SCBabyEatTonic) ProtoMessage()               {}
func (*SCBabyEatTonic) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{12} }

func (m *SCBabyEatTonic) GetAddPro() int32 {
	if m != nil && m.AddPro != nil {
		return *m.AddPro
	}
	return 0
}

type CSBabyBornChaoSheng struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSBabyBornChaoSheng) Reset()                    { *m = CSBabyBornChaoSheng{} }
func (m *CSBabyBornChaoSheng) String() string            { return proto.CompactTextString(m) }
func (*CSBabyBornChaoSheng) ProtoMessage()               {}
func (*CSBabyBornChaoSheng) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{13} }

type SCBabyBornChaoSheng struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCBabyBornChaoSheng) Reset()                    { *m = SCBabyBornChaoSheng{} }
func (m *SCBabyBornChaoSheng) String() string            { return proto.CompactTextString(m) }
func (*SCBabyBornChaoSheng) ProtoMessage()               {}
func (*SCBabyBornChaoSheng) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{14} }

type SCBabyBornNotice struct {
	BabyInfo         *BabyInfo `protobuf:"bytes,1,req,name=babyInfo" json:"babyInfo,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *SCBabyBornNotice) Reset()                    { *m = SCBabyBornNotice{} }
func (m *SCBabyBornNotice) String() string            { return proto.CompactTextString(m) }
func (*SCBabyBornNotice) ProtoMessage()               {}
func (*SCBabyBornNotice) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{15} }

func (m *SCBabyBornNotice) GetBabyInfo() *BabyInfo {
	if m != nil {
		return m.BabyInfo
	}
	return nil
}

type SCBabyBornSpouseNotice struct {
	EmailId          *int64 `protobuf:"varint,1,req,name=emailId" json:"emailId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCBabyBornSpouseNotice) Reset()                    { *m = SCBabyBornSpouseNotice{} }
func (m *SCBabyBornSpouseNotice) String() string            { return proto.CompactTextString(m) }
func (*SCBabyBornSpouseNotice) ProtoMessage()               {}
func (*SCBabyBornSpouseNotice) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{16} }

func (m *SCBabyBornSpouseNotice) GetEmailId() int64 {
	if m != nil && m.EmailId != nil {
		return *m.EmailId
	}
	return 0
}

type SCBabyBornMessageNotice struct {
	BornTime         *int64 `protobuf:"varint,1,req,name=bornTime" json:"bornTime,omitempty"`
	NoticeTime       *int64 `protobuf:"varint,2,req,name=noticeTime" json:"noticeTime,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCBabyBornMessageNotice) Reset()                    { *m = SCBabyBornMessageNotice{} }
func (m *SCBabyBornMessageNotice) String() string            { return proto.CompactTextString(m) }
func (*SCBabyBornMessageNotice) ProtoMessage()               {}
func (*SCBabyBornMessageNotice) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{17} }

func (m *SCBabyBornMessageNotice) GetBornTime() int64 {
	if m != nil && m.BornTime != nil {
		return *m.BornTime
	}
	return 0
}

func (m *SCBabyBornMessageNotice) GetNoticeTime() int64 {
	if m != nil && m.NoticeTime != nil {
		return *m.NoticeTime
	}
	return 0
}

type CSBabyChangeName struct {
	BabyId           *int64  `protobuf:"varint,1,req,name=babyId" json:"babyId,omitempty"`
	NewName          *string `protobuf:"bytes,2,req,name=newName" json:"newName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CSBabyChangeName) Reset()                    { *m = CSBabyChangeName{} }
func (m *CSBabyChangeName) String() string            { return proto.CompactTextString(m) }
func (*CSBabyChangeName) ProtoMessage()               {}
func (*CSBabyChangeName) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{18} }

func (m *CSBabyChangeName) GetBabyId() int64 {
	if m != nil && m.BabyId != nil {
		return *m.BabyId
	}
	return 0
}

func (m *CSBabyChangeName) GetNewName() string {
	if m != nil && m.NewName != nil {
		return *m.NewName
	}
	return ""
}

type SCBabyChangeName struct {
	BabyId           *int64  `protobuf:"varint,1,req,name=babyId" json:"babyId,omitempty"`
	NewName          *string `protobuf:"bytes,2,req,name=newName" json:"newName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SCBabyChangeName) Reset()                    { *m = SCBabyChangeName{} }
func (m *SCBabyChangeName) String() string            { return proto.CompactTextString(m) }
func (*SCBabyChangeName) ProtoMessage()               {}
func (*SCBabyChangeName) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{19} }

func (m *SCBabyChangeName) GetBabyId() int64 {
	if m != nil && m.BabyId != nil {
		return *m.BabyId
	}
	return 0
}

func (m *SCBabyChangeName) GetNewName() string {
	if m != nil && m.NewName != nil {
		return *m.NewName
	}
	return ""
}

type CSBabyActivateSkill struct {
	BabyId           *int64 `protobuf:"varint,1,req,name=babyId" json:"babyId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSBabyActivateSkill) Reset()                    { *m = CSBabyActivateSkill{} }
func (m *CSBabyActivateSkill) String() string            { return proto.CompactTextString(m) }
func (*CSBabyActivateSkill) ProtoMessage()               {}
func (*CSBabyActivateSkill) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{20} }

func (m *CSBabyActivateSkill) GetBabyId() int64 {
	if m != nil && m.BabyId != nil {
		return *m.BabyId
	}
	return 0
}

type SCBabyActivateSkill struct {
	BabyId           *int64        `protobuf:"varint,1,req,name=babyId" json:"babyId,omitempty"`
	TalentList       []*TalentInfo `protobuf:"bytes,2,rep,name=talentList" json:"talentList,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *SCBabyActivateSkill) Reset()                    { *m = SCBabyActivateSkill{} }
func (m *SCBabyActivateSkill) String() string            { return proto.CompactTextString(m) }
func (*SCBabyActivateSkill) ProtoMessage()               {}
func (*SCBabyActivateSkill) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{21} }

func (m *SCBabyActivateSkill) GetBabyId() int64 {
	if m != nil && m.BabyId != nil {
		return *m.BabyId
	}
	return 0
}

func (m *SCBabyActivateSkill) GetTalentList() []*TalentInfo {
	if m != nil {
		return m.TalentList
	}
	return nil
}

type CSBabyLockSkill struct {
	BabyId           *int64 `protobuf:"varint,1,req,name=babyId" json:"babyId,omitempty"`
	SkillIndex       *int32 `protobuf:"varint,2,req,name=skillIndex" json:"skillIndex,omitempty"`
	Operation        *int32 `protobuf:"varint,3,req,name=operation" json:"operation,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSBabyLockSkill) Reset()                    { *m = CSBabyLockSkill{} }
func (m *CSBabyLockSkill) String() string            { return proto.CompactTextString(m) }
func (*CSBabyLockSkill) ProtoMessage()               {}
func (*CSBabyLockSkill) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{22} }

func (m *CSBabyLockSkill) GetBabyId() int64 {
	if m != nil && m.BabyId != nil {
		return *m.BabyId
	}
	return 0
}

func (m *CSBabyLockSkill) GetSkillIndex() int32 {
	if m != nil && m.SkillIndex != nil {
		return *m.SkillIndex
	}
	return 0
}

func (m *CSBabyLockSkill) GetOperation() int32 {
	if m != nil && m.Operation != nil {
		return *m.Operation
	}
	return 0
}

type SCBabyLockSkill struct {
	BabyId           *int64 `protobuf:"varint,1,req,name=babyId" json:"babyId,omitempty"`
	SkillIndex       *int32 `protobuf:"varint,2,req,name=skillIndex" json:"skillIndex,omitempty"`
	Operation        *int32 `protobuf:"varint,3,req,name=operation" json:"operation,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCBabyLockSkill) Reset()                    { *m = SCBabyLockSkill{} }
func (m *SCBabyLockSkill) String() string            { return proto.CompactTextString(m) }
func (*SCBabyLockSkill) ProtoMessage()               {}
func (*SCBabyLockSkill) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{23} }

func (m *SCBabyLockSkill) GetBabyId() int64 {
	if m != nil && m.BabyId != nil {
		return *m.BabyId
	}
	return 0
}

func (m *SCBabyLockSkill) GetSkillIndex() int32 {
	if m != nil && m.SkillIndex != nil {
		return *m.SkillIndex
	}
	return 0
}

func (m *SCBabyLockSkill) GetOperation() int32 {
	if m != nil && m.Operation != nil {
		return *m.Operation
	}
	return 0
}

type CSBabyRefreshSkill struct {
	BabyId           *int64 `protobuf:"varint,1,req,name=babyId" json:"babyId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSBabyRefreshSkill) Reset()                    { *m = CSBabyRefreshSkill{} }
func (m *CSBabyRefreshSkill) String() string            { return proto.CompactTextString(m) }
func (*CSBabyRefreshSkill) ProtoMessage()               {}
func (*CSBabyRefreshSkill) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{24} }

func (m *CSBabyRefreshSkill) GetBabyId() int64 {
	if m != nil && m.BabyId != nil {
		return *m.BabyId
	}
	return 0
}

type SCBabyRefreshSkill struct {
	BabyId           *int64        `protobuf:"varint,1,req,name=babyId" json:"babyId,omitempty"`
	TalentList       []*TalentInfo `protobuf:"bytes,2,rep,name=talentList" json:"talentList,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *SCBabyRefreshSkill) Reset()                    { *m = SCBabyRefreshSkill{} }
func (m *SCBabyRefreshSkill) String() string            { return proto.CompactTextString(m) }
func (*SCBabyRefreshSkill) ProtoMessage()               {}
func (*SCBabyRefreshSkill) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{25} }

func (m *SCBabyRefreshSkill) GetBabyId() int64 {
	if m != nil && m.BabyId != nil {
		return *m.BabyId
	}
	return 0
}

func (m *SCBabyRefreshSkill) GetTalentList() []*TalentInfo {
	if m != nil {
		return m.TalentList
	}
	return nil
}

type CSBabyLearnUplevel struct {
	IsAuto           *bool  `protobuf:"varint,1,req,name=isAuto" json:"isAuto,omitempty"`
	ItemId           *int32 `protobuf:"varint,2,req,name=itemId" json:"itemId,omitempty"`
	Num              *int32 `protobuf:"varint,3,req,name=num" json:"num,omitempty"`
	BabyId           *int64 `protobuf:"varint,4,req,name=babyId" json:"babyId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSBabyLearnUplevel) Reset()                    { *m = CSBabyLearnUplevel{} }
func (m *CSBabyLearnUplevel) String() string            { return proto.CompactTextString(m) }
func (*CSBabyLearnUplevel) ProtoMessage()               {}
func (*CSBabyLearnUplevel) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{26} }

func (m *CSBabyLearnUplevel) GetIsAuto() bool {
	if m != nil && m.IsAuto != nil {
		return *m.IsAuto
	}
	return false
}

func (m *CSBabyLearnUplevel) GetItemId() int32 {
	if m != nil && m.ItemId != nil {
		return *m.ItemId
	}
	return 0
}

func (m *CSBabyLearnUplevel) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

func (m *CSBabyLearnUplevel) GetBabyId() int64 {
	if m != nil && m.BabyId != nil {
		return *m.BabyId
	}
	return 0
}

type SCBabyLearnUplevel struct {
	IsAuto           *bool  `protobuf:"varint,1,req,name=isAuto" json:"isAuto,omitempty"`
	ItemId           *int32 `protobuf:"varint,2,req,name=itemId" json:"itemId,omitempty"`
	Num              *int32 `protobuf:"varint,3,req,name=num" json:"num,omitempty"`
	BabyId           *int64 `protobuf:"varint,4,req,name=babyId" json:"babyId,omitempty"`
	LearnLevel       *int32 `protobuf:"varint,5,req,name=learnLevel" json:"learnLevel,omitempty"`
	LearnExp         *int32 `protobuf:"varint,6,req,name=learnExp" json:"learnExp,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCBabyLearnUplevel) Reset()                    { *m = SCBabyLearnUplevel{} }
func (m *SCBabyLearnUplevel) String() string            { return proto.CompactTextString(m) }
func (*SCBabyLearnUplevel) ProtoMessage()               {}
func (*SCBabyLearnUplevel) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{27} }

func (m *SCBabyLearnUplevel) GetIsAuto() bool {
	if m != nil && m.IsAuto != nil {
		return *m.IsAuto
	}
	return false
}

func (m *SCBabyLearnUplevel) GetItemId() int32 {
	if m != nil && m.ItemId != nil {
		return *m.ItemId
	}
	return 0
}

func (m *SCBabyLearnUplevel) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

func (m *SCBabyLearnUplevel) GetBabyId() int64 {
	if m != nil && m.BabyId != nil {
		return *m.BabyId
	}
	return 0
}

func (m *SCBabyLearnUplevel) GetLearnLevel() int32 {
	if m != nil && m.LearnLevel != nil {
		return *m.LearnLevel
	}
	return 0
}

func (m *SCBabyLearnUplevel) GetLearnExp() int32 {
	if m != nil && m.LearnExp != nil {
		return *m.LearnExp
	}
	return 0
}

type CSBabyZhuanShi struct {
	BabyId           *int64 `protobuf:"varint,1,req,name=babyId" json:"babyId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSBabyZhuanShi) Reset()                    { *m = CSBabyZhuanShi{} }
func (m *CSBabyZhuanShi) String() string            { return proto.CompactTextString(m) }
func (*CSBabyZhuanShi) ProtoMessage()               {}
func (*CSBabyZhuanShi) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{28} }

func (m *CSBabyZhuanShi) GetBabyId() int64 {
	if m != nil && m.BabyId != nil {
		return *m.BabyId
	}
	return 0
}

type SCBabyZhuanShi struct {
	BabyId           *int64      `protobuf:"varint,1,req,name=babyId" json:"babyId,omitempty"`
	DropInfo         []*DropInfo `protobuf:"bytes,2,rep,name=dropInfo" json:"dropInfo,omitempty"`
	BabyNum          *int32      `protobuf:"varint,3,req,name=babyNum" json:"babyNum,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *SCBabyZhuanShi) Reset()                    { *m = SCBabyZhuanShi{} }
func (m *SCBabyZhuanShi) String() string            { return proto.CompactTextString(m) }
func (*SCBabyZhuanShi) ProtoMessage()               {}
func (*SCBabyZhuanShi) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{29} }

func (m *SCBabyZhuanShi) GetBabyId() int64 {
	if m != nil && m.BabyId != nil {
		return *m.BabyId
	}
	return 0
}

func (m *SCBabyZhuanShi) GetDropInfo() []*DropInfo {
	if m != nil {
		return m.DropInfo
	}
	return nil
}

func (m *SCBabyZhuanShi) GetBabyNum() int32 {
	if m != nil && m.BabyNum != nil {
		return *m.BabyNum
	}
	return 0
}

type CSBabyEquipToy struct {
	Index            *int32 `protobuf:"varint,1,req,name=index" json:"index,omitempty"`
	SuitType         *int32 `protobuf:"varint,2,req,name=suitType" json:"suitType,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSBabyEquipToy) Reset()                    { *m = CSBabyEquipToy{} }
func (m *CSBabyEquipToy) String() string            { return proto.CompactTextString(m) }
func (*CSBabyEquipToy) ProtoMessage()               {}
func (*CSBabyEquipToy) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{30} }

func (m *CSBabyEquipToy) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *CSBabyEquipToy) GetSuitType() int32 {
	if m != nil && m.SuitType != nil {
		return *m.SuitType
	}
	return 0
}

type SCBabyEquipToy struct {
	Index            *int32 `protobuf:"varint,1,req,name=index" json:"index,omitempty"`
	SuitType         *int32 `protobuf:"varint,2,req,name=suitType" json:"suitType,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCBabyEquipToy) Reset()                    { *m = SCBabyEquipToy{} }
func (m *SCBabyEquipToy) String() string            { return proto.CompactTextString(m) }
func (*SCBabyEquipToy) ProtoMessage()               {}
func (*SCBabyEquipToy) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{31} }

func (m *SCBabyEquipToy) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *SCBabyEquipToy) GetSuitType() int32 {
	if m != nil && m.SuitType != nil {
		return *m.SuitType
	}
	return 0
}

type CSBabyToyUplevel struct {
	SuitType         *int32 `protobuf:"varint,1,req,name=suitType" json:"suitType,omitempty"`
	SlotId           *int32 `protobuf:"varint,2,req,name=slotId" json:"slotId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSBabyToyUplevel) Reset()                    { *m = CSBabyToyUplevel{} }
func (m *CSBabyToyUplevel) String() string            { return proto.CompactTextString(m) }
func (*CSBabyToyUplevel) ProtoMessage()               {}
func (*CSBabyToyUplevel) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{32} }

func (m *CSBabyToyUplevel) GetSuitType() int32 {
	if m != nil && m.SuitType != nil {
		return *m.SuitType
	}
	return 0
}

func (m *CSBabyToyUplevel) GetSlotId() int32 {
	if m != nil && m.SlotId != nil {
		return *m.SlotId
	}
	return 0
}

type SCBabyToyUplevel struct {
	Result           *int32 `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	Level            *int32 `protobuf:"varint,2,req,name=level" json:"level,omitempty"`
	SlotId           *int32 `protobuf:"varint,3,req,name=slotId" json:"slotId,omitempty"`
	SuitType         *int32 `protobuf:"varint,4,req,name=suitType" json:"suitType,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCBabyToyUplevel) Reset()                    { *m = SCBabyToyUplevel{} }
func (m *SCBabyToyUplevel) String() string            { return proto.CompactTextString(m) }
func (*SCBabyToyUplevel) ProtoMessage()               {}
func (*SCBabyToyUplevel) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{33} }

func (m *SCBabyToyUplevel) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *SCBabyToyUplevel) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *SCBabyToyUplevel) GetSlotId() int32 {
	if m != nil && m.SlotId != nil {
		return *m.SlotId
	}
	return 0
}

func (m *SCBabyToyUplevel) GetSuitType() int32 {
	if m != nil && m.SuitType != nil {
		return *m.SuitType
	}
	return 0
}

type SCBabyToySlotChanged struct {
	InfoList         []*ToySuitInfo `protobuf:"bytes,1,rep,name=infoList" json:"infoList,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *SCBabyToySlotChanged) Reset()                    { *m = SCBabyToySlotChanged{} }
func (m *SCBabyToySlotChanged) String() string            { return proto.CompactTextString(m) }
func (*SCBabyToySlotChanged) ProtoMessage()               {}
func (*SCBabyToySlotChanged) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{34} }

func (m *SCBabyToySlotChanged) GetInfoList() []*ToySuitInfo {
	if m != nil {
		return m.InfoList
	}
	return nil
}

type SCBabyPowerNotice struct {
	Power            *int64 `protobuf:"varint,1,req,name=power" json:"power,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCBabyPowerNotice) Reset()                    { *m = SCBabyPowerNotice{} }
func (m *SCBabyPowerNotice) String() string            { return proto.CompactTextString(m) }
func (*SCBabyPowerNotice) ProtoMessage()               {}
func (*SCBabyPowerNotice) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{35} }

func (m *SCBabyPowerNotice) GetPower() int64 {
	if m != nil && m.Power != nil {
		return *m.Power
	}
	return 0
}

func init() {
	proto.RegisterType((*DongFangInfo)(nil), "ui.DongFangInfo")
	proto.RegisterType((*TalentInfo)(nil), "ui.TalentInfo")
	proto.RegisterType((*BabyInfo)(nil), "ui.BabyInfo")
	proto.RegisterType((*ToySlotInfo)(nil), "ui.ToySlotInfo")
	proto.RegisterType((*ToySuitInfo)(nil), "ui.ToySuitInfo")
	proto.RegisterType((*CSBabyInfo)(nil), "ui.CSBabyInfo")
	proto.RegisterType((*SCBabyInfo)(nil), "ui.SCBabyInfo")
	proto.RegisterType((*CSBabyDongFang)(nil), "ui.CSBabyDongFang")
	proto.RegisterType((*SCBabyDongFang)(nil), "ui.SCBabyDongFang")
	proto.RegisterType((*CSBabyBornAccelerate)(nil), "ui.CSBabyBornAccelerate")
	proto.RegisterType((*SCBabyBornAccelerate)(nil), "ui.SCBabyBornAccelerate")
	proto.RegisterType((*CSBabyEatTonic)(nil), "ui.CSBabyEatTonic")
	proto.RegisterType((*SCBabyEatTonic)(nil), "ui.SCBabyEatTonic")
	proto.RegisterType((*CSBabyBornChaoSheng)(nil), "ui.CSBabyBornChaoSheng")
	proto.RegisterType((*SCBabyBornChaoSheng)(nil), "ui.SCBabyBornChaoSheng")
	proto.RegisterType((*SCBabyBornNotice)(nil), "ui.SCBabyBornNotice")
	proto.RegisterType((*SCBabyBornSpouseNotice)(nil), "ui.SCBabyBornSpouseNotice")
	proto.RegisterType((*SCBabyBornMessageNotice)(nil), "ui.SCBabyBornMessageNotice")
	proto.RegisterType((*CSBabyChangeName)(nil), "ui.CSBabyChangeName")
	proto.RegisterType((*SCBabyChangeName)(nil), "ui.SCBabyChangeName")
	proto.RegisterType((*CSBabyActivateSkill)(nil), "ui.CSBabyActivateSkill")
	proto.RegisterType((*SCBabyActivateSkill)(nil), "ui.SCBabyActivateSkill")
	proto.RegisterType((*CSBabyLockSkill)(nil), "ui.CSBabyLockSkill")
	proto.RegisterType((*SCBabyLockSkill)(nil), "ui.SCBabyLockSkill")
	proto.RegisterType((*CSBabyRefreshSkill)(nil), "ui.CSBabyRefreshSkill")
	proto.RegisterType((*SCBabyRefreshSkill)(nil), "ui.SCBabyRefreshSkill")
	proto.RegisterType((*CSBabyLearnUplevel)(nil), "ui.CSBabyLearnUplevel")
	proto.RegisterType((*SCBabyLearnUplevel)(nil), "ui.SCBabyLearnUplevel")
	proto.RegisterType((*CSBabyZhuanShi)(nil), "ui.CSBabyZhuanShi")
	proto.RegisterType((*SCBabyZhuanShi)(nil), "ui.SCBabyZhuanShi")
	proto.RegisterType((*CSBabyEquipToy)(nil), "ui.CSBabyEquipToy")
	proto.RegisterType((*SCBabyEquipToy)(nil), "ui.SCBabyEquipToy")
	proto.RegisterType((*CSBabyToyUplevel)(nil), "ui.CSBabyToyUplevel")
	proto.RegisterType((*SCBabyToyUplevel)(nil), "ui.SCBabyToyUplevel")
	proto.RegisterType((*SCBabyToySlotChanged)(nil), "ui.SCBabyToySlotChanged")
	proto.RegisterType((*SCBabyPowerNotice)(nil), "ui.SCBabyPowerNotice")
}

func init() { proto.RegisterFile("baby.proto", fileDescriptor9) }

var fileDescriptor9 = []byte{
	// 906 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x4b, 0x6f, 0x23, 0x45,
	0x10, 0x96, 0x67, 0xe2, 0xd8, 0x2e, 0x3b, 0x1e, 0x67, 0xc8, 0x2e, 0xa3, 0x3d, 0x20, 0xd3, 0x3c,
	0x64, 0x0e, 0x44, 0x22, 0x70, 0x41, 0x42, 0x42, 0x49, 0x76, 0x51, 0x2c, 0x85, 0xd5, 0x2e, 0xf6,
	0x5e, 0x90, 0x38, 0xb4, 0x67, 0x3a, 0x76, 0x2b, 0xe3, 0xee, 0xd9, 0xe9, 0x9e, 0x24, 0xbe, 0xf2,
	0x57, 0xf9, 0x23, 0xa8, 0xfa, 0xe1, 0xb1, 0x1d, 0x13, 0x05, 0xc1, 0xb1, 0xab, 0xeb, 0xf1, 0x55,
	0x75, 0x7f, 0x5f, 0x01, 0xcc, 0xe8, 0x6c, 0x75, 0x5a, 0x94, 0x52, 0xcb, 0x38, 0xa8, 0xf8, 0x2b,
	0xc8, 0x4a, 0x59, 0xd8, 0xf3, 0xab, 0xe3, 0x92, 0xdd, 0x17, 0xa5, 0x2c, 0x58, 0xa9, 0x9d, 0x0b,
	0xf9, 0x03, 0x7a, 0xaf, 0xa5, 0x98, 0xff, 0x42, 0xc5, 0x7c, 0x2c, 0x6e, 0x64, 0x7c, 0x02, 0xbd,
	0xa2, 0x64, 0x73, 0x41, 0x85, 0x9e, 0xf2, 0x25, 0x4b, 0x1a, 0xc3, 0xc6, 0x28, 0x8c, 0x07, 0xd0,
	0xd6, 0x52, 0xf0, 0xf4, 0x5d, 0x29, 0x93, 0x60, 0xd8, 0x18, 0x35, 0xe3, 0x08, 0x5a, 0x58, 0xe8,
	0x6d, 0xb5, 0x4c, 0x42, 0x63, 0x38, 0x81, 0x5e, 0xba, 0xa0, 0x52, 0x2d, 0x98, 0x98, 0xa3, 0xf5,
	0x00, 0xad, 0xe4, 0x5b, 0x80, 0x29, 0xcd, 0x99, 0xd0, 0x26, 0x79, 0x04, 0x2d, 0x75, 0xcb, 0xf3,
	0x7c, 0x9c, 0x25, 0x8d, 0x61, 0x30, 0x6a, 0xc6, 0x7d, 0x38, 0x54, 0x9a, 0xea, 0x4a, 0x25, 0x01,
	0x9e, 0xc9, 0x5f, 0x0d, 0x68, 0x5f, 0xd0, 0xd9, 0xca, 0x78, 0xbf, 0x80, 0x23, 0x9a, 0x6a, 0x7e,
	0x47, 0x35, 0x43, 0x28, 0xca, 0xc5, 0x10, 0x00, 0x6d, 0x52, 0x5e, 0x73, 0xa5, 0x93, 0x60, 0x18,
	0x8e, 0xba, 0x67, 0xfd, 0xd3, 0x8a, 0x9f, 0x6e, 0x14, 0x1a, 0x40, 0xdb, 0xa0, 0xa3, 0x4b, 0x96,
	0x84, 0xc3, 0x60, 0xd4, 0x89, 0xbb, 0x10, 0x2a, 0xf6, 0x90, 0x1c, 0xf8, 0xb2, 0x19, 0x15, 0x33,
	0xc6, 0x93, 0xa6, 0x39, 0x47, 0xd0, 0xfa, 0x58, 0xd1, 0x9c, 0xeb, 0x55, 0x72, 0x68, 0x0c, 0x31,
	0x40, 0xce, 0x68, 0x29, 0xae, 0xd9, 0x1d, 0xcb, 0x93, 0x96, 0x0f, 0xc2, 0x9c, 0xe3, 0x2c, 0x69,
	0x0f, 0x03, 0x3b, 0x93, 0x5c, 0xa6, 0xb7, 0x53, 0xbe, 0x54, 0x49, 0xc7, 0x78, 0x9c, 0x40, 0xaf,
	0x64, 0x37, 0x25, 0x53, 0x0b, 0x8b, 0x17, 0x8c, 0x15, 0xfd, 0x30, 0xd7, 0x9b, 0x87, 0x22, 0xe9,
	0x9a, 0x2e, 0x7f, 0x82, 0xee, 0x54, 0xae, 0x26, 0xb9, 0xb4, 0x60, 0x8f, 0xa0, 0x99, 0x9b, 0x3a,
	0xf5, 0x4c, 0xf0, 0x2a, 0xb3, 0x33, 0xc1, 0x33, 0xd7, 0x6c, 0x39, 0xce, 0x4c, 0x27, 0x4d, 0x72,
	0x61, 0xa3, 0x2b, 0xbe, 0x6e, 0x55, 0x55, 0x5c, 0x4f, 0x57, 0x05, 0x73, 0x09, 0x3e, 0x87, 0xb6,
	0x72, 0xb9, 0xdd, 0x78, 0x22, 0x33, 0x9e, 0xba, 0x24, 0xe9, 0x01, 0x5c, 0x4e, 0xfc, 0xa0, 0xc9,
	0x9f, 0x0d, 0x80, 0xc9, 0xe5, 0x7a, 0xee, 0x5f, 0x43, 0x2f, 0x93, 0x62, 0x7e, 0xe3, 0xbe, 0x84,
	0xc9, 0xda, 0x3d, 0x1b, 0x60, 0x8e, 0xad, 0xaf, 0x42, 0xa0, 0x37, 0x73, 0x31, 0x1b, 0x4f, 0xd1,
	0x43, 0xbf, 0x75, 0xae, 0x11, 0x44, 0xba, 0x06, 0x6b, 0xdc, 0xc2, 0x6d, 0x48, 0xee, 0x8a, 0x7c,
	0x01, 0x7d, 0x0b, 0xc9, 0xd7, 0x88, 0x8f, 0xa1, 0xc3, 0xd5, 0x07, 0xc5, 0xc6, 0x9a, 0x2d, 0x0d,
	0x88, 0x36, 0x51, 0xd0, 0xb7, 0x40, 0x9f, 0x70, 0x32, 0x03, 0x53, 0x17, 0xb2, 0x14, 0x66, 0x80,
	0xed, 0xf8, 0x33, 0x68, 0x23, 0x07, 0x4c, 0x2f, 0x61, 0x8d, 0xf1, 0xb5, 0xb3, 0xe1, 0xbd, 0xef,
	0xc3, 0xfc, 0xda, 0x9d, 0x1e, 0xc8, 0x4b, 0x38, 0xb1, 0xc8, 0x30, 0xe7, 0x79, 0x9a, 0xb2, 0x9c,
	0x95, 0x54, 0x33, 0xb4, 0x5b, 0x30, 0x3b, 0xf6, 0x81, 0xef, 0xe4, 0x0d, 0xd5, 0x53, 0x64, 0x0d,
	0x19, 0x7a, 0xd8, 0xde, 0x82, 0x18, 0x69, 0x96, 0x21, 0x9d, 0xcc, 0x9b, 0x91, 0x17, 0xf0, 0x49,
	0x5d, 0xe3, 0x72, 0x41, 0xe5, 0x04, 0x79, 0x84, 0xe6, 0xba, 0x44, 0x6d, 0x3e, 0x83, 0x41, 0x6d,
	0x7e, 0x2b, 0x35, 0x4f, 0xd9, 0x56, 0x17, 0xf6, 0xc5, 0xb6, 0xbb, 0xf8, 0x06, 0x5e, 0xd6, 0x31,
	0x93, 0x42, 0x56, 0x8a, 0xb9, 0xc8, 0x08, 0x5a, 0x6c, 0x49, 0xb9, 0x67, 0x65, 0x48, 0x7e, 0x86,
	0x4f, 0x6b, 0xd7, 0x5f, 0x99, 0x52, 0x74, 0xee, 0x7d, 0x91, 0x58, 0xb2, 0x14, 0x4e, 0x1a, 0x90,
	0x06, 0x31, 0x80, 0x30, 0x77, 0xc6, 0x16, 0x98, 0x04, 0xdf, 0xc3, 0xc0, 0x76, 0x73, 0xb9, 0xa0,
	0x62, 0xce, 0x90, 0x86, 0x1b, 0xf4, 0xb1, 0x71, 0x11, 0xb4, 0x04, 0xbb, 0x37, 0x0c, 0xc5, 0xa0,
	0x0e, 0x06, 0xd9, 0xaa, 0xff, 0x26, 0xe8, 0x2b, 0x3f, 0xb7, 0x73, 0xa7, 0x14, 0x13, 0xd4, 0x97,
	0xdd, 0x38, 0x32, 0xf6, 0x73, 0x7c, 0xd2, 0xed, 0x39, 0xd2, 0x42, 0xae, 0x20, 0xb2, 0x15, 0xaf,
	0x65, 0x7a, 0xbb, 0x3f, 0x4d, 0x0c, 0x60, 0x65, 0x4e, 0x64, 0xec, 0xc1, 0xb1, 0xf8, 0x18, 0x3a,
	0xa8, 0xbb, 0x54, 0x73, 0x29, 0x1c, 0x91, 0xaf, 0x20, 0xb2, 0xa0, 0xfe, 0x73, 0xa6, 0x2f, 0x21,
	0xb6, 0x98, 0x7e, 0xb3, 0xf2, 0xb3, 0x7f, 0x08, 0x57, 0x10, 0xdb, 0x7a, 0x4f, 0x79, 0x3d, 0x6b,
	0x06, 0xef, 0x7d, 0xbd, 0x6b, 0x14, 0xb6, 0x0f, 0x85, 0x91, 0x2f, 0xcb, 0xbb, 0xf3, 0x4a, 0xcb,
	0x0d, 0x1e, 0x5a, 0xe1, 0xb2, 0xc0, 0xbb, 0x10, 0x0a, 0xb3, 0x2e, 0xb6, 0xd5, 0xf4, 0xc0, 0x80,
	0xbb, 0xf7, 0xe0, 0xfe, 0xb7, 0x94, 0x3b, 0x22, 0xde, 0x7c, 0x24, 0xc6, 0x46, 0xea, 0x91, 0x9b,
	0xb6, 0x97, 0xdf, 0x17, 0x15, 0x15, 0x93, 0x05, 0x7f, 0x34, 0xb7, 0xf7, 0x9e, 0xbd, 0xff, 0xe4,
	0xb1, 0xa5, 0x30, 0xc1, 0x1e, 0x85, 0xd9, 0x5a, 0x96, 0x58, 0xf4, 0xbb, 0xb5, 0x44, 0x7c, 0xac,
	0x78, 0x31, 0x95, 0x2b, 0x5c, 0x02, 0xdc, 0x3c, 0x72, 0xc3, 0xe3, 0x5c, 0xab, 0x7a, 0xe0, 0x43,
	0x9c, 0x86, 0x3c, 0x3b, 0xe4, 0x07, 0x4f, 0xc3, 0xa9, 0x5c, 0xf9, 0x89, 0x3e, 0x5e, 0x17, 0x3b,
	0xfb, 0x86, 0x4c, 0x3c, 0x0f, 0x37, 0xa2, 0xfa, 0x70, 0x58, 0x32, 0x55, 0xe5, 0xda, 0xc5, 0xac,
	0x57, 0x56, 0xb0, 0x93, 0x22, 0x7c, 0x04, 0xc5, 0x6c, 0x5c, 0xf2, 0xa3, 0xd7, 0x4a, 0xb7, 0x85,
	0x2c, 0xc7, 0x33, 0xdc, 0x55, 0xdc, 0x2f, 0x86, 0xc6, 0xfe, 0xc5, 0x40, 0xe0, 0xd8, 0x86, 0xbe,
	0x93, 0xf7, 0xac, 0x74, 0x3a, 0x74, 0x04, 0xcd, 0x02, 0x8f, 0xf6, 0x01, 0xfe, 0x0e, 0x00, 0x00,
	0xff, 0xff, 0x17, 0x08, 0x91, 0xff, 0xf5, 0x08, 0x00, 0x00,
}
