// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chuangshi.proto

package ui

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CSChuangShiYuGao struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSChuangShiYuGao) Reset()                    { *m = CSChuangShiYuGao{} }
func (m *CSChuangShiYuGao) String() string            { return proto.CompactTextString(m) }
func (*CSChuangShiYuGao) ProtoMessage()               {}
func (*CSChuangShiYuGao) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{0} }

type SCChuangShiYuGao struct {
	IsJoin           *int32 `protobuf:"varint,1,req,name=isJoin" json:"isJoin,omitempty"`
	PeopleNum        *int64 `protobuf:"varint,2,req,name=peopleNum" json:"peopleNum,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCChuangShiYuGao) Reset()                    { *m = SCChuangShiYuGao{} }
func (m *SCChuangShiYuGao) String() string            { return proto.CompactTextString(m) }
func (*SCChuangShiYuGao) ProtoMessage()               {}
func (*SCChuangShiYuGao) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{1} }

func (m *SCChuangShiYuGao) GetIsJoin() int32 {
	if m != nil && m.IsJoin != nil {
		return *m.IsJoin
	}
	return 0
}

func (m *SCChuangShiYuGao) GetPeopleNum() int64 {
	if m != nil && m.PeopleNum != nil {
		return *m.PeopleNum
	}
	return 0
}

type CSBaoMingChuangShi struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSBaoMingChuangShi) Reset()                    { *m = CSBaoMingChuangShi{} }
func (m *CSBaoMingChuangShi) String() string            { return proto.CompactTextString(m) }
func (*CSBaoMingChuangShi) ProtoMessage()               {}
func (*CSBaoMingChuangShi) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{2} }

type SCBaoMingChuangShi struct {
	DropInfo         []*DropInfo `protobuf:"bytes,1,rep,name=dropInfo" json:"dropInfo,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *SCBaoMingChuangShi) Reset()                    { *m = SCBaoMingChuangShi{} }
func (m *SCBaoMingChuangShi) String() string            { return proto.CompactTextString(m) }
func (*SCBaoMingChuangShi) ProtoMessage()               {}
func (*SCBaoMingChuangShi) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{3} }

func (m *SCBaoMingChuangShi) GetDropInfo() []*DropInfo {
	if m != nil {
		return m.DropInfo
	}
	return nil
}

type PlayerGuanZhiInfo struct {
	Level            *int32 `protobuf:"varint,1,req,name=level" json:"level,omitempty"`
	WeiWang          *int32 `protobuf:"varint,2,req,name=weiWang" json:"weiWang,omitempty"`
	ReceiveRewLevel  *int32 `protobuf:"varint,3,req,name=receiveRewLevel" json:"receiveRewLevel,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerGuanZhiInfo) Reset()                    { *m = PlayerGuanZhiInfo{} }
func (m *PlayerGuanZhiInfo) String() string            { return proto.CompactTextString(m) }
func (*PlayerGuanZhiInfo) ProtoMessage()               {}
func (*PlayerGuanZhiInfo) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{4} }

func (m *PlayerGuanZhiInfo) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *PlayerGuanZhiInfo) GetWeiWang() int32 {
	if m != nil && m.WeiWang != nil {
		return *m.WeiWang
	}
	return 0
}

func (m *PlayerGuanZhiInfo) GetReceiveRewLevel() int32 {
	if m != nil && m.ReceiveRewLevel != nil {
		return *m.ReceiveRewLevel
	}
	return 0
}

type PlayerChuangShiInfo struct {
	Pos              *int32             `protobuf:"varint,1,req,name=pos" json:"pos,omitempty"`
	Jifen            *int64             `protobuf:"varint,2,req,name=jifen" json:"jifen,omitempty"`
	Diamonds         *int64             `protobuf:"varint,3,req,name=diamonds" json:"diamonds,omitempty"`
	WeiWang          *int64             `protobuf:"varint,4,req,name=weiWang" json:"weiWang,omitempty"`
	CampType         *int32             `protobuf:"varint,5,req,name=campType" json:"campType,omitempty"`
	GuanZhiInfo      *PlayerGuanZhiInfo `protobuf:"bytes,6,req,name=guanZhiInfo" json:"guanZhiInfo,omitempty"`
	SignStatus       *int32             `protobuf:"varint,7,req,name=signStatus" json:"signStatus,omitempty"`
	VoteStatus       *int32             `protobuf:"varint,8,req,name=voteStatus" json:"voteStatus,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *PlayerChuangShiInfo) Reset()                    { *m = PlayerChuangShiInfo{} }
func (m *PlayerChuangShiInfo) String() string            { return proto.CompactTextString(m) }
func (*PlayerChuangShiInfo) ProtoMessage()               {}
func (*PlayerChuangShiInfo) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{5} }

func (m *PlayerChuangShiInfo) GetPos() int32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

func (m *PlayerChuangShiInfo) GetJifen() int64 {
	if m != nil && m.Jifen != nil {
		return *m.Jifen
	}
	return 0
}

func (m *PlayerChuangShiInfo) GetDiamonds() int64 {
	if m != nil && m.Diamonds != nil {
		return *m.Diamonds
	}
	return 0
}

func (m *PlayerChuangShiInfo) GetWeiWang() int64 {
	if m != nil && m.WeiWang != nil {
		return *m.WeiWang
	}
	return 0
}

func (m *PlayerChuangShiInfo) GetCampType() int32 {
	if m != nil && m.CampType != nil {
		return *m.CampType
	}
	return 0
}

func (m *PlayerChuangShiInfo) GetGuanZhiInfo() *PlayerGuanZhiInfo {
	if m != nil {
		return m.GuanZhiInfo
	}
	return nil
}

func (m *PlayerChuangShiInfo) GetSignStatus() int32 {
	if m != nil && m.SignStatus != nil {
		return *m.SignStatus
	}
	return 0
}

func (m *PlayerChuangShiInfo) GetVoteStatus() int32 {
	if m != nil && m.VoteStatus != nil {
		return *m.VoteStatus
	}
	return 0
}

type ChuangShiMemberInfo struct {
	Platform         *int32  `protobuf:"varint,1,req,name=platform" json:"platform,omitempty"`
	ServerId         *int32  `protobuf:"varint,2,req,name=serverId" json:"serverId,omitempty"`
	Name             *string `protobuf:"bytes,3,req,name=name" json:"name,omitempty"`
	Pos              *int32  `protobuf:"varint,4,req,name=pos" json:"pos,omitempty"`
	Force            *int64  `protobuf:"varint,5,req,name=force" json:"force,omitempty"`
	AllianceName     *string `protobuf:"bytes,6,req,name=allianceName" json:"allianceName,omitempty"`
	MemId            *int64  `protobuf:"varint,7,req,name=memId" json:"memId,omitempty"`
	AlPos            *int32  `protobuf:"varint,8,req,name=alPos" json:"alPos,omitempty"`
	AllianceId       *int64  `protobuf:"varint,9,req,name=allianceId" json:"allianceId,omitempty"`
	CampType         *int32  `protobuf:"varint,10,req,name=campType" json:"campType,omitempty"`
	Role             *int32  `protobuf:"varint,11,req,name=role" json:"role,omitempty"`
	Sex              *int32  `protobuf:"varint,12,req,name=sex" json:"sex,omitempty"`
	WingId           *int32  `protobuf:"varint,13,req,name=wingId" json:"wingId,omitempty"`
	WeaponId         *int32  `protobuf:"varint,14,req,name=weaponId" json:"weaponId,omitempty"`
	FashionId        *int32  `protobuf:"varint,15,req,name=fashionId" json:"fashionId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ChuangShiMemberInfo) Reset()                    { *m = ChuangShiMemberInfo{} }
func (m *ChuangShiMemberInfo) String() string            { return proto.CompactTextString(m) }
func (*ChuangShiMemberInfo) ProtoMessage()               {}
func (*ChuangShiMemberInfo) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{6} }

func (m *ChuangShiMemberInfo) GetPlatform() int32 {
	if m != nil && m.Platform != nil {
		return *m.Platform
	}
	return 0
}

func (m *ChuangShiMemberInfo) GetServerId() int32 {
	if m != nil && m.ServerId != nil {
		return *m.ServerId
	}
	return 0
}

func (m *ChuangShiMemberInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ChuangShiMemberInfo) GetPos() int32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

func (m *ChuangShiMemberInfo) GetForce() int64 {
	if m != nil && m.Force != nil {
		return *m.Force
	}
	return 0
}

func (m *ChuangShiMemberInfo) GetAllianceName() string {
	if m != nil && m.AllianceName != nil {
		return *m.AllianceName
	}
	return ""
}

func (m *ChuangShiMemberInfo) GetMemId() int64 {
	if m != nil && m.MemId != nil {
		return *m.MemId
	}
	return 0
}

func (m *ChuangShiMemberInfo) GetAlPos() int32 {
	if m != nil && m.AlPos != nil {
		return *m.AlPos
	}
	return 0
}

func (m *ChuangShiMemberInfo) GetAllianceId() int64 {
	if m != nil && m.AllianceId != nil {
		return *m.AllianceId
	}
	return 0
}

func (m *ChuangShiMemberInfo) GetCampType() int32 {
	if m != nil && m.CampType != nil {
		return *m.CampType
	}
	return 0
}

func (m *ChuangShiMemberInfo) GetRole() int32 {
	if m != nil && m.Role != nil {
		return *m.Role
	}
	return 0
}

func (m *ChuangShiMemberInfo) GetSex() int32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func (m *ChuangShiMemberInfo) GetWingId() int32 {
	if m != nil && m.WingId != nil {
		return *m.WingId
	}
	return 0
}

func (m *ChuangShiMemberInfo) GetWeaponId() int32 {
	if m != nil && m.WeaponId != nil {
		return *m.WeaponId
	}
	return 0
}

func (m *ChuangShiMemberInfo) GetFashionId() int32 {
	if m != nil && m.FashionId != nil {
		return *m.FashionId
	}
	return 0
}

type JianSheSkillInfo struct {
	Level            *int32 `protobuf:"varint,1,req,name=level" json:"level,omitempty"`
	ActivateTime     *int64 `protobuf:"varint,2,req,name=activateTime" json:"activateTime,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *JianSheSkillInfo) Reset()                    { *m = JianSheSkillInfo{} }
func (m *JianSheSkillInfo) String() string            { return proto.CompactTextString(m) }
func (*JianSheSkillInfo) ProtoMessage()               {}
func (*JianSheSkillInfo) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{7} }

func (m *JianSheSkillInfo) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *JianSheSkillInfo) GetActivateTime() int64 {
	if m != nil && m.ActivateTime != nil {
		return *m.ActivateTime
	}
	return 0
}

type ChuangShiJianSheInfo struct {
	Type             *int32              `protobuf:"varint,1,req,name=type" json:"type,omitempty"`
	Level            *int32              `protobuf:"varint,2,req,name=level" json:"level,omitempty"`
	Exp              *int32              `protobuf:"varint,3,req,name=exp" json:"exp,omitempty"`
	SkillList        []*JianSheSkillInfo `protobuf:"bytes,4,rep,name=skillList" json:"skillList,omitempty"`
	SkillLevelSet    *int32              `protobuf:"varint,5,opt,name=skillLevelSet" json:"skillLevelSet,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ChuangShiJianSheInfo) Reset()                    { *m = ChuangShiJianSheInfo{} }
func (m *ChuangShiJianSheInfo) String() string            { return proto.CompactTextString(m) }
func (*ChuangShiJianSheInfo) ProtoMessage()               {}
func (*ChuangShiJianSheInfo) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{8} }

func (m *ChuangShiJianSheInfo) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *ChuangShiJianSheInfo) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *ChuangShiJianSheInfo) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func (m *ChuangShiJianSheInfo) GetSkillList() []*JianSheSkillInfo {
	if m != nil {
		return m.SkillList
	}
	return nil
}

func (m *ChuangShiJianSheInfo) GetSkillLevelSet() int32 {
	if m != nil && m.SkillLevelSet != nil {
		return *m.SkillLevelSet
	}
	return 0
}

type ChuangShiCity struct {
	Camp             *int32                  `protobuf:"varint,1,req,name=camp" json:"camp,omitempty"`
	CityType         *int32                  `protobuf:"varint,2,req,name=cityType" json:"cityType,omitempty"`
	Index            *int32                  `protobuf:"varint,3,req,name=index" json:"index,omitempty"`
	KingMember       *ChuangShiMemberInfo    `protobuf:"bytes,4,opt,name=kingMember" json:"kingMember,omitempty"`
	OrignalCamp      *int32                  `protobuf:"varint,5,req,name=orignalCamp" json:"orignalCamp,omitempty"`
	CityId           *int64                  `protobuf:"varint,6,req,name=cityId" json:"cityId,omitempty"`
	JianSheList      []*ChuangShiJianSheInfo `protobuf:"bytes,7,rep,name=jianSheList" json:"jianSheList,omitempty"`
	Jifen            *int64                  `protobuf:"varint,8,req,name=jifen" json:"jifen,omitempty"`
	Diamonds         *int64                  `protobuf:"varint,9,req,name=diamonds" json:"diamonds,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *ChuangShiCity) Reset()                    { *m = ChuangShiCity{} }
func (m *ChuangShiCity) String() string            { return proto.CompactTextString(m) }
func (*ChuangShiCity) ProtoMessage()               {}
func (*ChuangShiCity) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{9} }

func (m *ChuangShiCity) GetCamp() int32 {
	if m != nil && m.Camp != nil {
		return *m.Camp
	}
	return 0
}

func (m *ChuangShiCity) GetCityType() int32 {
	if m != nil && m.CityType != nil {
		return *m.CityType
	}
	return 0
}

func (m *ChuangShiCity) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *ChuangShiCity) GetKingMember() *ChuangShiMemberInfo {
	if m != nil {
		return m.KingMember
	}
	return nil
}

func (m *ChuangShiCity) GetOrignalCamp() int32 {
	if m != nil && m.OrignalCamp != nil {
		return *m.OrignalCamp
	}
	return 0
}

func (m *ChuangShiCity) GetCityId() int64 {
	if m != nil && m.CityId != nil {
		return *m.CityId
	}
	return 0
}

func (m *ChuangShiCity) GetJianSheList() []*ChuangShiJianSheInfo {
	if m != nil {
		return m.JianSheList
	}
	return nil
}

func (m *ChuangShiCity) GetJifen() int64 {
	if m != nil && m.Jifen != nil {
		return *m.Jifen
	}
	return 0
}

func (m *ChuangShiCity) GetDiamonds() int64 {
	if m != nil && m.Diamonds != nil {
		return *m.Diamonds
	}
	return 0
}

type ChuangShiCamp struct {
	Camp             *int32                 `protobuf:"varint,1,req,name=camp" json:"camp,omitempty"`
	KingMember       *ChuangShiMemberInfo   `protobuf:"bytes,2,opt,name=kingMember" json:"kingMember,omitempty"`
	Power            *int64                 `protobuf:"varint,3,req,name=power" json:"power,omitempty"`
	CityList         []*ChuangShiCity       `protobuf:"bytes,4,rep,name=cityList" json:"cityList,omitempty"`
	MemList          []*ChuangShiMemberInfo `protobuf:"bytes,5,rep,name=memList" json:"memList,omitempty"`
	Jifen            *int64                 `protobuf:"varint,6,req,name=jifen" json:"jifen,omitempty"`
	Diamonds         *int64                 `protobuf:"varint,7,req,name=diamonds" json:"diamonds,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *ChuangShiCamp) Reset()                    { *m = ChuangShiCamp{} }
func (m *ChuangShiCamp) String() string            { return proto.CompactTextString(m) }
func (*ChuangShiCamp) ProtoMessage()               {}
func (*ChuangShiCamp) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{10} }

func (m *ChuangShiCamp) GetCamp() int32 {
	if m != nil && m.Camp != nil {
		return *m.Camp
	}
	return 0
}

func (m *ChuangShiCamp) GetKingMember() *ChuangShiMemberInfo {
	if m != nil {
		return m.KingMember
	}
	return nil
}

func (m *ChuangShiCamp) GetPower() int64 {
	if m != nil && m.Power != nil {
		return *m.Power
	}
	return 0
}

func (m *ChuangShiCamp) GetCityList() []*ChuangShiCity {
	if m != nil {
		return m.CityList
	}
	return nil
}

func (m *ChuangShiCamp) GetMemList() []*ChuangShiMemberInfo {
	if m != nil {
		return m.MemList
	}
	return nil
}

func (m *ChuangShiCamp) GetJifen() int64 {
	if m != nil && m.Jifen != nil {
		return *m.Jifen
	}
	return 0
}

func (m *ChuangShiCamp) GetDiamonds() int64 {
	if m != nil && m.Diamonds != nil {
		return *m.Diamonds
	}
	return 0
}

type CSChuangShiInfo struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSChuangShiInfo) Reset()                    { *m = CSChuangShiInfo{} }
func (m *CSChuangShiInfo) String() string            { return proto.CompactTextString(m) }
func (*CSChuangShiInfo) ProtoMessage()               {}
func (*CSChuangShiInfo) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{11} }

type SCChuangShiInfo struct {
	CampList         []*ChuangShiCamp     `protobuf:"bytes,1,rep,name=campList" json:"campList,omitempty"`
	PlayerInfo       *PlayerChuangShiInfo `protobuf:"bytes,2,req,name=playerInfo" json:"playerInfo,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *SCChuangShiInfo) Reset()                    { *m = SCChuangShiInfo{} }
func (m *SCChuangShiInfo) String() string            { return proto.CompactTextString(m) }
func (*SCChuangShiInfo) ProtoMessage()               {}
func (*SCChuangShiInfo) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{12} }

func (m *SCChuangShiInfo) GetCampList() []*ChuangShiCamp {
	if m != nil {
		return m.CampList
	}
	return nil
}

func (m *SCChuangShiInfo) GetPlayerInfo() *PlayerChuangShiInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

type SCChuangShiPlayerInfoNotice struct {
	PlayerInfo       *PlayerChuangShiInfo `protobuf:"bytes,1,req,name=playerInfo" json:"playerInfo,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *SCChuangShiPlayerInfoNotice) Reset()                    { *m = SCChuangShiPlayerInfoNotice{} }
func (m *SCChuangShiPlayerInfoNotice) String() string            { return proto.CompactTextString(m) }
func (*SCChuangShiPlayerInfoNotice) ProtoMessage()               {}
func (*SCChuangShiPlayerInfoNotice) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{13} }

func (m *SCChuangShiPlayerInfoNotice) GetPlayerInfo() *PlayerChuangShiInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

type CSChuangShiJoinCamp struct {
	Camp             *int32 `protobuf:"varint,1,req,name=camp" json:"camp,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSChuangShiJoinCamp) Reset()                    { *m = CSChuangShiJoinCamp{} }
func (m *CSChuangShiJoinCamp) String() string            { return proto.CompactTextString(m) }
func (*CSChuangShiJoinCamp) ProtoMessage()               {}
func (*CSChuangShiJoinCamp) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{14} }

func (m *CSChuangShiJoinCamp) GetCamp() int32 {
	if m != nil && m.Camp != nil {
		return *m.Camp
	}
	return 0
}

type SCChuangShiJoinCamp struct {
	Camp             *int32 `protobuf:"varint,1,req,name=camp" json:"camp,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCChuangShiJoinCamp) Reset()                    { *m = SCChuangShiJoinCamp{} }
func (m *SCChuangShiJoinCamp) String() string            { return proto.CompactTextString(m) }
func (*SCChuangShiJoinCamp) ProtoMessage()               {}
func (*SCChuangShiJoinCamp) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{15} }

func (m *SCChuangShiJoinCamp) GetCamp() int32 {
	if m != nil && m.Camp != nil {
		return *m.Camp
	}
	return 0
}

type CSChuangShiShenWangBaoMingList struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSChuangShiShenWangBaoMingList) Reset()         { *m = CSChuangShiShenWangBaoMingList{} }
func (m *CSChuangShiShenWangBaoMingList) String() string { return proto.CompactTextString(m) }
func (*CSChuangShiShenWangBaoMingList) ProtoMessage()    {}
func (*CSChuangShiShenWangBaoMingList) Descriptor() ([]byte, []int) {
	return fileDescriptor18, []int{16}
}

type SCChuangShiShengWangBaoMingList struct {
	MemberInfoList   []*ChuangShiMemberInfo `protobuf:"bytes,1,rep,name=memberInfoList" json:"memberInfoList,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *SCChuangShiShengWangBaoMingList) Reset()         { *m = SCChuangShiShengWangBaoMingList{} }
func (m *SCChuangShiShengWangBaoMingList) String() string { return proto.CompactTextString(m) }
func (*SCChuangShiShengWangBaoMingList) ProtoMessage()    {}
func (*SCChuangShiShengWangBaoMingList) Descriptor() ([]byte, []int) {
	return fileDescriptor18, []int{17}
}

func (m *SCChuangShiShengWangBaoMingList) GetMemberInfoList() []*ChuangShiMemberInfo {
	if m != nil {
		return m.MemberInfoList
	}
	return nil
}

type CSChuangShiShenWangBaoMing struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSChuangShiShenWangBaoMing) Reset()                    { *m = CSChuangShiShenWangBaoMing{} }
func (m *CSChuangShiShenWangBaoMing) String() string            { return proto.CompactTextString(m) }
func (*CSChuangShiShenWangBaoMing) ProtoMessage()               {}
func (*CSChuangShiShenWangBaoMing) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{18} }

type SCChuangShiShenWangBaoMing struct {
	Status           *int32 `protobuf:"varint,1,req,name=status" json:"status,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCChuangShiShenWangBaoMing) Reset()                    { *m = SCChuangShiShenWangBaoMing{} }
func (m *SCChuangShiShenWangBaoMing) String() string            { return proto.CompactTextString(m) }
func (*SCChuangShiShenWangBaoMing) ProtoMessage()               {}
func (*SCChuangShiShenWangBaoMing) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{19} }

func (m *SCChuangShiShenWangBaoMing) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

type ChuangShiTouPiaoMemberInfo struct {
	MemberInfo       *ChuangShiMemberInfo `protobuf:"bytes,1,req,name=memberInfo" json:"memberInfo,omitempty"`
	TicketNum        *int32               `protobuf:"varint,2,req,name=ticketNum" json:"ticketNum,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *ChuangShiTouPiaoMemberInfo) Reset()                    { *m = ChuangShiTouPiaoMemberInfo{} }
func (m *ChuangShiTouPiaoMemberInfo) String() string            { return proto.CompactTextString(m) }
func (*ChuangShiTouPiaoMemberInfo) ProtoMessage()               {}
func (*ChuangShiTouPiaoMemberInfo) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{20} }

func (m *ChuangShiTouPiaoMemberInfo) GetMemberInfo() *ChuangShiMemberInfo {
	if m != nil {
		return m.MemberInfo
	}
	return nil
}

func (m *ChuangShiTouPiaoMemberInfo) GetTicketNum() int32 {
	if m != nil && m.TicketNum != nil {
		return *m.TicketNum
	}
	return 0
}

type CSChuangShiShenWangTouPiaoList struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSChuangShiShenWangTouPiaoList) Reset()         { *m = CSChuangShiShenWangTouPiaoList{} }
func (m *CSChuangShiShenWangTouPiaoList) String() string { return proto.CompactTextString(m) }
func (*CSChuangShiShenWangTouPiaoList) ProtoMessage()    {}
func (*CSChuangShiShenWangTouPiaoList) Descriptor() ([]byte, []int) {
	return fileDescriptor18, []int{21}
}

type SCChuangShiShengWangTouPiaoList struct {
	MemberInfoList   []*ChuangShiTouPiaoMemberInfo `protobuf:"bytes,1,rep,name=memberInfoList" json:"memberInfoList,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *SCChuangShiShengWangTouPiaoList) Reset()         { *m = SCChuangShiShengWangTouPiaoList{} }
func (m *SCChuangShiShengWangTouPiaoList) String() string { return proto.CompactTextString(m) }
func (*SCChuangShiShengWangTouPiaoList) ProtoMessage()    {}
func (*SCChuangShiShengWangTouPiaoList) Descriptor() ([]byte, []int) {
	return fileDescriptor18, []int{22}
}

func (m *SCChuangShiShengWangTouPiaoList) GetMemberInfoList() []*ChuangShiTouPiaoMemberInfo {
	if m != nil {
		return m.MemberInfoList
	}
	return nil
}

type CSChuangShiShengWangTouPiao struct {
	SupportId        *int64 `protobuf:"varint,1,req,name=supportId" json:"supportId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSChuangShiShengWangTouPiao) Reset()                    { *m = CSChuangShiShengWangTouPiao{} }
func (m *CSChuangShiShengWangTouPiao) String() string            { return proto.CompactTextString(m) }
func (*CSChuangShiShengWangTouPiao) ProtoMessage()               {}
func (*CSChuangShiShengWangTouPiao) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{23} }

func (m *CSChuangShiShengWangTouPiao) GetSupportId() int64 {
	if m != nil && m.SupportId != nil {
		return *m.SupportId
	}
	return 0
}

type SCChuangShiShengWangTouPiao struct {
	SupportId        *int64 `protobuf:"varint,1,req,name=supportId" json:"supportId,omitempty"`
	Status           *int32 `protobuf:"varint,2,req,name=status" json:"status,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCChuangShiShengWangTouPiao) Reset()                    { *m = SCChuangShiShengWangTouPiao{} }
func (m *SCChuangShiShengWangTouPiao) String() string            { return proto.CompactTextString(m) }
func (*SCChuangShiShengWangTouPiao) ProtoMessage()               {}
func (*SCChuangShiShengWangTouPiao) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{24} }

func (m *SCChuangShiShengWangTouPiao) GetSupportId() int64 {
	if m != nil && m.SupportId != nil {
		return *m.SupportId
	}
	return 0
}

func (m *SCChuangShiShengWangTouPiao) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

type SCChuangShiShenWangBroadcast struct {
	MemInfo          *ChuangShiMemberInfo `protobuf:"bytes,1,req,name=memInfo" json:"memInfo,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *SCChuangShiShenWangBroadcast) Reset()                    { *m = SCChuangShiShenWangBroadcast{} }
func (m *SCChuangShiShenWangBroadcast) String() string            { return proto.CompactTextString(m) }
func (*SCChuangShiShenWangBroadcast) ProtoMessage()               {}
func (*SCChuangShiShenWangBroadcast) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{25} }

func (m *SCChuangShiShenWangBroadcast) GetMemInfo() *ChuangShiMemberInfo {
	if m != nil {
		return m.MemInfo
	}
	return nil
}

type CSChuangShiCityRenMing struct {
	CityId           *int64 `protobuf:"varint,1,req,name=cityId" json:"cityId,omitempty"`
	BeCommitId       *int64 `protobuf:"varint,2,req,name=beCommitId" json:"beCommitId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSChuangShiCityRenMing) Reset()                    { *m = CSChuangShiCityRenMing{} }
func (m *CSChuangShiCityRenMing) String() string            { return proto.CompactTextString(m) }
func (*CSChuangShiCityRenMing) ProtoMessage()               {}
func (*CSChuangShiCityRenMing) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{26} }

func (m *CSChuangShiCityRenMing) GetCityId() int64 {
	if m != nil && m.CityId != nil {
		return *m.CityId
	}
	return 0
}

func (m *CSChuangShiCityRenMing) GetBeCommitId() int64 {
	if m != nil && m.BeCommitId != nil {
		return *m.BeCommitId
	}
	return 0
}

type SCChuangShiCityRenMing struct {
	City             *ChuangShiCity `protobuf:"bytes,1,req,name=city" json:"city,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *SCChuangShiCityRenMing) Reset()                    { *m = SCChuangShiCityRenMing{} }
func (m *SCChuangShiCityRenMing) String() string            { return proto.CompactTextString(m) }
func (*SCChuangShiCityRenMing) ProtoMessage()               {}
func (*SCChuangShiCityRenMing) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{27} }

func (m *SCChuangShiCityRenMing) GetCity() *ChuangShiCity {
	if m != nil {
		return m.City
	}
	return nil
}

type CampPaySchedule struct {
	CityId           *int64 `protobuf:"varint,1,req,name=cityId" json:"cityId,omitempty"`
	Ratio            *int32 `protobuf:"varint,2,req,name=ratio" json:"ratio,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CampPaySchedule) Reset()                    { *m = CampPaySchedule{} }
func (m *CampPaySchedule) String() string            { return proto.CompactTextString(m) }
func (*CampPaySchedule) ProtoMessage()               {}
func (*CampPaySchedule) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{28} }

func (m *CampPaySchedule) GetCityId() int64 {
	if m != nil && m.CityId != nil {
		return *m.CityId
	}
	return 0
}

func (m *CampPaySchedule) GetRatio() int32 {
	if m != nil && m.Ratio != nil {
		return *m.Ratio
	}
	return 0
}

type CSChuangShiCampPaySchedule struct {
	ScheduleList     []*CampPaySchedule `protobuf:"bytes,1,rep,name=scheduleList" json:"scheduleList,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *CSChuangShiCampPaySchedule) Reset()                    { *m = CSChuangShiCampPaySchedule{} }
func (m *CSChuangShiCampPaySchedule) String() string            { return proto.CompactTextString(m) }
func (*CSChuangShiCampPaySchedule) ProtoMessage()               {}
func (*CSChuangShiCampPaySchedule) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{29} }

func (m *CSChuangShiCampPaySchedule) GetScheduleList() []*CampPaySchedule {
	if m != nil {
		return m.ScheduleList
	}
	return nil
}

type SCChuangShiCampPaySchedule struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCChuangShiCampPaySchedule) Reset()                    { *m = SCChuangShiCampPaySchedule{} }
func (m *SCChuangShiCampPaySchedule) String() string            { return proto.CompactTextString(m) }
func (*SCChuangShiCampPaySchedule) ProtoMessage()               {}
func (*SCChuangShiCampPaySchedule) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{30} }

type CityPaySchedule struct {
	AlPos            *int32 `protobuf:"varint,1,req,name=alPos" json:"alPos,omitempty"`
	Ratio            *int32 `protobuf:"varint,2,req,name=ratio" json:"ratio,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CityPaySchedule) Reset()                    { *m = CityPaySchedule{} }
func (m *CityPaySchedule) String() string            { return proto.CompactTextString(m) }
func (*CityPaySchedule) ProtoMessage()               {}
func (*CityPaySchedule) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{31} }

func (m *CityPaySchedule) GetAlPos() int32 {
	if m != nil && m.AlPos != nil {
		return *m.AlPos
	}
	return 0
}

func (m *CityPaySchedule) GetRatio() int32 {
	if m != nil && m.Ratio != nil {
		return *m.Ratio
	}
	return 0
}

type CSChuangShiCityPaySchedule struct {
	ScheduleList     []*CityPaySchedule `protobuf:"bytes,1,rep,name=scheduleList" json:"scheduleList,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *CSChuangShiCityPaySchedule) Reset()                    { *m = CSChuangShiCityPaySchedule{} }
func (m *CSChuangShiCityPaySchedule) String() string            { return proto.CompactTextString(m) }
func (*CSChuangShiCityPaySchedule) ProtoMessage()               {}
func (*CSChuangShiCityPaySchedule) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{32} }

func (m *CSChuangShiCityPaySchedule) GetScheduleList() []*CityPaySchedule {
	if m != nil {
		return m.ScheduleList
	}
	return nil
}

type SCChuangShiCityPaySchedule struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCChuangShiCityPaySchedule) Reset()                    { *m = SCChuangShiCityPaySchedule{} }
func (m *SCChuangShiCityPaySchedule) String() string            { return proto.CompactTextString(m) }
func (*SCChuangShiCityPaySchedule) ProtoMessage()               {}
func (*SCChuangShiCityPaySchedule) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{33} }

type CSChuangShiMyPayReceive struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSChuangShiMyPayReceive) Reset()                    { *m = CSChuangShiMyPayReceive{} }
func (m *CSChuangShiMyPayReceive) String() string            { return proto.CompactTextString(m) }
func (*CSChuangShiMyPayReceive) ProtoMessage()               {}
func (*CSChuangShiMyPayReceive) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{34} }

type SCChuangShiMyPayReceive struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCChuangShiMyPayReceive) Reset()                    { *m = SCChuangShiMyPayReceive{} }
func (m *SCChuangShiMyPayReceive) String() string            { return proto.CompactTextString(m) }
func (*SCChuangShiMyPayReceive) ProtoMessage()               {}
func (*SCChuangShiMyPayReceive) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{35} }

type CSChuangShiCampPayReceive struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSChuangShiCampPayReceive) Reset()                    { *m = CSChuangShiCampPayReceive{} }
func (m *CSChuangShiCampPayReceive) String() string            { return proto.CompactTextString(m) }
func (*CSChuangShiCampPayReceive) ProtoMessage()               {}
func (*CSChuangShiCampPayReceive) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{36} }

type SCChuangShiCampPayReceive struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCChuangShiCampPayReceive) Reset()                    { *m = SCChuangShiCampPayReceive{} }
func (m *SCChuangShiCampPayReceive) String() string            { return proto.CompactTextString(m) }
func (*SCChuangShiCampPayReceive) ProtoMessage()               {}
func (*SCChuangShiCampPayReceive) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{37} }

type CSChuangShiCityJianShe struct {
	CityId           *int64 `protobuf:"varint,1,req,name=cityId" json:"cityId,omitempty"`
	BuildType        *int32 `protobuf:"varint,2,req,name=buildType" json:"buildType,omitempty"`
	Num              *int32 `protobuf:"varint,3,req,name=num" json:"num,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSChuangShiCityJianShe) Reset()                    { *m = CSChuangShiCityJianShe{} }
func (m *CSChuangShiCityJianShe) String() string            { return proto.CompactTextString(m) }
func (*CSChuangShiCityJianShe) ProtoMessage()               {}
func (*CSChuangShiCityJianShe) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{38} }

func (m *CSChuangShiCityJianShe) GetCityId() int64 {
	if m != nil && m.CityId != nil {
		return *m.CityId
	}
	return 0
}

func (m *CSChuangShiCityJianShe) GetBuildType() int32 {
	if m != nil && m.BuildType != nil {
		return *m.BuildType
	}
	return 0
}

func (m *CSChuangShiCityJianShe) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

type SCChuangShiCityJianShe struct {
	City             *ChuangShiCity `protobuf:"bytes,1,req,name=city" json:"city,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *SCChuangShiCityJianShe) Reset()                    { *m = SCChuangShiCityJianShe{} }
func (m *SCChuangShiCityJianShe) String() string            { return proto.CompactTextString(m) }
func (*SCChuangShiCityJianShe) ProtoMessage()               {}
func (*SCChuangShiCityJianShe) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{39} }

func (m *SCChuangShiCityJianShe) GetCity() *ChuangShiCity {
	if m != nil {
		return m.City
	}
	return nil
}

type CSChuangShiCityTianQiSet struct {
	CityId           *int64 `protobuf:"varint,1,req,name=cityId" json:"cityId,omitempty"`
	Level            *int32 `protobuf:"varint,2,req,name=level" json:"level,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSChuangShiCityTianQiSet) Reset()                    { *m = CSChuangShiCityTianQiSet{} }
func (m *CSChuangShiCityTianQiSet) String() string            { return proto.CompactTextString(m) }
func (*CSChuangShiCityTianQiSet) ProtoMessage()               {}
func (*CSChuangShiCityTianQiSet) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{40} }

func (m *CSChuangShiCityTianQiSet) GetCityId() int64 {
	if m != nil && m.CityId != nil {
		return *m.CityId
	}
	return 0
}

func (m *CSChuangShiCityTianQiSet) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

type SCChuangShiCityTianQiSet struct {
	CityId           *int64 `protobuf:"varint,1,req,name=cityId" json:"cityId,omitempty"`
	Level            *int32 `protobuf:"varint,2,req,name=level" json:"level,omitempty"`
	CampType         *int32 `protobuf:"varint,3,req,name=campType" json:"campType,omitempty"`
	CityType         *int32 `protobuf:"varint,4,req,name=cityType" json:"cityType,omitempty"`
	Index            *int32 `protobuf:"varint,5,req,name=index" json:"index,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCChuangShiCityTianQiSet) Reset()                    { *m = SCChuangShiCityTianQiSet{} }
func (m *SCChuangShiCityTianQiSet) String() string            { return proto.CompactTextString(m) }
func (*SCChuangShiCityTianQiSet) ProtoMessage()               {}
func (*SCChuangShiCityTianQiSet) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{41} }

func (m *SCChuangShiCityTianQiSet) GetCityId() int64 {
	if m != nil && m.CityId != nil {
		return *m.CityId
	}
	return 0
}

func (m *SCChuangShiCityTianQiSet) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *SCChuangShiCityTianQiSet) GetCampType() int32 {
	if m != nil && m.CampType != nil {
		return *m.CampType
	}
	return 0
}

func (m *SCChuangShiCityTianQiSet) GetCityType() int32 {
	if m != nil && m.CityType != nil {
		return *m.CityType
	}
	return 0
}

func (m *SCChuangShiCityTianQiSet) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

type CSChuangShiPositionAdvance struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSChuangShiPositionAdvance) Reset()                    { *m = CSChuangShiPositionAdvance{} }
func (m *CSChuangShiPositionAdvance) String() string            { return proto.CompactTextString(m) }
func (*CSChuangShiPositionAdvance) ProtoMessage()               {}
func (*CSChuangShiPositionAdvance) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{42} }

type SCChuangShiPositionAdvance struct {
	Success          *bool  `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	Level            *int32 `protobuf:"varint,2,req,name=level" json:"level,omitempty"`
	WeiWang          *int32 `protobuf:"varint,3,req,name=weiWang" json:"weiWang,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCChuangShiPositionAdvance) Reset()                    { *m = SCChuangShiPositionAdvance{} }
func (m *SCChuangShiPositionAdvance) String() string            { return proto.CompactTextString(m) }
func (*SCChuangShiPositionAdvance) ProtoMessage()               {}
func (*SCChuangShiPositionAdvance) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{43} }

func (m *SCChuangShiPositionAdvance) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *SCChuangShiPositionAdvance) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *SCChuangShiPositionAdvance) GetWeiWang() int32 {
	if m != nil && m.WeiWang != nil {
		return *m.WeiWang
	}
	return 0
}

type CSChuangShiGuanZhiRew struct {
	RewLevel         *int32 `protobuf:"varint,1,req,name=rewLevel" json:"rewLevel,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSChuangShiGuanZhiRew) Reset()                    { *m = CSChuangShiGuanZhiRew{} }
func (m *CSChuangShiGuanZhiRew) String() string            { return proto.CompactTextString(m) }
func (*CSChuangShiGuanZhiRew) ProtoMessage()               {}
func (*CSChuangShiGuanZhiRew) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{44} }

func (m *CSChuangShiGuanZhiRew) GetRewLevel() int32 {
	if m != nil && m.RewLevel != nil {
		return *m.RewLevel
	}
	return 0
}

type SCChuangShiGuanZhiRew struct {
	RewLevel         *int32 `protobuf:"varint,1,req,name=rewLevel" json:"rewLevel,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCChuangShiGuanZhiRew) Reset()                    { *m = SCChuangShiGuanZhiRew{} }
func (m *SCChuangShiGuanZhiRew) String() string            { return proto.CompactTextString(m) }
func (*SCChuangShiGuanZhiRew) ProtoMessage()               {}
func (*SCChuangShiGuanZhiRew) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{45} }

func (m *SCChuangShiGuanZhiRew) GetRewLevel() int32 {
	if m != nil && m.RewLevel != nil {
		return *m.RewLevel
	}
	return 0
}

type CSChuangShiEnterCity struct {
	CityId           *int64 `protobuf:"varint,1,req,name=cityId" json:"cityId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSChuangShiEnterCity) Reset()                    { *m = CSChuangShiEnterCity{} }
func (m *CSChuangShiEnterCity) String() string            { return proto.CompactTextString(m) }
func (*CSChuangShiEnterCity) ProtoMessage()               {}
func (*CSChuangShiEnterCity) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{46} }

func (m *CSChuangShiEnterCity) GetCityId() int64 {
	if m != nil && m.CityId != nil {
		return *m.CityId
	}
	return 0
}

type SCChuangShiEnterCity struct {
	CityId           *int64 `protobuf:"varint,1,req,name=cityId" json:"cityId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCChuangShiEnterCity) Reset()                    { *m = SCChuangShiEnterCity{} }
func (m *SCChuangShiEnterCity) String() string            { return proto.CompactTextString(m) }
func (*SCChuangShiEnterCity) ProtoMessage()               {}
func (*SCChuangShiEnterCity) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{47} }

func (m *SCChuangShiEnterCity) GetCityId() int64 {
	if m != nil && m.CityId != nil {
		return *m.CityId
	}
	return 0
}

type CSChuangShiGongChengTarget struct {
	CityId           *int64 `protobuf:"varint,1,req,name=cityId" json:"cityId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSChuangShiGongChengTarget) Reset()                    { *m = CSChuangShiGongChengTarget{} }
func (m *CSChuangShiGongChengTarget) String() string            { return proto.CompactTextString(m) }
func (*CSChuangShiGongChengTarget) ProtoMessage()               {}
func (*CSChuangShiGongChengTarget) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{48} }

func (m *CSChuangShiGongChengTarget) GetCityId() int64 {
	if m != nil && m.CityId != nil {
		return *m.CityId
	}
	return 0
}

type SCChuangShiGongChengTarget struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCChuangShiGongChengTarget) Reset()                    { *m = SCChuangShiGongChengTarget{} }
func (m *SCChuangShiGongChengTarget) String() string            { return proto.CompactTextString(m) }
func (*SCChuangShiGongChengTarget) ProtoMessage()               {}
func (*SCChuangShiGongChengTarget) Descriptor() ([]byte, []int) { return fileDescriptor18, []int{49} }

func init() {
	proto.RegisterType((*CSChuangShiYuGao)(nil), "ui.CSChuangShiYuGao")
	proto.RegisterType((*SCChuangShiYuGao)(nil), "ui.SCChuangShiYuGao")
	proto.RegisterType((*CSBaoMingChuangShi)(nil), "ui.CSBaoMingChuangShi")
	proto.RegisterType((*SCBaoMingChuangShi)(nil), "ui.SCBaoMingChuangShi")
	proto.RegisterType((*PlayerGuanZhiInfo)(nil), "ui.PlayerGuanZhiInfo")
	proto.RegisterType((*PlayerChuangShiInfo)(nil), "ui.PlayerChuangShiInfo")
	proto.RegisterType((*ChuangShiMemberInfo)(nil), "ui.ChuangShiMemberInfo")
	proto.RegisterType((*JianSheSkillInfo)(nil), "ui.JianSheSkillInfo")
	proto.RegisterType((*ChuangShiJianSheInfo)(nil), "ui.ChuangShiJianSheInfo")
	proto.RegisterType((*ChuangShiCity)(nil), "ui.ChuangShiCity")
	proto.RegisterType((*ChuangShiCamp)(nil), "ui.ChuangShiCamp")
	proto.RegisterType((*CSChuangShiInfo)(nil), "ui.CSChuangShiInfo")
	proto.RegisterType((*SCChuangShiInfo)(nil), "ui.SCChuangShiInfo")
	proto.RegisterType((*SCChuangShiPlayerInfoNotice)(nil), "ui.SCChuangShiPlayerInfoNotice")
	proto.RegisterType((*CSChuangShiJoinCamp)(nil), "ui.CSChuangShiJoinCamp")
	proto.RegisterType((*SCChuangShiJoinCamp)(nil), "ui.SCChuangShiJoinCamp")
	proto.RegisterType((*CSChuangShiShenWangBaoMingList)(nil), "ui.CSChuangShiShenWangBaoMingList")
	proto.RegisterType((*SCChuangShiShengWangBaoMingList)(nil), "ui.SCChuangShiShengWangBaoMingList")
	proto.RegisterType((*CSChuangShiShenWangBaoMing)(nil), "ui.CSChuangShiShenWangBaoMing")
	proto.RegisterType((*SCChuangShiShenWangBaoMing)(nil), "ui.SCChuangShiShenWangBaoMing")
	proto.RegisterType((*ChuangShiTouPiaoMemberInfo)(nil), "ui.ChuangShiTouPiaoMemberInfo")
	proto.RegisterType((*CSChuangShiShenWangTouPiaoList)(nil), "ui.CSChuangShiShenWangTouPiaoList")
	proto.RegisterType((*SCChuangShiShengWangTouPiaoList)(nil), "ui.SCChuangShiShengWangTouPiaoList")
	proto.RegisterType((*CSChuangShiShengWangTouPiao)(nil), "ui.CSChuangShiShengWangTouPiao")
	proto.RegisterType((*SCChuangShiShengWangTouPiao)(nil), "ui.SCChuangShiShengWangTouPiao")
	proto.RegisterType((*SCChuangShiShenWangBroadcast)(nil), "ui.SCChuangShiShenWangBroadcast")
	proto.RegisterType((*CSChuangShiCityRenMing)(nil), "ui.CSChuangShiCityRenMing")
	proto.RegisterType((*SCChuangShiCityRenMing)(nil), "ui.SCChuangShiCityRenMing")
	proto.RegisterType((*CampPaySchedule)(nil), "ui.CampPaySchedule")
	proto.RegisterType((*CSChuangShiCampPaySchedule)(nil), "ui.CSChuangShiCampPaySchedule")
	proto.RegisterType((*SCChuangShiCampPaySchedule)(nil), "ui.SCChuangShiCampPaySchedule")
	proto.RegisterType((*CityPaySchedule)(nil), "ui.CityPaySchedule")
	proto.RegisterType((*CSChuangShiCityPaySchedule)(nil), "ui.CSChuangShiCityPaySchedule")
	proto.RegisterType((*SCChuangShiCityPaySchedule)(nil), "ui.SCChuangShiCityPaySchedule")
	proto.RegisterType((*CSChuangShiMyPayReceive)(nil), "ui.CSChuangShiMyPayReceive")
	proto.RegisterType((*SCChuangShiMyPayReceive)(nil), "ui.SCChuangShiMyPayReceive")
	proto.RegisterType((*CSChuangShiCampPayReceive)(nil), "ui.CSChuangShiCampPayReceive")
	proto.RegisterType((*SCChuangShiCampPayReceive)(nil), "ui.SCChuangShiCampPayReceive")
	proto.RegisterType((*CSChuangShiCityJianShe)(nil), "ui.CSChuangShiCityJianShe")
	proto.RegisterType((*SCChuangShiCityJianShe)(nil), "ui.SCChuangShiCityJianShe")
	proto.RegisterType((*CSChuangShiCityTianQiSet)(nil), "ui.CSChuangShiCityTianQiSet")
	proto.RegisterType((*SCChuangShiCityTianQiSet)(nil), "ui.SCChuangShiCityTianQiSet")
	proto.RegisterType((*CSChuangShiPositionAdvance)(nil), "ui.CSChuangShiPositionAdvance")
	proto.RegisterType((*SCChuangShiPositionAdvance)(nil), "ui.SCChuangShiPositionAdvance")
	proto.RegisterType((*CSChuangShiGuanZhiRew)(nil), "ui.CSChuangShiGuanZhiRew")
	proto.RegisterType((*SCChuangShiGuanZhiRew)(nil), "ui.SCChuangShiGuanZhiRew")
	proto.RegisterType((*CSChuangShiEnterCity)(nil), "ui.CSChuangShiEnterCity")
	proto.RegisterType((*SCChuangShiEnterCity)(nil), "ui.SCChuangShiEnterCity")
	proto.RegisterType((*CSChuangShiGongChengTarget)(nil), "ui.CSChuangShiGongChengTarget")
	proto.RegisterType((*SCChuangShiGongChengTarget)(nil), "ui.SCChuangShiGongChengTarget")
}

func init() { proto.RegisterFile("chuangshi.proto", fileDescriptor18) }

var fileDescriptor18 = []byte{
	// 1222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x57, 0xdd, 0x4e, 0xe3, 0x46,
	0x1b, 0x56, 0xe2, 0x18, 0x92, 0x37, 0x09, 0x49, 0x0c, 0x2c, 0x5e, 0x58, 0xb1, 0x91, 0x91, 0xbe,
	0x2f, 0x5b, 0xb6, 0xec, 0x0a, 0xf5, 0x47, 0x2b, 0xf5, 0xa0, 0x6d, 0x5a, 0xb1, 0x41, 0x80, 0x52,
	0x8c, 0x54, 0x6d, 0xd5, 0x93, 0xc1, 0x1e, 0x9c, 0x59, 0xec, 0x19, 0xcb, 0x3f, 0x09, 0x9c, 0xf5,
	0x06, 0x7a, 0x43, 0xbd, 0x83, 0xde, 0x45, 0x2f, 0xa5, 0x9a, 0xf1, 0x0f, 0x63, 0x3b, 0x49, 0x39,
	0x23, 0x33, 0xef, 0xcf, 0xf3, 0x3c, 0xf3, 0xf8, 0x9d, 0x01, 0x7a, 0xd6, 0x2c, 0x46, 0xd4, 0x09,
	0x67, 0xe4, 0xc4, 0x0f, 0x58, 0xc4, 0xb4, 0x7a, 0x4c, 0xf6, 0xc1, 0x0e, 0x98, 0x9f, 0xfc, 0x36,
	0x34, 0xe8, 0x8f, 0xcd, 0xb1, 0x08, 0x32, 0x67, 0xe4, 0x53, 0x7c, 0x86, 0x98, 0xf1, 0x35, 0xf4,
	0xcd, 0x71, 0x71, 0x4d, 0xdb, 0x82, 0x0d, 0x12, 0x9e, 0x33, 0x42, 0xf5, 0xda, 0xb0, 0x3e, 0x52,
	0xb5, 0x01, 0xb4, 0x7c, 0xcc, 0x7c, 0x17, 0x5f, 0xc5, 0x9e, 0x5e, 0x1f, 0xd6, 0x47, 0x8a, 0xb1,
	0x03, 0xda, 0xd8, 0xfc, 0x11, 0xb1, 0x4b, 0x42, 0x9d, 0x3c, 0xdb, 0xf8, 0x0a, 0x34, 0x73, 0x5c,
	0x5e, 0xd5, 0x0e, 0xa1, 0xc9, 0x41, 0x4c, 0xe8, 0x1d, 0xd3, 0x6b, 0x43, 0x65, 0xd4, 0x3e, 0xed,
	0x9c, 0xc4, 0xe4, 0xe4, 0xa7, 0x74, 0xcd, 0xb8, 0x80, 0xc1, 0xd4, 0x45, 0x8f, 0x38, 0x38, 0x8b,
	0x11, 0xfd, 0x6d, 0x46, 0xf8, 0xa2, 0xd6, 0x05, 0xd5, 0xc5, 0x73, 0xec, 0xa6, 0x10, 0x7a, 0xb0,
	0xb9, 0xc0, 0xe4, 0x57, 0x44, 0x1d, 0x01, 0x40, 0xd5, 0xf6, 0xa0, 0x17, 0x60, 0x0b, 0x93, 0x39,
	0xbe, 0xc6, 0x8b, 0x0b, 0x11, 0xa9, 0xf0, 0x0d, 0xe3, 0xaf, 0x1a, 0x6c, 0x27, 0xe5, 0x72, 0x04,
	0xa2, 0x60, 0x1b, 0x14, 0x9f, 0x85, 0x69, 0xb9, 0x2e, 0xa8, 0x9f, 0xc9, 0x1d, 0xa6, 0x09, 0x1b,
	0xad, 0x0f, 0x4d, 0x9b, 0x20, 0x8f, 0x51, 0x3b, 0x14, 0x55, 0x14, 0xb9, 0x5f, 0x23, 0x0b, 0xb1,
	0x90, 0xe7, 0xdf, 0x3c, 0xfa, 0x58, 0x57, 0x45, 0x8d, 0x2f, 0xa0, 0xed, 0x3c, 0x01, 0xd6, 0x37,
	0x86, 0xf5, 0x51, 0xfb, 0x74, 0x97, 0x33, 0xab, 0xb2, 0xd1, 0x00, 0x42, 0xe2, 0x50, 0x33, 0x42,
	0x51, 0x1c, 0xea, 0x9b, 0x22, 0x5f, 0x03, 0x98, 0xb3, 0x08, 0xa7, 0x6b, 0x4d, 0x01, 0xfe, 0xcf,
	0x3a, 0x6c, 0xe7, 0xb0, 0x2f, 0xb1, 0x77, 0x8b, 0x03, 0x91, 0xdf, 0x87, 0xa6, 0xef, 0xa2, 0xe8,
	0x8e, 0x05, 0x5e, 0xca, 0xa0, 0x0f, 0xcd, 0x10, 0x07, 0x73, 0x1c, 0x4c, 0xec, 0x54, 0x91, 0x0e,
	0x34, 0x28, 0xf2, 0xb0, 0x20, 0xd0, 0xca, 0xe8, 0x36, 0x32, 0xba, 0x77, 0x2c, 0xb0, 0x12, 0xe4,
	0x8a, 0xb6, 0x03, 0x1d, 0xe4, 0xba, 0x04, 0x51, 0x0b, 0x5f, 0xf1, 0x8c, 0x0d, 0x91, 0xd1, 0x05,
	0xd5, 0xc3, 0xde, 0xc4, 0x16, 0xf0, 0x14, 0xfe, 0x13, 0xb9, 0x53, 0x96, 0x22, 0xe3, 0x68, 0xb3,
	0x9c, 0x89, 0xad, 0xb7, 0x2a, 0x9a, 0x40, 0x86, 0x21, 0x60, 0x2e, 0xd6, 0xdb, 0xe2, 0x57, 0x1b,
	0x94, 0x10, 0x3f, 0xe8, 0x1d, 0xf1, 0x63, 0x0b, 0x36, 0x16, 0x84, 0x3a, 0x13, 0x5b, 0xef, 0x66,
	0x04, 0x16, 0x18, 0xf9, 0x8c, 0x4e, 0x6c, 0x7d, 0x2b, 0xb3, 0xd9, 0x1d, 0x0a, 0x67, 0x44, 0x2c,
	0xf5, 0x84, 0x1e, 0xdf, 0x42, 0xff, 0x9c, 0x20, 0x6a, 0xce, 0xb0, 0x79, 0x4f, 0x5c, 0x77, 0x99,
	0x33, 0x38, 0x19, 0x2b, 0x22, 0x73, 0x14, 0xe1, 0x1b, 0xe2, 0xe1, 0xd4, 0x9f, 0x7f, 0xd4, 0x60,
	0x27, 0x17, 0x32, 0x2d, 0x21, 0xb2, 0x3b, 0xd0, 0x88, 0x38, 0xde, 0xdc, 0x07, 0x49, 0xad, 0x7a,
	0x06, 0x18, 0x3f, 0xf8, 0x89, 0x91, 0xb4, 0xff, 0x43, 0x2b, 0xe4, 0x4d, 0x2f, 0x48, 0x18, 0xe9,
	0x0d, 0xe1, 0xdb, 0x1d, 0x7e, 0xba, 0x15, 0x40, 0xbb, 0xd0, 0x4d, 0x02, 0x79, 0x25, 0x13, 0x47,
	0xba, 0x3a, 0xac, 0x8d, 0x54, 0xe3, 0x9f, 0x1a, 0x74, 0x73, 0x08, 0x63, 0x12, 0x3d, 0xf2, 0xde,
	0x5c, 0xaf, 0xa7, 0x13, 0xb4, 0x48, 0xf4, 0x28, 0xd4, 0xab, 0x67, 0x68, 0x08, 0xb5, 0xf1, 0x43,
	0x0a, 0xe0, 0x18, 0xe0, 0x9e, 0x50, 0x27, 0xb1, 0x81, 0xde, 0x18, 0xd6, 0x46, 0xed, 0xd3, 0x3d,
	0x8e, 0x60, 0x99, 0x43, 0xb6, 0xa1, 0xcd, 0x02, 0xe2, 0x50, 0xe4, 0x8e, 0x79, 0x0b, 0x35, 0xd3,
	0x9c, 0xb7, 0x98, 0xd8, 0xe2, 0x88, 0x15, 0xed, 0x4b, 0x68, 0x7f, 0x4e, 0xd0, 0x0b, 0x52, 0x9b,
	0x82, 0x94, 0x5e, 0x28, 0x29, 0x6b, 0x95, 0x7f, 0x25, 0xcd, 0xca, 0x57, 0x22, 0x0c, 0x60, 0xfc,
	0x5d, 0xa0, 0x88, 0x3c, 0xbf, 0x44, 0xb1, 0xc8, 0xa0, 0xbe, 0x9e, 0x41, 0x17, 0x54, 0x9f, 0x2d,
	0x70, 0x90, 0x7e, 0x81, 0x47, 0x89, 0x3c, 0x92, 0xfa, 0x83, 0x42, 0xa6, 0x50, 0x74, 0x04, 0x9b,
	0x1e, 0xf6, 0x44, 0x8c, 0x2a, 0x62, 0xd6, 0x55, 0x4f, 0xb8, 0x6c, 0x54, 0xb8, 0x08, 0xbf, 0x1b,
	0x03, 0xe8, 0x49, 0xc3, 0x51, 0x0c, 0x26, 0x0b, 0x7a, 0xd2, 0x6c, 0x14, 0x65, 0x8e, 0x12, 0xcb,
	0x8b, 0x8e, 0xb5, 0x65, 0xa8, 0xb8, 0x08, 0xc7, 0x00, 0xbe, 0x18, 0x01, 0x62, 0x30, 0xd4, 0xc5,
	0x60, 0xd8, 0x7b, 0x1a, 0x0c, 0xc5, 0x26, 0xe7, 0x70, 0x20, 0x35, 0x99, 0xe6, 0x79, 0x57, 0x2c,
	0x22, 0x16, 0x2e, 0xd5, 0xaa, 0xad, 0xaf, 0x75, 0x04, 0xdb, 0x12, 0x07, 0x3e, 0xc1, 0xab, 0x87,
	0xc2, 0x83, 0xa4, 0x86, 0x2b, 0x82, 0x86, 0x70, 0x28, 0x55, 0x32, 0x67, 0x98, 0xf2, 0x59, 0x98,
	0x8e, 0x76, 0xce, 0xde, 0xb8, 0x86, 0xd7, 0x52, 0x19, 0x1e, 0xe1, 0x94, 0x42, 0xb4, 0x77, 0xb0,
	0xe5, 0xe5, 0x27, 0x20, 0x49, 0xb6, 0xea, 0x90, 0x8c, 0x57, 0xb0, 0xbf, 0xba, 0xab, 0xf1, 0x16,
	0xf6, 0x4b, 0x1d, 0xa5, 0x5d, 0xee, 0xf5, 0x30, 0x19, 0xa5, 0x09, 0x83, 0xdf, 0x61, 0x3f, 0x8f,
	0xbd, 0x61, 0xf1, 0x94, 0x20, 0x26, 0xd9, 0xe1, 0x18, 0xe0, 0x09, 0x9a, 0x2c, 0xeb, 0x32, 0xef,
	0x0c, 0xa0, 0x15, 0x11, 0xeb, 0x1e, 0x47, 0xd9, 0xfd, 0xb7, 0x4a, 0x9f, 0xb4, 0x8f, 0xd0, 0xe7,
	0xd3, 0x72, 0x7d, 0xa4, 0x10, 0xed, 0x9b, 0x15, 0xfa, 0x1c, 0x16, 0x80, 0x54, 0xc0, 0x1b, 0xef,
	0xe1, 0xa0, 0xd4, 0x5c, 0x2e, 0xcd, 0xe1, 0x86, 0xb1, 0xef, 0xb3, 0x20, 0x9a, 0xd8, 0x82, 0x9a,
	0x62, 0x7c, 0x5f, 0x30, 0xd9, 0x33, 0x32, 0x24, 0x39, 0x13, 0xc2, 0x1f, 0xe1, 0xd5, 0x32, 0xf1,
	0x03, 0x86, 0x6c, 0x0b, 0x85, 0x51, 0xfa, 0x25, 0x3e, 0x43, 0x4d, 0xe3, 0x3b, 0x78, 0x21, 0xa1,
	0xe7, 0x9f, 0xf1, 0x35, 0xa6, 0xd9, 0x11, 0xa6, 0xe3, 0x2a, 0xc1, 0xa0, 0x01, 0xdc, 0xe2, 0x31,
	0xf3, 0x3c, 0x12, 0xa5, 0xb7, 0x9c, 0x62, 0x7c, 0x80, 0x17, 0x12, 0x0e, 0x39, 0xfb, 0x35, 0x34,
	0x78, 0x76, 0xda, 0xbe, 0x3a, 0x2c, 0x8c, 0xf7, 0xd0, 0xe3, 0x4e, 0x9f, 0xa2, 0x47, 0xd3, 0x9a,
	0x61, 0x3b, 0x76, 0x71, 0xa5, 0x63, 0x17, 0xd4, 0x00, 0x45, 0x84, 0xa5, 0xa4, 0xcf, 0x0a, 0x7e,
	0x2c, 0x27, 0xbf, 0x81, 0x4e, 0x98, 0xfe, 0x2d, 0x1d, 0xde, 0xb6, 0x68, 0x5c, 0x0c, 0xe5, 0xc6,
	0x96, 0x51, 0x97, 0x76, 0xdf, 0x41, 0x8f, 0x03, 0x94, 0x6b, 0xe7, 0xb7, 0x6f, 0x7e, 0x4f, 0xad,
	0xc1, 0x55, 0xca, 0x5d, 0x87, 0xab, 0x18, 0x5a, 0xc6, 0x55, 0xda, 0x7d, 0x09, 0x7b, 0x52, 0x9b,
	0x4b, 0xbe, 0x77, 0x9d, 0xbc, 0xb9, 0xf8, 0x96, 0x94, 0x58, 0xd8, 0x3a, 0x80, 0x97, 0x55, 0xd1,
	0xa4, 0xcd, 0xaa, 0x10, 0xd9, 0xe6, 0xc7, 0x8a, 0x33, 0xd2, 0xdb, 0xa8, 0x72, 0x4e, 0x03, 0x68,
	0xdd, 0xc6, 0xc4, 0xb5, 0xa5, 0xcb, 0xb3, 0x0d, 0x0a, 0x8d, 0xbd, 0xf4, 0x11, 0x58, 0x75, 0x49,
	0x56, 0xe9, 0x3f, 0x5d, 0xf2, 0x01, 0xf4, 0x12, 0x88, 0x1b, 0x82, 0xe8, 0x2f, 0xc4, 0xc4, 0xd1,
	0x32, 0xbb, 0x48, 0xcf, 0x07, 0xc3, 0x05, 0xbd, 0xd4, 0xf5, 0xb9, 0xa9, 0x85, 0xa7, 0x94, 0x52,
	0x79, 0x1e, 0x34, 0x8a, 0xcf, 0x03, 0x71, 0xb9, 0x97, 0x86, 0xe5, 0x94, 0x85, 0x24, 0x22, 0x8c,
	0xfe, 0x60, 0xcf, 0xf9, 0x1b, 0xcd, 0xb8, 0x2c, 0x9c, 0x6c, 0x69, 0x97, 0x3f, 0x6f, 0xc3, 0xd8,
	0xb2, 0x70, 0x98, 0x18, 0xac, 0x59, 0x86, 0x23, 0x3d, 0x7f, 0x13, 0x41, 0xdf, 0xc0, 0xae, 0xd4,
	0x2c, 0x7d, 0xda, 0x5e, 0xe3, 0x05, 0x87, 0x19, 0x64, 0x0f, 0xf0, 0x5a, 0x16, 0x2a, 0x75, 0x5e,
	0x1b, 0xfa, 0x3f, 0xd8, 0x91, 0xaa, 0xfe, 0x4c, 0x23, 0x1c, 0x88, 0x6b, 0xbd, 0x24, 0x16, 0x8f,
	0x93, 0x4a, 0xae, 0x8e, 0x7b, 0x5b, 0x90, 0xe4, 0x8c, 0xf1, 0xff, 0x42, 0x30, 0x75, 0x6e, 0x50,
	0xe0, 0x54, 0x8f, 0xa0, 0x64, 0xfe, 0x52, 0xf4, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x91, 0xcf,
	0xed, 0x3d, 0x4e, 0x0d, 0x00, 0x00,
}
