// Code generated by protoc-gen-go. DO NOT EDIT.
// source: drop.proto

package ui

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GoldEquipAttrList struct {
	AttrList         []int32 `protobuf:"varint,1,rep,name=attrList" json:"attrList,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GoldEquipAttrList) Reset()                    { *m = GoldEquipAttrList{} }
func (m *GoldEquipAttrList) String() string            { return proto.CompactTextString(m) }
func (*GoldEquipAttrList) ProtoMessage()               {}
func (*GoldEquipAttrList) Descriptor() ([]byte, []int) { return fileDescriptor26, []int{0} }

func (m *GoldEquipAttrList) GetAttrList() []int32 {
	if m != nil {
		return m.AttrList
	}
	return nil
}

type DropInfo struct {
	ItemId           *int32             `protobuf:"varint,1,req,name=itemId" json:"itemId,omitempty"`
	Num              *int32             `protobuf:"varint,2,req,name=num" json:"num,omitempty"`
	Level            *int32             `protobuf:"varint,3,opt,name=level,def=0" json:"level,omitempty"`
	Bind             *int32             `protobuf:"varint,4,opt,name=bind,def=0" json:"bind,omitempty"`
	UpstarLevel      *int32             `protobuf:"varint,5,opt,name=upstarLevel" json:"upstarLevel,omitempty"`
	Attr             *GoldEquipAttrList `protobuf:"bytes,6,opt,name=attr" json:"attr,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *DropInfo) Reset()                    { *m = DropInfo{} }
func (m *DropInfo) String() string            { return proto.CompactTextString(m) }
func (*DropInfo) ProtoMessage()               {}
func (*DropInfo) Descriptor() ([]byte, []int) { return fileDescriptor26, []int{1} }

const Default_DropInfo_Level int32 = 0
const Default_DropInfo_Bind int32 = 0

func (m *DropInfo) GetItemId() int32 {
	if m != nil && m.ItemId != nil {
		return *m.ItemId
	}
	return 0
}

func (m *DropInfo) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

func (m *DropInfo) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return Default_DropInfo_Level
}

func (m *DropInfo) GetBind() int32 {
	if m != nil && m.Bind != nil {
		return *m.Bind
	}
	return Default_DropInfo_Bind
}

func (m *DropInfo) GetUpstarLevel() int32 {
	if m != nil && m.UpstarLevel != nil {
		return *m.UpstarLevel
	}
	return 0
}

func (m *DropInfo) GetAttr() *GoldEquipAttrList {
	if m != nil {
		return m.Attr
	}
	return nil
}

func init() {
	proto.RegisterType((*GoldEquipAttrList)(nil), "ui.GoldEquipAttrList")
	proto.RegisterType((*DropInfo)(nil), "ui.DropInfo")
}

func init() { proto.RegisterFile("drop.proto", fileDescriptor26) }

var fileDescriptor26 = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x29, 0xca, 0x2f,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0xcd, 0x54, 0x52, 0xe5, 0x12, 0x74, 0xcf,
	0xcf, 0x49, 0x71, 0x2d, 0x2c, 0xcd, 0x2c, 0x70, 0x2c, 0x29, 0x29, 0xf2, 0xc9, 0x2c, 0x2e, 0x11,
	0x12, 0xe0, 0xe2, 0x48, 0x84, 0xb2, 0x25, 0x18, 0x15, 0x98, 0x35, 0x58, 0x95, 0x5a, 0x18, 0xb9,
	0x38, 0x5c, 0x8a, 0xf2, 0x0b, 0x3c, 0xf3, 0xd2, 0xf2, 0x85, 0xf8, 0xb8, 0xd8, 0x32, 0x4b, 0x52,
	0x73, 0x3d, 0x53, 0x24, 0x18, 0x15, 0x98, 0x34, 0x58, 0x85, 0xb8, 0xb9, 0x98, 0xf3, 0x4a, 0x73,
	0x25, 0x98, 0xc0, 0x1c, 0x01, 0x2e, 0xd6, 0x9c, 0xd4, 0xb2, 0xd4, 0x1c, 0x09, 0x66, 0x05, 0x46,
	0x0d, 0x56, 0x2b, 0x46, 0x03, 0x21, 0x7e, 0x2e, 0x96, 0xa4, 0xcc, 0xbc, 0x14, 0x09, 0x16, 0x98,
	0x80, 0x30, 0x17, 0x77, 0x69, 0x41, 0x71, 0x49, 0x62, 0x91, 0x0f, 0x58, 0x21, 0x2b, 0x48, 0x5c,
	0x48, 0x99, 0x8b, 0x05, 0x64, 0xa7, 0x04, 0x9b, 0x02, 0xa3, 0x06, 0xb7, 0x91, 0xa8, 0x5e, 0x69,
	0xa6, 0x1e, 0x86, 0xc3, 0x00, 0x01, 0x00, 0x00, 0xff, 0xff, 0x56, 0xe3, 0xaf, 0xda, 0xbe, 0x00,
	0x00, 0x00,
}
