// Code generated by protoc-gen-go. DO NOT EDIT.
// source: email.proto

package ui

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type AttachementInfo struct {
	ItemId           *int32        `protobuf:"varint,1,req,name=itemId" json:"itemId,omitempty"`
	Num              *int32        `protobuf:"varint,2,req,name=num" json:"num,omitempty"`
	Level            *int32        `protobuf:"varint,3,opt,name=level" json:"level,omitempty"`
	Upstar           *int32        `protobuf:"varint,4,opt,name=upstar" json:"upstar,omitempty"`
	AttrList         []int32       `protobuf:"varint,5,rep,name=attrList" json:"attrList,omitempty"`
	BindType         *int32        `protobuf:"varint,6,opt,name=bindType" json:"bindType,omitempty"`
	IsRandomAttr     *bool         `protobuf:"varint,7,opt,name=isRandomAttr" json:"isRandomAttr,omitempty"`
	ExpireType       *int32        `protobuf:"varint,8,opt,name=expireType" json:"expireType,omitempty"`
	ExpireTime       *int64        `protobuf:"varint,9,opt,name=expireTime" json:"expireTime,omitempty"`
	ItemGetTime      *int64        `protobuf:"varint,10,opt,name=itemGetTime" json:"itemGetTime,omitempty"`
	Quality          *int32        `protobuf:"varint,11,opt,name=quality" json:"quality,omitempty"`
	Sex              *int32        `protobuf:"varint,12,opt,name=sex" json:"sex,omitempty"`
	TalentList       []*TalentInfo `protobuf:"bytes,13,rep,name=TalentList" json:"TalentList,omitempty"`
	Danbei           *int32        `protobuf:"varint,14,opt,name=danbei" json:"danbei,omitempty"`
	OpenLightLevel   *int32        `protobuf:"varint,15,opt,name=openLightLevel" json:"openLightLevel,omitempty"`
	OpenTimes        *int32        `protobuf:"varint,16,opt,name=openTimes" json:"openTimes,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *AttachementInfo) Reset()                    { *m = AttachementInfo{} }
func (m *AttachementInfo) String() string            { return proto.CompactTextString(m) }
func (*AttachementInfo) ProtoMessage()               {}
func (*AttachementInfo) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{0} }

func (m *AttachementInfo) GetItemId() int32 {
	if m != nil && m.ItemId != nil {
		return *m.ItemId
	}
	return 0
}

func (m *AttachementInfo) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

func (m *AttachementInfo) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *AttachementInfo) GetUpstar() int32 {
	if m != nil && m.Upstar != nil {
		return *m.Upstar
	}
	return 0
}

func (m *AttachementInfo) GetAttrList() []int32 {
	if m != nil {
		return m.AttrList
	}
	return nil
}

func (m *AttachementInfo) GetBindType() int32 {
	if m != nil && m.BindType != nil {
		return *m.BindType
	}
	return 0
}

func (m *AttachementInfo) GetIsRandomAttr() bool {
	if m != nil && m.IsRandomAttr != nil {
		return *m.IsRandomAttr
	}
	return false
}

func (m *AttachementInfo) GetExpireType() int32 {
	if m != nil && m.ExpireType != nil {
		return *m.ExpireType
	}
	return 0
}

func (m *AttachementInfo) GetExpireTime() int64 {
	if m != nil && m.ExpireTime != nil {
		return *m.ExpireTime
	}
	return 0
}

func (m *AttachementInfo) GetItemGetTime() int64 {
	if m != nil && m.ItemGetTime != nil {
		return *m.ItemGetTime
	}
	return 0
}

func (m *AttachementInfo) GetQuality() int32 {
	if m != nil && m.Quality != nil {
		return *m.Quality
	}
	return 0
}

func (m *AttachementInfo) GetSex() int32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func (m *AttachementInfo) GetTalentList() []*TalentInfo {
	if m != nil {
		return m.TalentList
	}
	return nil
}

func (m *AttachementInfo) GetDanbei() int32 {
	if m != nil && m.Danbei != nil {
		return *m.Danbei
	}
	return 0
}

func (m *AttachementInfo) GetOpenLightLevel() int32 {
	if m != nil && m.OpenLightLevel != nil {
		return *m.OpenLightLevel
	}
	return 0
}

func (m *AttachementInfo) GetOpenTimes() int32 {
	if m != nil && m.OpenTimes != nil {
		return *m.OpenTimes
	}
	return 0
}

type EmailInfo struct {
	EmailId          *int64             `protobuf:"varint,1,req,name=emailId" json:"emailId,omitempty"`
	IsRead           *int32             `protobuf:"varint,2,req,name=isRead" json:"isRead,omitempty"`
	IsGetAttachment  *int32             `protobuf:"varint,3,req,name=isGetAttachment" json:"isGetAttachment,omitempty"`
	CreateTime       *int64             `protobuf:"varint,4,req,name=createTime" json:"createTime,omitempty"`
	Title            *string            `protobuf:"bytes,5,req,name=title" json:"title,omitempty"`
	Content          *string            `protobuf:"bytes,6,req,name=content" json:"content,omitempty"`
	AttachementInfo  []*AttachementInfo `protobuf:"bytes,7,rep,name=AttachementInfo" json:"AttachementInfo,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *EmailInfo) Reset()                    { *m = EmailInfo{} }
func (m *EmailInfo) String() string            { return proto.CompactTextString(m) }
func (*EmailInfo) ProtoMessage()               {}
func (*EmailInfo) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{1} }

func (m *EmailInfo) GetEmailId() int64 {
	if m != nil && m.EmailId != nil {
		return *m.EmailId
	}
	return 0
}

func (m *EmailInfo) GetIsRead() int32 {
	if m != nil && m.IsRead != nil {
		return *m.IsRead
	}
	return 0
}

func (m *EmailInfo) GetIsGetAttachment() int32 {
	if m != nil && m.IsGetAttachment != nil {
		return *m.IsGetAttachment
	}
	return 0
}

func (m *EmailInfo) GetCreateTime() int64 {
	if m != nil && m.CreateTime != nil {
		return *m.CreateTime
	}
	return 0
}

func (m *EmailInfo) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *EmailInfo) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *EmailInfo) GetAttachementInfo() []*AttachementInfo {
	if m != nil {
		return m.AttachementInfo
	}
	return nil
}

type CSEmailsGet struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSEmailsGet) Reset()                    { *m = CSEmailsGet{} }
func (m *CSEmailsGet) String() string            { return proto.CompactTextString(m) }
func (*CSEmailsGet) ProtoMessage()               {}
func (*CSEmailsGet) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{2} }

type SCEmailsGet struct {
	EmailInfo        []*EmailInfo `protobuf:"bytes,1,rep,name=emailInfo" json:"emailInfo,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *SCEmailsGet) Reset()                    { *m = SCEmailsGet{} }
func (m *SCEmailsGet) String() string            { return proto.CompactTextString(m) }
func (*SCEmailsGet) ProtoMessage()               {}
func (*SCEmailsGet) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{3} }

func (m *SCEmailsGet) GetEmailInfo() []*EmailInfo {
	if m != nil {
		return m.EmailInfo
	}
	return nil
}

type CSReadEmail struct {
	EmailId          *int64 `protobuf:"varint,1,req,name=emailId" json:"emailId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSReadEmail) Reset()                    { *m = CSReadEmail{} }
func (m *CSReadEmail) String() string            { return proto.CompactTextString(m) }
func (*CSReadEmail) ProtoMessage()               {}
func (*CSReadEmail) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{4} }

func (m *CSReadEmail) GetEmailId() int64 {
	if m != nil && m.EmailId != nil {
		return *m.EmailId
	}
	return 0
}

type SCReadEmail struct {
	EmailId          *int64 `protobuf:"varint,1,req,name=emailId" json:"emailId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCReadEmail) Reset()                    { *m = SCReadEmail{} }
func (m *SCReadEmail) String() string            { return proto.CompactTextString(m) }
func (*SCReadEmail) ProtoMessage()               {}
func (*SCReadEmail) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{5} }

func (m *SCReadEmail) GetEmailId() int64 {
	if m != nil && m.EmailId != nil {
		return *m.EmailId
	}
	return 0
}

type CSDelHadReadEmail struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSDelHadReadEmail) Reset()                    { *m = CSDelHadReadEmail{} }
func (m *CSDelHadReadEmail) String() string            { return proto.CompactTextString(m) }
func (*CSDelHadReadEmail) ProtoMessage()               {}
func (*CSDelHadReadEmail) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{6} }

type SCDelHadReadEmail struct {
	EmailIdList      []int64 `protobuf:"varint,1,rep,name=emailIdList" json:"emailIdList,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SCDelHadReadEmail) Reset()                    { *m = SCDelHadReadEmail{} }
func (m *SCDelHadReadEmail) String() string            { return proto.CompactTextString(m) }
func (*SCDelHadReadEmail) ProtoMessage()               {}
func (*SCDelHadReadEmail) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{7} }

func (m *SCDelHadReadEmail) GetEmailIdList() []int64 {
	if m != nil {
		return m.EmailIdList
	}
	return nil
}

type CSDelEmail struct {
	EmailId          *int64 `protobuf:"varint,1,req,name=emailId" json:"emailId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSDelEmail) Reset()                    { *m = CSDelEmail{} }
func (m *CSDelEmail) String() string            { return proto.CompactTextString(m) }
func (*CSDelEmail) ProtoMessage()               {}
func (*CSDelEmail) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{8} }

func (m *CSDelEmail) GetEmailId() int64 {
	if m != nil && m.EmailId != nil {
		return *m.EmailId
	}
	return 0
}

type SCDelEmail struct {
	EmailId          *int64 `protobuf:"varint,1,req,name=emailId" json:"emailId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCDelEmail) Reset()                    { *m = SCDelEmail{} }
func (m *SCDelEmail) String() string            { return proto.CompactTextString(m) }
func (*SCDelEmail) ProtoMessage()               {}
func (*SCDelEmail) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{9} }

func (m *SCDelEmail) GetEmailId() int64 {
	if m != nil && m.EmailId != nil {
		return *m.EmailId
	}
	return 0
}

type CSGetAttachmentBatch struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSGetAttachmentBatch) Reset()                    { *m = CSGetAttachmentBatch{} }
func (m *CSGetAttachmentBatch) String() string            { return proto.CompactTextString(m) }
func (*CSGetAttachmentBatch) ProtoMessage()               {}
func (*CSGetAttachmentBatch) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{10} }

type SCGetAttachmentBatch struct {
	EmailIdList      []int64            `protobuf:"varint,1,rep,name=emailIdList" json:"emailIdList,omitempty"`
	AttachementInfo  []*AttachementInfo `protobuf:"bytes,2,rep,name=attachementInfo" json:"attachementInfo,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *SCGetAttachmentBatch) Reset()                    { *m = SCGetAttachmentBatch{} }
func (m *SCGetAttachmentBatch) String() string            { return proto.CompactTextString(m) }
func (*SCGetAttachmentBatch) ProtoMessage()               {}
func (*SCGetAttachmentBatch) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{11} }

func (m *SCGetAttachmentBatch) GetEmailIdList() []int64 {
	if m != nil {
		return m.EmailIdList
	}
	return nil
}

func (m *SCGetAttachmentBatch) GetAttachementInfo() []*AttachementInfo {
	if m != nil {
		return m.AttachementInfo
	}
	return nil
}

type CSGetAttachment struct {
	EmailId          *int64 `protobuf:"varint,1,req,name=emailId" json:"emailId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSGetAttachment) Reset()                    { *m = CSGetAttachment{} }
func (m *CSGetAttachment) String() string            { return proto.CompactTextString(m) }
func (*CSGetAttachment) ProtoMessage()               {}
func (*CSGetAttachment) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{12} }

func (m *CSGetAttachment) GetEmailId() int64 {
	if m != nil && m.EmailId != nil {
		return *m.EmailId
	}
	return 0
}

type SCGetAttachment struct {
	EmailId          *int64             `protobuf:"varint,1,req,name=emailId" json:"emailId,omitempty"`
	AttachementInfo  []*AttachementInfo `protobuf:"bytes,2,rep,name=attachementInfo" json:"attachementInfo,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *SCGetAttachment) Reset()                    { *m = SCGetAttachment{} }
func (m *SCGetAttachment) String() string            { return proto.CompactTextString(m) }
func (*SCGetAttachment) ProtoMessage()               {}
func (*SCGetAttachment) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{13} }

func (m *SCGetAttachment) GetEmailId() int64 {
	if m != nil && m.EmailId != nil {
		return *m.EmailId
	}
	return 0
}

func (m *SCGetAttachment) GetAttachementInfo() []*AttachementInfo {
	if m != nil {
		return m.AttachementInfo
	}
	return nil
}

type SCAddEmail struct {
	EmailInfo        *EmailInfo `protobuf:"bytes,1,req,name=emailInfo" json:"emailInfo,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *SCAddEmail) Reset()                    { *m = SCAddEmail{} }
func (m *SCAddEmail) String() string            { return proto.CompactTextString(m) }
func (*SCAddEmail) ProtoMessage()               {}
func (*SCAddEmail) Descriptor() ([]byte, []int) { return fileDescriptor27, []int{14} }

func (m *SCAddEmail) GetEmailInfo() *EmailInfo {
	if m != nil {
		return m.EmailInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*AttachementInfo)(nil), "ui.AttachementInfo")
	proto.RegisterType((*EmailInfo)(nil), "ui.EmailInfo")
	proto.RegisterType((*CSEmailsGet)(nil), "ui.CSEmailsGet")
	proto.RegisterType((*SCEmailsGet)(nil), "ui.SCEmailsGet")
	proto.RegisterType((*CSReadEmail)(nil), "ui.CSReadEmail")
	proto.RegisterType((*SCReadEmail)(nil), "ui.SCReadEmail")
	proto.RegisterType((*CSDelHadReadEmail)(nil), "ui.CSDelHadReadEmail")
	proto.RegisterType((*SCDelHadReadEmail)(nil), "ui.SCDelHadReadEmail")
	proto.RegisterType((*CSDelEmail)(nil), "ui.CSDelEmail")
	proto.RegisterType((*SCDelEmail)(nil), "ui.SCDelEmail")
	proto.RegisterType((*CSGetAttachmentBatch)(nil), "ui.CSGetAttachmentBatch")
	proto.RegisterType((*SCGetAttachmentBatch)(nil), "ui.SCGetAttachmentBatch")
	proto.RegisterType((*CSGetAttachment)(nil), "ui.CSGetAttachment")
	proto.RegisterType((*SCGetAttachment)(nil), "ui.SCGetAttachment")
	proto.RegisterType((*SCAddEmail)(nil), "ui.SCAddEmail")
}

func init() { proto.RegisterFile("email.proto", fileDescriptor27) }

var fileDescriptor27 = []byte{
	// 495 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0xed, 0xba, 0x49, 0xc6, 0x4d, 0xdc, 0x38, 0x51, 0x59, 0x21, 0x15, 0x59, 0x7b, 0xf2,
	0x01, 0x05, 0x89, 0x7f, 0x10, 0x0c, 0x2a, 0x95, 0x72, 0x40, 0x75, 0x2f, 0x1c, 0x37, 0xf1, 0x40,
	0x56, 0xf2, 0x17, 0xf6, 0x18, 0x35, 0xbf, 0x88, 0xdf, 0xc1, 0x3f, 0x43, 0x3b, 0x4e, 0x83, 0xb0,
	0x09, 0x12, 0xc7, 0x79, 0x33, 0x6f, 0xf6, 0xbd, 0x37, 0x0b, 0x1e, 0xe6, 0x4a, 0x67, 0xab, 0xaa,
	0x2e, 0xa9, 0x0c, 0xec, 0x56, 0xbf, 0x84, 0xad, 0xda, 0x1e, 0xba, 0x5a, 0xfe, 0xb4, 0xc1, 0x5f,
	0x13, 0xa9, 0xdd, 0x1e, 0x73, 0x2c, 0xe8, 0xbe, 0xf8, 0x52, 0x06, 0x33, 0xb8, 0xd4, 0x84, 0xf9,
	0x7d, 0x2a, 0xac, 0xd0, 0x8e, 0xdc, 0xc0, 0x03, 0xa7, 0x68, 0x73, 0x61, 0x73, 0x31, 0x05, 0x37,
	0xc3, 0xef, 0x98, 0x09, 0x27, 0xb4, 0x22, 0xd7, 0xcc, 0xb6, 0x55, 0x43, 0xaa, 0x16, 0x17, 0x5c,
	0x5f, 0xc3, 0x58, 0x11, 0xd5, 0x1b, 0xdd, 0x90, 0x70, 0x43, 0xa7, 0x43, 0xb6, 0xba, 0x48, 0x1f,
	0x0f, 0x15, 0x8a, 0x4b, 0x9e, 0x59, 0xc2, 0x95, 0x6e, 0x1e, 0x54, 0x91, 0x96, 0xf9, 0x9a, 0xa8,
	0x16, 0xa3, 0xd0, 0x8a, 0xc6, 0x41, 0x00, 0x80, 0x4f, 0x95, 0xae, 0x91, 0x27, 0xc7, 0x3c, 0xf9,
	0x1b, 0xd3, 0x39, 0x8a, 0x49, 0x68, 0x45, 0x4e, 0xb0, 0x00, 0xcf, 0xa8, 0xbb, 0x43, 0x62, 0x10,
	0x18, 0xf4, 0x61, 0xf4, 0xad, 0x55, 0x99, 0xa6, 0x83, 0xf0, 0x98, 0xe9, 0x81, 0xd3, 0xe0, 0x93,
	0xb8, 0xe2, 0x42, 0x02, 0x3c, 0xaa, 0x0c, 0x0b, 0x62, 0x59, 0xd3, 0xd0, 0x89, 0xbc, 0xb7, 0xb3,
	0x55, 0xab, 0x57, 0x1d, 0xfa, 0x6c, 0x3a, 0x55, 0xc5, 0x16, 0xb5, 0x98, 0x31, 0xe7, 0x06, 0x66,
	0x65, 0x85, 0xc5, 0x46, 0x7f, 0xdd, 0xd3, 0x86, 0x0d, 0xfb, 0x8c, 0xcf, 0x61, 0x62, 0x70, 0xf3,
	0x76, 0x23, 0xae, 0x0d, 0x24, 0x7f, 0x58, 0x30, 0xf9, 0x60, 0x32, 0xe6, 0x45, 0x3e, 0x8c, 0x38,
	0xf0, 0x63, 0x7c, 0x0e, 0xc7, 0xd9, 0x3c, 0xa0, 0x4a, 0x8f, 0x09, 0xbe, 0x00, 0x5f, 0x37, 0x77,
	0x48, 0x5d, 0xec, 0x26, 0x75, 0xe1, 0x70, 0x23, 0x00, 0xd8, 0xd5, 0xa8, 0xa8, 0x73, 0x7b, 0xc1,
	0xe4, 0x29, 0xb8, 0xa4, 0x29, 0x43, 0xe1, 0x86, 0x76, 0x34, 0x31, 0xcb, 0x77, 0x65, 0x41, 0x86,
	0x73, 0xc9, 0xc0, 0xeb, 0xc1, 0xf9, 0xc4, 0x88, 0xfd, 0x2d, 0x8c, 0xbf, 0x5e, 0x4b, 0x4e, 0xc1,
	0x8b, 0x13, 0x96, 0x6a, 0x04, 0xc8, 0x37, 0xe0, 0x25, 0xf1, 0xa9, 0x0c, 0x42, 0x98, 0xe0, 0xb3,
	0x0d, 0x61, 0xf1, 0x96, 0xa9, 0xd9, 0x72, 0xf2, 0x26, 0x5f, 0x19, 0xbe, 0xb1, 0xc2, 0xd0, 0xc0,
	0xaa, 0xe9, 0x27, 0xf1, 0x3f, 0xfa, 0x0b, 0x98, 0xc7, 0xc9, 0x7b, 0xcc, 0x3e, 0xaa, 0xf4, 0x34,
	0x25, 0x23, 0x98, 0x27, 0x71, 0x0f, 0x34, 0x57, 0x3e, 0x52, 0xf9, 0x66, 0x46, 0x8d, 0x23, 0x6f,
	0x01, 0x98, 0x7e, 0x66, 0xfb, 0x2d, 0x00, 0x2f, 0x3a, 0xd3, 0xbe, 0x81, 0x65, 0x9c, 0xfc, 0x91,
	0xfb, 0x3b, 0x45, 0xbb, 0xbd, 0xfc, 0x0c, 0xcb, 0x24, 0x1e, 0xe2, 0x7f, 0x95, 0x60, 0xf2, 0x56,
	0xbd, 0xbc, 0xed, 0xf3, 0x79, 0x4b, 0xf0, 0x7b, 0x4f, 0x0e, 0x65, 0x7d, 0x02, 0xbf, 0xf7, 0xfc,
	0xf0, 0x0b, 0xfd, 0xdf, 0xab, 0x2b, 0x93, 0xc3, 0x3a, 0x3d, 0x26, 0xd9, 0xbb, 0xaa, 0x3d, 0xb8,
	0xea, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3d, 0xc7, 0x42, 0x99, 0x21, 0x04, 0x00, 0x00,
}
