// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gem.proto

package ui

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type MineInfo struct {
	Level            *int32 `protobuf:"varint,1,req,name=level" json:"level,omitempty"`
	Storage          *int32 `protobuf:"varint,2,req,name=storage" json:"storage,omitempty"`
	LastTime         *int64 `protobuf:"varint,3,req,name=lastTime" json:"lastTime,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MineInfo) Reset()                    { *m = MineInfo{} }
func (m *MineInfo) String() string            { return proto.CompactTextString(m) }
func (*MineInfo) ProtoMessage()               {}
func (*MineInfo) Descriptor() ([]byte, []int) { return fileDescriptor42, []int{0} }

func (m *MineInfo) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *MineInfo) GetStorage() int32 {
	if m != nil && m.Storage != nil {
		return *m.Storage
	}
	return 0
}

func (m *MineInfo) GetLastTime() int64 {
	if m != nil && m.LastTime != nil {
		return *m.LastTime
	}
	return 0
}

type CSGemMineGet struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSGemMineGet) Reset()                    { *m = CSGemMineGet{} }
func (m *CSGemMineGet) String() string            { return proto.CompactTextString(m) }
func (*CSGemMineGet) ProtoMessage()               {}
func (*CSGemMineGet) Descriptor() ([]byte, []int) { return fileDescriptor42, []int{1} }

type SCGemMineGet struct {
	MineInfo         *MineInfo `protobuf:"bytes,1,req,name=mineInfo" json:"mineInfo,omitempty"`
	Stone            *int64    `protobuf:"varint,2,req,name=stone" json:"stone,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *SCGemMineGet) Reset()                    { *m = SCGemMineGet{} }
func (m *SCGemMineGet) String() string            { return proto.CompactTextString(m) }
func (*SCGemMineGet) ProtoMessage()               {}
func (*SCGemMineGet) Descriptor() ([]byte, []int) { return fileDescriptor42, []int{2} }

func (m *SCGemMineGet) GetMineInfo() *MineInfo {
	if m != nil {
		return m.MineInfo
	}
	return nil
}

func (m *SCGemMineGet) GetStone() int64 {
	if m != nil && m.Stone != nil {
		return *m.Stone
	}
	return 0
}

type CSGemMineActive struct {
	Level            *int32 `protobuf:"varint,1,req,name=level" json:"level,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSGemMineActive) Reset()                    { *m = CSGemMineActive{} }
func (m *CSGemMineActive) String() string            { return proto.CompactTextString(m) }
func (*CSGemMineActive) ProtoMessage()               {}
func (*CSGemMineActive) Descriptor() ([]byte, []int) { return fileDescriptor42, []int{3} }

func (m *CSGemMineActive) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

type SCGemMineActive struct {
	MineInfo         *MineInfo `protobuf:"bytes,1,req,name=mineInfo" json:"mineInfo,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *SCGemMineActive) Reset()                    { *m = SCGemMineActive{} }
func (m *SCGemMineActive) String() string            { return proto.CompactTextString(m) }
func (*SCGemMineActive) ProtoMessage()               {}
func (*SCGemMineActive) Descriptor() ([]byte, []int) { return fileDescriptor42, []int{4} }

func (m *SCGemMineActive) GetMineInfo() *MineInfo {
	if m != nil {
		return m.MineInfo
	}
	return nil
}

type CSGemMineReceive struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSGemMineReceive) Reset()                    { *m = CSGemMineReceive{} }
func (m *CSGemMineReceive) String() string            { return proto.CompactTextString(m) }
func (*CSGemMineReceive) ProtoMessage()               {}
func (*CSGemMineReceive) Descriptor() ([]byte, []int) { return fileDescriptor42, []int{5} }

type SCGemMineReceive struct {
	Stone            *int64 `protobuf:"varint,1,req,name=stone" json:"stone,omitempty"`
	LastTime         *int64 `protobuf:"varint,2,req,name=lastTime" json:"lastTime,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCGemMineReceive) Reset()                    { *m = SCGemMineReceive{} }
func (m *SCGemMineReceive) String() string            { return proto.CompactTextString(m) }
func (*SCGemMineReceive) ProtoMessage()               {}
func (*SCGemMineReceive) Descriptor() ([]byte, []int) { return fileDescriptor42, []int{6} }

func (m *SCGemMineReceive) GetStone() int64 {
	if m != nil && m.Stone != nil {
		return *m.Stone
	}
	return 0
}

func (m *SCGemMineReceive) GetLastTime() int64 {
	if m != nil && m.LastTime != nil {
		return *m.LastTime
	}
	return 0
}

type CSGemGamble struct {
	Type             *int32 `protobuf:"varint,1,req,name=type" json:"type,omitempty"`
	TenEven          *bool  `protobuf:"varint,2,req,name=tenEven" json:"tenEven,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSGemGamble) Reset()                    { *m = CSGemGamble{} }
func (m *CSGemGamble) String() string            { return proto.CompactTextString(m) }
func (*CSGemGamble) ProtoMessage()               {}
func (*CSGemGamble) Descriptor() ([]byte, []int) { return fileDescriptor42, []int{7} }

func (m *CSGemGamble) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *CSGemGamble) GetTenEven() bool {
	if m != nil && m.TenEven != nil {
		return *m.TenEven
	}
	return false
}

type SCGemGamble struct {
	DropList         []*DropInfo `protobuf:"bytes,1,rep,name=dropList" json:"dropList,omitempty"`
	Stone            *int64      `protobuf:"varint,2,req,name=stone" json:"stone,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *SCGemGamble) Reset()                    { *m = SCGemGamble{} }
func (m *SCGemGamble) String() string            { return proto.CompactTextString(m) }
func (*SCGemGamble) ProtoMessage()               {}
func (*SCGemGamble) Descriptor() ([]byte, []int) { return fileDescriptor42, []int{8} }

func (m *SCGemGamble) GetDropList() []*DropInfo {
	if m != nil {
		return m.DropList
	}
	return nil
}

func (m *SCGemGamble) GetStone() int64 {
	if m != nil && m.Stone != nil {
		return *m.Stone
	}
	return 0
}

func init() {
	proto.RegisterType((*MineInfo)(nil), "ui.MineInfo")
	proto.RegisterType((*CSGemMineGet)(nil), "ui.CSGemMineGet")
	proto.RegisterType((*SCGemMineGet)(nil), "ui.SCGemMineGet")
	proto.RegisterType((*CSGemMineActive)(nil), "ui.CSGemMineActive")
	proto.RegisterType((*SCGemMineActive)(nil), "ui.SCGemMineActive")
	proto.RegisterType((*CSGemMineReceive)(nil), "ui.CSGemMineReceive")
	proto.RegisterType((*SCGemMineReceive)(nil), "ui.SCGemMineReceive")
	proto.RegisterType((*CSGemGamble)(nil), "ui.CSGemGamble")
	proto.RegisterType((*SCGemGamble)(nil), "ui.SCGemGamble")
}

func init() { proto.RegisterFile("gem.proto", fileDescriptor42) }

var fileDescriptor42 = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xd9, 0xc6, 0xc5, 0x38, 0xad, 0xb6, 0xe4, 0x54, 0x3c, 0x2c, 0x25, 0xa7, 0x3d, 0x48,
	0x41, 0xbd, 0xae, 0x07, 0x59, 0xa5, 0x08, 0x7a, 0x71, 0xfd, 0x03, 0x75, 0x1d, 0x97, 0x40, 0x93,
	0x94, 0x76, 0x5a, 0xf0, 0xdf, 0x4b, 0xd3, 0x9a, 0xaa, 0x08, 0x1e, 0x33, 0x3c, 0xbe, 0xef, 0xe5,
	0xc1, 0xc9, 0x01, 0x75, 0x5e, 0x37, 0x96, 0xac, 0x08, 0x3a, 0x75, 0x0e, 0x6f, 0x8d, 0xad, 0xc7,
	0xb7, 0xdc, 0x00, 0x7f, 0x52, 0x06, 0x1f, 0xcc, 0xbb, 0x15, 0xa7, 0xb0, 0xac, 0xb0, 0xc7, 0x2a,
	0x5d, 0x64, 0xc1, 0x7a, 0x29, 0x62, 0x38, 0x6e, 0xc9, 0x36, 0xe5, 0x01, 0xd3, 0xc0, 0x1d, 0x12,
	0xe0, 0x55, 0xd9, 0xd2, 0x8b, 0xd2, 0x98, 0xb2, 0x2c, 0x58, 0x33, 0x79, 0x06, 0xd1, 0x76, 0x57,
	0xa0, 0x1e, 0x10, 0x05, 0x92, 0xbc, 0x81, 0x68, 0xb7, 0x9d, 0xdf, 0x62, 0x05, 0x5c, 0x4f, 0x74,
	0x07, 0x0d, 0xaf, 0xa2, 0xbc, 0x53, 0xf9, 0x77, 0x63, 0x4b, 0xd6, 0x8c, 0x02, 0x26, 0x33, 0x88,
	0x3d, 0xee, 0x76, 0x4f, 0xaa, 0xc7, 0x5f, 0x9d, 0xe4, 0x25, 0xc4, 0x5e, 0x30, 0x25, 0xfe, 0x71,
	0x48, 0x01, 0x89, 0x87, 0x3e, 0xe3, 0x1e, 0x55, 0x8f, 0xf2, 0x1a, 0x12, 0x8f, 0x99, 0x6e, 0x73,
	0x97, 0x01, 0xc2, 0x7e, 0x7c, 0x76, 0x6c, 0x77, 0x01, 0xa1, 0x03, 0x15, 0xa5, 0x7e, 0xad, 0x50,
	0x44, 0x70, 0x44, 0x1f, 0x35, 0xce, 0x63, 0x11, 0x9a, 0xfb, 0x1e, 0x8d, 0x4b, 0x73, 0xb9, 0x81,
	0xd0, 0x29, 0xa6, 0xf4, 0x0a, 0xf8, 0xb0, 0xfa, 0xa3, 0x6a, 0x29, 0x5d, 0x64, 0xec, 0xab, 0xe5,
	0x5d, 0x63, 0xeb, 0x3f, 0x96, 0xf8, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xb2, 0x4d, 0x82, 0xbf, 0xb2,
	0x01, 0x00, 0x00,
}
