// Code generated by protoc-gen-go. DO NOT EDIT.
// source: itemskill.proto

package ui

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ItemSkillInfo struct {
	Typ              *int32 `protobuf:"varint,1,req,name=typ" json:"typ,omitempty"`
	Level            *int32 `protobuf:"varint,2,req,name=level" json:"level,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ItemSkillInfo) Reset()                    { *m = ItemSkillInfo{} }
func (m *ItemSkillInfo) String() string            { return proto.CompactTextString(m) }
func (*ItemSkillInfo) ProtoMessage()               {}
func (*ItemSkillInfo) Descriptor() ([]byte, []int) { return fileDescriptor54, []int{0} }

func (m *ItemSkillInfo) GetTyp() int32 {
	if m != nil && m.Typ != nil {
		return *m.Typ
	}
	return 0
}

func (m *ItemSkillInfo) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

type SCItemSkillActive struct {
	ItemSkill        *ItemSkillInfo `protobuf:"bytes,1,req,name=itemSkill" json:"itemSkill,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *SCItemSkillActive) Reset()                    { *m = SCItemSkillActive{} }
func (m *SCItemSkillActive) String() string            { return proto.CompactTextString(m) }
func (*SCItemSkillActive) ProtoMessage()               {}
func (*SCItemSkillActive) Descriptor() ([]byte, []int) { return fileDescriptor54, []int{1} }

func (m *SCItemSkillActive) GetItemSkill() *ItemSkillInfo {
	if m != nil {
		return m.ItemSkill
	}
	return nil
}

type SCItemSkillUpgrade struct {
	ItemSkill        *ItemSkillInfo `protobuf:"bytes,1,req,name=itemSkill" json:"itemSkill,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *SCItemSkillUpgrade) Reset()                    { *m = SCItemSkillUpgrade{} }
func (m *SCItemSkillUpgrade) String() string            { return proto.CompactTextString(m) }
func (*SCItemSkillUpgrade) ProtoMessage()               {}
func (*SCItemSkillUpgrade) Descriptor() ([]byte, []int) { return fileDescriptor54, []int{2} }

func (m *SCItemSkillUpgrade) GetItemSkill() *ItemSkillInfo {
	if m != nil {
		return m.ItemSkill
	}
	return nil
}

type CSItemSkillAllGet struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSItemSkillAllGet) Reset()                    { *m = CSItemSkillAllGet{} }
func (m *CSItemSkillAllGet) String() string            { return proto.CompactTextString(m) }
func (*CSItemSkillAllGet) ProtoMessage()               {}
func (*CSItemSkillAllGet) Descriptor() ([]byte, []int) { return fileDescriptor54, []int{3} }

type SCItemSkillAllGet struct {
	ItemSkillList    []*ItemSkillInfo `protobuf:"bytes,1,rep,name=itemSkillList" json:"itemSkillList,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *SCItemSkillAllGet) Reset()                    { *m = SCItemSkillAllGet{} }
func (m *SCItemSkillAllGet) String() string            { return proto.CompactTextString(m) }
func (*SCItemSkillAllGet) ProtoMessage()               {}
func (*SCItemSkillAllGet) Descriptor() ([]byte, []int) { return fileDescriptor54, []int{4} }

func (m *SCItemSkillAllGet) GetItemSkillList() []*ItemSkillInfo {
	if m != nil {
		return m.ItemSkillList
	}
	return nil
}

func init() {
	proto.RegisterType((*ItemSkillInfo)(nil), "ui.ItemSkillInfo")
	proto.RegisterType((*SCItemSkillActive)(nil), "ui.SCItemSkillActive")
	proto.RegisterType((*SCItemSkillUpgrade)(nil), "ui.SCItemSkillUpgrade")
	proto.RegisterType((*CSItemSkillAllGet)(nil), "ui.CSItemSkillAllGet")
	proto.RegisterType((*SCItemSkillAllGet)(nil), "ui.SCItemSkillAllGet")
}

func init() { proto.RegisterFile("itemskill.proto", fileDescriptor54) }

var fileDescriptor54 = []byte{
	// 167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcf, 0x2c, 0x49, 0xcd,
	0x2d, 0xce, 0xce, 0xcc, 0xc9, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0xcd, 0x54,
	0xd2, 0xe6, 0xe2, 0xf5, 0x2c, 0x49, 0xcd, 0x0d, 0x06, 0x09, 0x7b, 0xe6, 0xa5, 0xe5, 0x0b, 0x71,
	0x73, 0x31, 0x97, 0x54, 0x16, 0x48, 0x30, 0x2a, 0x30, 0x69, 0xb0, 0x0a, 0xf1, 0x72, 0xb1, 0xe6,
	0xa4, 0x96, 0xa5, 0xe6, 0x48, 0x30, 0x81, 0xb8, 0x4a, 0x96, 0x5c, 0x82, 0xc1, 0xce, 0x70, 0xe5,
	0x8e, 0xc9, 0x25, 0x99, 0x65, 0xa9, 0x42, 0x2a, 0x5c, 0x9c, 0x99, 0x30, 0x21, 0xb0, 0x36, 0x6e,
	0x23, 0x41, 0xbd, 0xd2, 0x4c, 0x3d, 0x14, 0x63, 0x95, 0xac, 0xb8, 0x84, 0x90, 0xb4, 0x86, 0x16,
	0xa4, 0x17, 0x25, 0xa6, 0x10, 0xab, 0x57, 0x98, 0x4b, 0xd0, 0x39, 0x18, 0x61, 0x6d, 0x4e, 0x8e,
	0x7b, 0x6a, 0x89, 0x92, 0x2d, 0xaa, 0x5b, 0xc0, 0x82, 0x42, 0x1a, 0x5c, 0xbc, 0x70, 0xf3, 0x7c,
	0x32, 0x8b, 0x4b, 0x24, 0x18, 0x15, 0x98, 0xb1, 0x9a, 0x09, 0x08, 0x00, 0x00, 0xff, 0xff, 0x73,
	0xbb, 0xe0, 0x0c, 0x0d, 0x01, 0x00, 0x00,
}
