// Code generated by protoc-gen-go. DO NOT EDIT.
// source: realm.proto

package ui

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RealmRank struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Level            *int32  `protobuf:"varint,2,req,name=level" json:"level,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RealmRank) Reset()                    { *m = RealmRank{} }
func (m *RealmRank) String() string            { return proto.CompactTextString(m) }
func (*RealmRank) ProtoMessage()               {}
func (*RealmRank) Descriptor() ([]byte, []int) { return fileDescriptor86, []int{0} }

func (m *RealmRank) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *RealmRank) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

type SCRealmLevel struct {
	Level            *int32 `protobuf:"varint,1,req,name=level" json:"level,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCRealmLevel) Reset()                    { *m = SCRealmLevel{} }
func (m *SCRealmLevel) String() string            { return proto.CompactTextString(m) }
func (*SCRealmLevel) ProtoMessage()               {}
func (*SCRealmLevel) Descriptor() ([]byte, []int) { return fileDescriptor86, []int{1} }

func (m *SCRealmLevel) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

type CSRealmToKill struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSRealmToKill) Reset()                    { *m = CSRealmToKill{} }
func (m *CSRealmToKill) String() string            { return proto.CompactTextString(m) }
func (*CSRealmToKill) ProtoMessage()               {}
func (*CSRealmToKill) Descriptor() ([]byte, []int) { return fileDescriptor86, []int{2} }

type SCRealmToKill struct {
	Level            *int32 `protobuf:"varint,1,req,name=level" json:"level,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCRealmToKill) Reset()                    { *m = SCRealmToKill{} }
func (m *SCRealmToKill) String() string            { return proto.CompactTextString(m) }
func (*SCRealmToKill) ProtoMessage()               {}
func (*SCRealmToKill) Descriptor() ([]byte, []int) { return fileDescriptor86, []int{3} }

func (m *SCRealmToKill) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

type SCRealmToKillResult struct {
	State            *bool  `protobuf:"varint,1,req,name=state" json:"state,omitempty"`
	Level            *int32 `protobuf:"varint,2,req,name=level" json:"level,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCRealmToKillResult) Reset()                    { *m = SCRealmToKillResult{} }
func (m *SCRealmToKillResult) String() string            { return proto.CompactTextString(m) }
func (*SCRealmToKillResult) ProtoMessage()               {}
func (*SCRealmToKillResult) Descriptor() ([]byte, []int) { return fileDescriptor86, []int{4} }

func (m *SCRealmToKillResult) GetState() bool {
	if m != nil && m.State != nil {
		return *m.State
	}
	return false
}

func (m *SCRealmToKillResult) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

type SCRealmSceneInfo struct {
	CreateTime       *int64 `protobuf:"varint,1,req,name=createTime" json:"createTime,omitempty"`
	Level            *int32 `protobuf:"varint,2,req,name=level" json:"level,omitempty"`
	OwnerId          *int64 `protobuf:"varint,3,req,name=ownerId" json:"ownerId,omitempty"`
	SpouseId         *int64 `protobuf:"varint,4,req,name=spouseId" json:"spouseId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCRealmSceneInfo) Reset()                    { *m = SCRealmSceneInfo{} }
func (m *SCRealmSceneInfo) String() string            { return proto.CompactTextString(m) }
func (*SCRealmSceneInfo) ProtoMessage()               {}
func (*SCRealmSceneInfo) Descriptor() ([]byte, []int) { return fileDescriptor86, []int{5} }

func (m *SCRealmSceneInfo) GetCreateTime() int64 {
	if m != nil && m.CreateTime != nil {
		return *m.CreateTime
	}
	return 0
}

func (m *SCRealmSceneInfo) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *SCRealmSceneInfo) GetOwnerId() int64 {
	if m != nil && m.OwnerId != nil {
		return *m.OwnerId
	}
	return 0
}

func (m *SCRealmSceneInfo) GetSpouseId() int64 {
	if m != nil && m.SpouseId != nil {
		return *m.SpouseId
	}
	return 0
}

type CSRealmRankGet struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSRealmRankGet) Reset()                    { *m = CSRealmRankGet{} }
func (m *CSRealmRankGet) String() string            { return proto.CompactTextString(m) }
func (*CSRealmRankGet) ProtoMessage()               {}
func (*CSRealmRankGet) Descriptor() ([]byte, []int) { return fileDescriptor86, []int{6} }

type SCRealmRankGet struct {
	RankList         []*RealmRank `protobuf:"bytes,1,rep,name=rankList" json:"rankList,omitempty"`
	Pos              *int32       `protobuf:"varint,2,req,name=pos" json:"pos,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *SCRealmRankGet) Reset()                    { *m = SCRealmRankGet{} }
func (m *SCRealmRankGet) String() string            { return proto.CompactTextString(m) }
func (*SCRealmRankGet) ProtoMessage()               {}
func (*SCRealmRankGet) Descriptor() ([]byte, []int) { return fileDescriptor86, []int{7} }

func (m *SCRealmRankGet) GetRankList() []*RealmRank {
	if m != nil {
		return m.RankList
	}
	return nil
}

func (m *SCRealmRankGet) GetPos() int32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

type CSRealmPair struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSRealmPair) Reset()                    { *m = CSRealmPair{} }
func (m *CSRealmPair) String() string            { return proto.CompactTextString(m) }
func (*CSRealmPair) ProtoMessage()               {}
func (*CSRealmPair) Descriptor() ([]byte, []int) { return fileDescriptor86, []int{8} }

type SCRealmPair struct {
	InviteTime       *int64 `protobuf:"varint,1,req,name=inviteTime" json:"inviteTime,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCRealmPair) Reset()                    { *m = SCRealmPair{} }
func (m *SCRealmPair) String() string            { return proto.CompactTextString(m) }
func (*SCRealmPair) ProtoMessage()               {}
func (*SCRealmPair) Descriptor() ([]byte, []int) { return fileDescriptor86, []int{9} }

func (m *SCRealmPair) GetInviteTime() int64 {
	if m != nil && m.InviteTime != nil {
		return *m.InviteTime
	}
	return 0
}

type CSRealmPairCancle struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSRealmPairCancle) Reset()                    { *m = CSRealmPairCancle{} }
func (m *CSRealmPairCancle) String() string            { return proto.CompactTextString(m) }
func (*CSRealmPairCancle) ProtoMessage()               {}
func (*CSRealmPairCancle) Descriptor() ([]byte, []int) { return fileDescriptor86, []int{10} }

type SCRealmPairCancle struct {
	Result           *int32 `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCRealmPairCancle) Reset()                    { *m = SCRealmPairCancle{} }
func (m *SCRealmPairCancle) String() string            { return proto.CompactTextString(m) }
func (*SCRealmPairCancle) ProtoMessage()               {}
func (*SCRealmPairCancle) Descriptor() ([]byte, []int) { return fileDescriptor86, []int{11} }

func (m *SCRealmPairCancle) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

type SCRealmPairPushSpouse struct {
	PlayerId         *int64 `protobuf:"varint,1,req,name=playerId" json:"playerId,omitempty"`
	Level            *int32 `protobuf:"varint,2,req,name=level" json:"level,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCRealmPairPushSpouse) Reset()                    { *m = SCRealmPairPushSpouse{} }
func (m *SCRealmPairPushSpouse) String() string            { return proto.CompactTextString(m) }
func (*SCRealmPairPushSpouse) ProtoMessage()               {}
func (*SCRealmPairPushSpouse) Descriptor() ([]byte, []int) { return fileDescriptor86, []int{12} }

func (m *SCRealmPairPushSpouse) GetPlayerId() int64 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *SCRealmPairPushSpouse) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

type SCRealmPairPushCancle struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SCRealmPairPushCancle) Reset()                    { *m = SCRealmPairPushCancle{} }
func (m *SCRealmPairPushCancle) String() string            { return proto.CompactTextString(m) }
func (*SCRealmPairPushCancle) ProtoMessage()               {}
func (*SCRealmPairPushCancle) Descriptor() ([]byte, []int) { return fileDescriptor86, []int{13} }

func (m *SCRealmPairPushCancle) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type CSRealmPairDeal struct {
	Result           *int32 `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSRealmPairDeal) Reset()                    { *m = CSRealmPairDeal{} }
func (m *CSRealmPairDeal) String() string            { return proto.CompactTextString(m) }
func (*CSRealmPairDeal) ProtoMessage()               {}
func (*CSRealmPairDeal) Descriptor() ([]byte, []int) { return fileDescriptor86, []int{14} }

func (m *CSRealmPairDeal) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

type SCRealmPairDeal struct {
	Result           *int32 `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCRealmPairDeal) Reset()                    { *m = SCRealmPairDeal{} }
func (m *SCRealmPairDeal) String() string            { return proto.CompactTextString(m) }
func (*SCRealmPairDeal) ProtoMessage()               {}
func (*SCRealmPairDeal) Descriptor() ([]byte, []int) { return fileDescriptor86, []int{15} }

func (m *SCRealmPairDeal) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

type SCRealmSpouseRefused struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SCRealmSpouseRefused) Reset()                    { *m = SCRealmSpouseRefused{} }
func (m *SCRealmSpouseRefused) String() string            { return proto.CompactTextString(m) }
func (*SCRealmSpouseRefused) ProtoMessage()               {}
func (*SCRealmSpouseRefused) Descriptor() ([]byte, []int) { return fileDescriptor86, []int{16} }

func (m *SCRealmSpouseRefused) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type SCRealmPairResult struct {
	Identity         *bool  `protobuf:"varint,1,req,name=identity" json:"identity,omitempty"`
	State            *bool  `protobuf:"varint,2,req,name=state" json:"state,omitempty"`
	Level            *int32 `protobuf:"varint,3,req,name=level" json:"level,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCRealmPairResult) Reset()                    { *m = SCRealmPairResult{} }
func (m *SCRealmPairResult) String() string            { return proto.CompactTextString(m) }
func (*SCRealmPairResult) ProtoMessage()               {}
func (*SCRealmPairResult) Descriptor() ([]byte, []int) { return fileDescriptor86, []int{17} }

func (m *SCRealmPairResult) GetIdentity() bool {
	if m != nil && m.Identity != nil {
		return *m.Identity
	}
	return false
}

func (m *SCRealmPairResult) GetState() bool {
	if m != nil && m.State != nil {
		return *m.State
	}
	return false
}

func (m *SCRealmPairResult) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

type CSRealmNext struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSRealmNext) Reset()                    { *m = CSRealmNext{} }
func (m *CSRealmNext) String() string            { return proto.CompactTextString(m) }
func (*CSRealmNext) ProtoMessage()               {}
func (*CSRealmNext) Descriptor() ([]byte, []int) { return fileDescriptor86, []int{18} }

type SCRealmNext struct {
	Level            *int32 `protobuf:"varint,1,req,name=level" json:"level,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCRealmNext) Reset()                    { *m = SCRealmNext{} }
func (m *SCRealmNext) String() string            { return proto.CompactTextString(m) }
func (*SCRealmNext) ProtoMessage()               {}
func (*SCRealmNext) Descriptor() ([]byte, []int) { return fileDescriptor86, []int{19} }

func (m *SCRealmNext) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

type SCRealmInviteOffonline struct {
	InviteName       *string `protobuf:"bytes,1,req,name=inviteName" json:"inviteName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SCRealmInviteOffonline) Reset()                    { *m = SCRealmInviteOffonline{} }
func (m *SCRealmInviteOffonline) String() string            { return proto.CompactTextString(m) }
func (*SCRealmInviteOffonline) ProtoMessage()               {}
func (*SCRealmInviteOffonline) Descriptor() ([]byte, []int) { return fileDescriptor86, []int{20} }

func (m *SCRealmInviteOffonline) GetInviteName() string {
	if m != nil && m.InviteName != nil {
		return *m.InviteName
	}
	return ""
}

func init() {
	proto.RegisterType((*RealmRank)(nil), "ui.RealmRank")
	proto.RegisterType((*SCRealmLevel)(nil), "ui.SCRealmLevel")
	proto.RegisterType((*CSRealmToKill)(nil), "ui.CSRealmToKill")
	proto.RegisterType((*SCRealmToKill)(nil), "ui.SCRealmToKill")
	proto.RegisterType((*SCRealmToKillResult)(nil), "ui.SCRealmToKillResult")
	proto.RegisterType((*SCRealmSceneInfo)(nil), "ui.SCRealmSceneInfo")
	proto.RegisterType((*CSRealmRankGet)(nil), "ui.CSRealmRankGet")
	proto.RegisterType((*SCRealmRankGet)(nil), "ui.SCRealmRankGet")
	proto.RegisterType((*CSRealmPair)(nil), "ui.CSRealmPair")
	proto.RegisterType((*SCRealmPair)(nil), "ui.SCRealmPair")
	proto.RegisterType((*CSRealmPairCancle)(nil), "ui.CSRealmPairCancle")
	proto.RegisterType((*SCRealmPairCancle)(nil), "ui.SCRealmPairCancle")
	proto.RegisterType((*SCRealmPairPushSpouse)(nil), "ui.SCRealmPairPushSpouse")
	proto.RegisterType((*SCRealmPairPushCancle)(nil), "ui.SCRealmPairPushCancle")
	proto.RegisterType((*CSRealmPairDeal)(nil), "ui.CSRealmPairDeal")
	proto.RegisterType((*SCRealmPairDeal)(nil), "ui.SCRealmPairDeal")
	proto.RegisterType((*SCRealmSpouseRefused)(nil), "ui.SCRealmSpouseRefused")
	proto.RegisterType((*SCRealmPairResult)(nil), "ui.SCRealmPairResult")
	proto.RegisterType((*CSRealmNext)(nil), "ui.CSRealmNext")
	proto.RegisterType((*SCRealmNext)(nil), "ui.SCRealmNext")
	proto.RegisterType((*SCRealmInviteOffonline)(nil), "ui.SCRealmInviteOffonline")
}

func init() { proto.RegisterFile("realm.proto", fileDescriptor86) }

var fileDescriptor86 = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x4d, 0x6f, 0xd4, 0x30,
	0x14, 0xd4, 0x26, 0x2d, 0x6c, 0x5f, 0x9a, 0xdd, 0xad, 0x0b, 0x28, 0x07, 0x3e, 0x76, 0x0d, 0x48,
	0x7b, 0x40, 0x7b, 0x80, 0x0b, 0x27, 0x2e, 0x41, 0x42, 0x11, 0x55, 0xa9, 0x92, 0x1e, 0xb8, 0x5a,
	0x9b, 0x17, 0x61, 0xd5, 0xb5, 0xa3, 0xd8, 0x29, 0xf4, 0xdf, 0x23, 0x3b, 0x6e, 0xf3, 0xd1, 0x3d,
	0x7a, 0xe6, 0x8d, 0x3d, 0x6f, 0x3c, 0x10, 0x35, 0xc8, 0xc4, 0xed, 0xae, 0x6e, 0x94, 0x51, 0x24,
	0x68, 0x39, 0xdd, 0xc2, 0x49, 0x6e, 0xa1, 0x9c, 0xc9, 0x1b, 0x72, 0x0a, 0x47, 0x92, 0xdd, 0x62,
	0x32, 0x5b, 0x07, 0xdb, 0x13, 0x12, 0xc3, 0xb1, 0xc0, 0x3b, 0x14, 0x49, 0xb0, 0x0e, 0xb6, 0xc7,
	0xf4, 0x0d, 0x9c, 0x16, 0xa9, 0x9b, 0xbd, 0xb0, 0x68, 0x4f, 0xcf, 0x1c, 0xbd, 0x84, 0x38, 0x2d,
	0x1c, 0x7d, 0xad, 0x7e, 0x72, 0x21, 0xe8, 0x5b, 0x88, 0xfd, 0x7c, 0x07, 0x4c, 0x05, 0x5f, 0xe0,
	0x7c, 0xc4, 0xe7, 0xa8, 0x5b, 0x61, 0xec, 0x94, 0x36, 0xcc, 0x74, 0x26, 0xe6, 0x53, 0x13, 0xbf,
	0x61, 0xe5, 0x45, 0xc5, 0x1e, 0x25, 0x66, 0xb2, 0x52, 0x84, 0x00, 0xec, 0x1b, 0x64, 0x06, 0xaf,
	0xb9, 0xf7, 0x1e, 0x4e, 0x64, 0x64, 0x09, 0xcf, 0xd5, 0x5f, 0x89, 0x4d, 0x56, 0x26, 0xa1, 0xe3,
	0x57, 0x30, 0xd7, 0xb5, 0x6a, 0x35, 0x66, 0x65, 0x72, 0x64, 0x11, 0xba, 0x82, 0x85, 0xf7, 0x6f,
	0xa3, 0xf8, 0x81, 0x86, 0x7e, 0x83, 0x85, 0x7f, 0xcb, 0x23, 0xe4, 0x1d, 0xcc, 0x1b, 0x26, 0x6f,
	0x2e, 0xb8, 0x36, 0xc9, 0x6c, 0x1d, 0x6e, 0xa3, 0xcf, 0xf1, 0xae, 0xe5, 0xbb, 0x3e, 0xc0, 0x08,
	0xc2, 0x5a, 0x69, 0xef, 0x35, 0x86, 0xc8, 0xdf, 0x78, 0xc5, 0x78, 0x43, 0x37, 0x10, 0xf9, 0xeb,
	0xec, 0xd1, 0xba, 0xe6, 0xf2, 0x8e, 0x0f, 0x5d, 0xd3, 0x73, 0x38, 0x1b, 0x28, 0x52, 0x26, 0xf7,
	0x02, 0xe9, 0x7b, 0x38, 0x1b, 0xe8, 0x3a, 0x90, 0x2c, 0xe0, 0x59, 0xe3, 0xf2, 0xf2, 0x61, 0x7e,
	0x85, 0x97, 0x83, 0xa1, 0xab, 0x56, 0xff, 0x29, 0xdc, 0x7a, 0x76, 0xd1, 0x5a, 0xb0, 0x7b, 0xb7,
	0xfa, 0xa1, 0x68, 0xe8, 0xc7, 0x27, 0x4a, 0xff, 0xc4, 0xa8, 0x0c, 0x74, 0x03, 0xcb, 0x81, 0xb5,
	0xef, 0xc8, 0xc4, 0x13, 0x0f, 0x1b, 0x58, 0x0e, 0x6e, 0x3a, 0x38, 0xf2, 0x01, 0x5e, 0x3c, 0x7c,
	0x9f, 0xb3, 0x97, 0x63, 0xd5, 0x6a, 0x2c, 0x27, 0x6f, 0xa5, 0xa3, 0x8d, 0x7d, 0x2f, 0x56, 0x30,
	0xe7, 0x25, 0x4a, 0xc3, 0xcd, 0x7d, 0x5f, 0x8d, 0xae, 0x29, 0xc1, 0xb8, 0x29, 0xe1, 0x24, 0xfd,
	0x4b, 0xfc, 0x67, 0xe8, 0xeb, 0xc7, 0xf4, 0xed, 0x71, 0xda, 0xc5, 0x4f, 0xf0, 0xca, 0xb3, 0x99,
	0xfb, 0x93, 0x5f, 0x55, 0xa5, 0xa4, 0xe0, 0x12, 0xfb, 0x6f, 0xba, 0x7c, 0xf4, 0xf7, 0x3f, 0x00,
	0x00, 0xff, 0xff, 0x1c, 0x5e, 0x01, 0xa6, 0x45, 0x03, 0x00, 0x00,
}
