// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shopdiscount.proto

package ui

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ShopDiscountInfo struct {
	Typ              *int32 `protobuf:"varint,1,req,name=typ" json:"typ,omitempty"`
	StartTime        *int64 `protobuf:"varint,2,req,name=startTime" json:"startTime,omitempty"`
	EndTime          *int64 `protobuf:"varint,3,req,name=endTime" json:"endTime,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ShopDiscountInfo) Reset()                    { *m = ShopDiscountInfo{} }
func (m *ShopDiscountInfo) String() string            { return proto.CompactTextString(m) }
func (*ShopDiscountInfo) ProtoMessage()               {}
func (*ShopDiscountInfo) Descriptor() ([]byte, []int) { return fileDescriptor104, []int{0} }

func (m *ShopDiscountInfo) GetTyp() int32 {
	if m != nil && m.Typ != nil {
		return *m.Typ
	}
	return 0
}

func (m *ShopDiscountInfo) GetStartTime() int64 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *ShopDiscountInfo) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

type CSShopDiscountGet struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSShopDiscountGet) Reset()                    { *m = CSShopDiscountGet{} }
func (m *CSShopDiscountGet) String() string            { return proto.CompactTextString(m) }
func (*CSShopDiscountGet) ProtoMessage()               {}
func (*CSShopDiscountGet) Descriptor() ([]byte, []int) { return fileDescriptor104, []int{1} }

type SCShopDiscountGet struct {
	Info             *ShopDiscountInfo `protobuf:"bytes,1,req,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *SCShopDiscountGet) Reset()                    { *m = SCShopDiscountGet{} }
func (m *SCShopDiscountGet) String() string            { return proto.CompactTextString(m) }
func (*SCShopDiscountGet) ProtoMessage()               {}
func (*SCShopDiscountGet) Descriptor() ([]byte, []int) { return fileDescriptor104, []int{2} }

func (m *SCShopDiscountGet) GetInfo() *ShopDiscountInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type SCShopDiscountNotice struct {
	Info             *ShopDiscountInfo `protobuf:"bytes,1,req,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *SCShopDiscountNotice) Reset()                    { *m = SCShopDiscountNotice{} }
func (m *SCShopDiscountNotice) String() string            { return proto.CompactTextString(m) }
func (*SCShopDiscountNotice) ProtoMessage()               {}
func (*SCShopDiscountNotice) Descriptor() ([]byte, []int) { return fileDescriptor104, []int{3} }

func (m *SCShopDiscountNotice) GetInfo() *ShopDiscountInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterType((*ShopDiscountInfo)(nil), "ui.ShopDiscountInfo")
	proto.RegisterType((*CSShopDiscountGet)(nil), "ui.CSShopDiscountGet")
	proto.RegisterType((*SCShopDiscountGet)(nil), "ui.SCShopDiscountGet")
	proto.RegisterType((*SCShopDiscountNotice)(nil), "ui.SCShopDiscountNotice")
}

func init() { proto.RegisterFile("shopdiscount.proto", fileDescriptor104) }

var fileDescriptor104 = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0xce, 0xc8, 0x2f,
	0x48, 0xc9, 0x2c, 0x4e, 0xce, 0x2f, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x2a, 0xcd, 0x54, 0x72, 0xe6, 0x12, 0x08, 0xce, 0xc8, 0x2f, 0x70, 0x81, 0xca, 0x78, 0xe6, 0xa5,
	0xe5, 0x0b, 0x71, 0x73, 0x31, 0x97, 0x54, 0x16, 0x48, 0x30, 0x2a, 0x30, 0x69, 0xb0, 0x0a, 0x09,
	0x72, 0x71, 0x16, 0x97, 0x24, 0x16, 0x95, 0x84, 0x64, 0xe6, 0xa6, 0x4a, 0x30, 0x29, 0x30, 0x69,
	0x30, 0x0b, 0xf1, 0x73, 0xb1, 0xa7, 0xe6, 0xa5, 0x80, 0x05, 0x98, 0x41, 0x02, 0x4a, 0xc2, 0x5c,
	0x82, 0xce, 0xc1, 0xc8, 0xc6, 0xb8, 0xa7, 0x96, 0x28, 0x99, 0x73, 0x09, 0x06, 0x3b, 0xa3, 0x09,
	0x0a, 0x29, 0x71, 0xb1, 0x64, 0xe6, 0xa5, 0xe5, 0x83, 0xcd, 0xe6, 0x36, 0x12, 0xd1, 0x2b, 0xcd,
	0xd4, 0x43, 0xb7, 0x5e, 0xc9, 0x8a, 0x4b, 0x04, 0x55, 0xa3, 0x5f, 0x7e, 0x49, 0x66, 0x72, 0x2a,
	0x31, 0x7a, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3b, 0xed, 0xf7, 0x53, 0xe7, 0x00, 0x00, 0x00,
}
