// Code generated by protoc-gen-go. DO NOT EDIT.
// source: skill.proto

package ui

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type TianFuInfo struct {
	TianFuId         *int32 `protobuf:"varint,1,req,name=tianFuId" json:"tianFuId,omitempty"`
	Level            *int32 `protobuf:"varint,2,req,name=level" json:"level,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *TianFuInfo) Reset()                    { *m = TianFuInfo{} }
func (m *TianFuInfo) String() string            { return proto.CompactTextString(m) }
func (*TianFuInfo) ProtoMessage()               {}
func (*TianFuInfo) Descriptor() ([]byte, []int) { return fileDescriptor105, []int{0} }

func (m *TianFuInfo) GetTianFuId() int32 {
	if m != nil && m.TianFuId != nil {
		return *m.TianFuId
	}
	return 0
}

func (m *TianFuInfo) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

type SkillTianFuInfo struct {
	SkillId          *int32        `protobuf:"varint,1,req,name=skillId" json:"skillId,omitempty"`
	TianFuList       []*TianFuInfo `protobuf:"bytes,2,rep,name=tianFuList" json:"tianFuList,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *SkillTianFuInfo) Reset()                    { *m = SkillTianFuInfo{} }
func (m *SkillTianFuInfo) String() string            { return proto.CompactTextString(m) }
func (*SkillTianFuInfo) ProtoMessage()               {}
func (*SkillTianFuInfo) Descriptor() ([]byte, []int) { return fileDescriptor105, []int{1} }

func (m *SkillTianFuInfo) GetSkillId() int32 {
	if m != nil && m.SkillId != nil {
		return *m.SkillId
	}
	return 0
}

func (m *SkillTianFuInfo) GetTianFuList() []*TianFuInfo {
	if m != nil {
		return m.TianFuList
	}
	return nil
}

type SkillCdInfo struct {
	SkillId          *int32 `protobuf:"varint,1,req,name=skillId" json:"skillId,omitempty"`
	LastTime         *int64 `protobuf:"varint,2,req,name=lastTime" json:"lastTime,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SkillCdInfo) Reset()                    { *m = SkillCdInfo{} }
func (m *SkillCdInfo) String() string            { return proto.CompactTextString(m) }
func (*SkillCdInfo) ProtoMessage()               {}
func (*SkillCdInfo) Descriptor() ([]byte, []int) { return fileDescriptor105, []int{2} }

func (m *SkillCdInfo) GetSkillId() int32 {
	if m != nil && m.SkillId != nil {
		return *m.SkillId
	}
	return 0
}

func (m *SkillCdInfo) GetLastTime() int64 {
	if m != nil && m.LastTime != nil {
		return *m.LastTime
	}
	return 0
}

type SkillInfo struct {
	SkillId          *int32 `protobuf:"varint,1,req,name=skillId" json:"skillId,omitempty"`
	Level            *int32 `protobuf:"varint,2,req,name=level" json:"level,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SkillInfo) Reset()                    { *m = SkillInfo{} }
func (m *SkillInfo) String() string            { return proto.CompactTextString(m) }
func (*SkillInfo) ProtoMessage()               {}
func (*SkillInfo) Descriptor() ([]byte, []int) { return fileDescriptor105, []int{3} }

func (m *SkillInfo) GetSkillId() int32 {
	if m != nil && m.SkillId != nil {
		return *m.SkillId
	}
	return 0
}

func (m *SkillInfo) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

type SCSkillGet struct {
	SkillList        []*SkillInfo `protobuf:"bytes,1,rep,name=skillList" json:"skillList,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *SCSkillGet) Reset()                    { *m = SCSkillGet{} }
func (m *SCSkillGet) String() string            { return proto.CompactTextString(m) }
func (*SCSkillGet) ProtoMessage()               {}
func (*SCSkillGet) Descriptor() ([]byte, []int) { return fileDescriptor105, []int{4} }

func (m *SCSkillGet) GetSkillList() []*SkillInfo {
	if m != nil {
		return m.SkillList
	}
	return nil
}

type SCSkillAdd struct {
	SkillId          *int32 `protobuf:"varint,1,req,name=skillId" json:"skillId,omitempty"`
	Level            *int32 `protobuf:"varint,2,req,name=level" json:"level,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCSkillAdd) Reset()                    { *m = SCSkillAdd{} }
func (m *SCSkillAdd) String() string            { return proto.CompactTextString(m) }
func (*SCSkillAdd) ProtoMessage()               {}
func (*SCSkillAdd) Descriptor() ([]byte, []int) { return fileDescriptor105, []int{5} }

func (m *SCSkillAdd) GetSkillId() int32 {
	if m != nil && m.SkillId != nil {
		return *m.SkillId
	}
	return 0
}

func (m *SCSkillAdd) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

type CSSkillUpgrade struct {
	SkillId          *int32 `protobuf:"varint,1,req,name=skillId" json:"skillId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSSkillUpgrade) Reset()                    { *m = CSSkillUpgrade{} }
func (m *CSSkillUpgrade) String() string            { return proto.CompactTextString(m) }
func (*CSSkillUpgrade) ProtoMessage()               {}
func (*CSSkillUpgrade) Descriptor() ([]byte, []int) { return fileDescriptor105, []int{6} }

func (m *CSSkillUpgrade) GetSkillId() int32 {
	if m != nil && m.SkillId != nil {
		return *m.SkillId
	}
	return 0
}

type SCSkillUpgrade struct {
	OldSkillId       *int32 `protobuf:"varint,1,req,name=oldSkillId" json:"oldSkillId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCSkillUpgrade) Reset()                    { *m = SCSkillUpgrade{} }
func (m *SCSkillUpgrade) String() string            { return proto.CompactTextString(m) }
func (*SCSkillUpgrade) ProtoMessage()               {}
func (*SCSkillUpgrade) Descriptor() ([]byte, []int) { return fileDescriptor105, []int{7} }

func (m *SCSkillUpgrade) GetOldSkillId() int32 {
	if m != nil && m.OldSkillId != nil {
		return *m.OldSkillId
	}
	return 0
}

type CSSkillUpgradeAll struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSSkillUpgradeAll) Reset()                    { *m = CSSkillUpgradeAll{} }
func (m *CSSkillUpgradeAll) String() string            { return proto.CompactTextString(m) }
func (*CSSkillUpgradeAll) ProtoMessage()               {}
func (*CSSkillUpgradeAll) Descriptor() ([]byte, []int) { return fileDescriptor105, []int{8} }

type SCSkillUpgradeAll struct {
	OldSkillIdList   []int32 `protobuf:"varint,1,rep,name=oldSkillIdList" json:"oldSkillIdList,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SCSkillUpgradeAll) Reset()                    { *m = SCSkillUpgradeAll{} }
func (m *SCSkillUpgradeAll) String() string            { return proto.CompactTextString(m) }
func (*SCSkillUpgradeAll) ProtoMessage()               {}
func (*SCSkillUpgradeAll) Descriptor() ([]byte, []int) { return fileDescriptor105, []int{9} }

func (m *SCSkillUpgradeAll) GetOldSkillIdList() []int32 {
	if m != nil {
		return m.OldSkillIdList
	}
	return nil
}

type SCSkillRemove struct {
	SkillId          *int32 `protobuf:"varint,1,req,name=skillId" json:"skillId,omitempty"`
	Level            *int32 `protobuf:"varint,2,req,name=level" json:"level,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCSkillRemove) Reset()                    { *m = SCSkillRemove{} }
func (m *SCSkillRemove) String() string            { return proto.CompactTextString(m) }
func (*SCSkillRemove) ProtoMessage()               {}
func (*SCSkillRemove) Descriptor() ([]byte, []int) { return fileDescriptor105, []int{10} }

func (m *SCSkillRemove) GetSkillId() int32 {
	if m != nil && m.SkillId != nil {
		return *m.SkillId
	}
	return 0
}

func (m *SCSkillRemove) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

type SCSkillCdTime struct {
	SkillCdList      []*SkillCdInfo `protobuf:"bytes,1,rep,name=skillCdList" json:"skillCdList,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *SCSkillCdTime) Reset()                    { *m = SCSkillCdTime{} }
func (m *SCSkillCdTime) String() string            { return proto.CompactTextString(m) }
func (*SCSkillCdTime) ProtoMessage()               {}
func (*SCSkillCdTime) Descriptor() ([]byte, []int) { return fileDescriptor105, []int{11} }

func (m *SCSkillCdTime) GetSkillCdList() []*SkillCdInfo {
	if m != nil {
		return m.SkillCdList
	}
	return nil
}

type SCSkillLearn struct {
	SkillId          *int32 `protobuf:"varint,1,req,name=skillId" json:"skillId,omitempty"`
	Level            *int32 `protobuf:"varint,2,req,name=level" json:"level,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCSkillLearn) Reset()                    { *m = SCSkillLearn{} }
func (m *SCSkillLearn) String() string            { return proto.CompactTextString(m) }
func (*SCSkillLearn) ProtoMessage()               {}
func (*SCSkillLearn) Descriptor() ([]byte, []int) { return fileDescriptor105, []int{12} }

func (m *SCSkillLearn) GetSkillId() int32 {
	if m != nil && m.SkillId != nil {
		return *m.SkillId
	}
	return 0
}

func (m *SCSkillLearn) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

type CSSkillTianFuAwaken struct {
	SkillId          *int32 `protobuf:"varint,1,req,name=skillId" json:"skillId,omitempty"`
	TianFuId         *int32 `protobuf:"varint,2,req,name=tianFuId" json:"tianFuId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSSkillTianFuAwaken) Reset()                    { *m = CSSkillTianFuAwaken{} }
func (m *CSSkillTianFuAwaken) String() string            { return proto.CompactTextString(m) }
func (*CSSkillTianFuAwaken) ProtoMessage()               {}
func (*CSSkillTianFuAwaken) Descriptor() ([]byte, []int) { return fileDescriptor105, []int{13} }

func (m *CSSkillTianFuAwaken) GetSkillId() int32 {
	if m != nil && m.SkillId != nil {
		return *m.SkillId
	}
	return 0
}

func (m *CSSkillTianFuAwaken) GetTianFuId() int32 {
	if m != nil && m.TianFuId != nil {
		return *m.TianFuId
	}
	return 0
}

type SCSkillTianFuAwaken struct {
	SkillId          *int32      `protobuf:"varint,1,req,name=skillId" json:"skillId,omitempty"`
	TianFuInfo       *TianFuInfo `protobuf:"bytes,2,req,name=tianFuInfo" json:"tianFuInfo,omitempty"`
	Sucess           *bool       `protobuf:"varint,3,req,name=sucess" json:"sucess,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *SCSkillTianFuAwaken) Reset()                    { *m = SCSkillTianFuAwaken{} }
func (m *SCSkillTianFuAwaken) String() string            { return proto.CompactTextString(m) }
func (*SCSkillTianFuAwaken) ProtoMessage()               {}
func (*SCSkillTianFuAwaken) Descriptor() ([]byte, []int) { return fileDescriptor105, []int{14} }

func (m *SCSkillTianFuAwaken) GetSkillId() int32 {
	if m != nil && m.SkillId != nil {
		return *m.SkillId
	}
	return 0
}

func (m *SCSkillTianFuAwaken) GetTianFuInfo() *TianFuInfo {
	if m != nil {
		return m.TianFuInfo
	}
	return nil
}

func (m *SCSkillTianFuAwaken) GetSucess() bool {
	if m != nil && m.Sucess != nil {
		return *m.Sucess
	}
	return false
}

type CSSkillTianFuUpgrade struct {
	SkillId          *int32 `protobuf:"varint,1,req,name=skillId" json:"skillId,omitempty"`
	TianFuId         *int32 `protobuf:"varint,2,req,name=tianFuId" json:"tianFuId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSSkillTianFuUpgrade) Reset()                    { *m = CSSkillTianFuUpgrade{} }
func (m *CSSkillTianFuUpgrade) String() string            { return proto.CompactTextString(m) }
func (*CSSkillTianFuUpgrade) ProtoMessage()               {}
func (*CSSkillTianFuUpgrade) Descriptor() ([]byte, []int) { return fileDescriptor105, []int{15} }

func (m *CSSkillTianFuUpgrade) GetSkillId() int32 {
	if m != nil && m.SkillId != nil {
		return *m.SkillId
	}
	return 0
}

func (m *CSSkillTianFuUpgrade) GetTianFuId() int32 {
	if m != nil && m.TianFuId != nil {
		return *m.TianFuId
	}
	return 0
}

type SCSkillTianFuUpgrade struct {
	SkillId          *int32      `protobuf:"varint,1,req,name=skillId" json:"skillId,omitempty"`
	TianFuInfo       *TianFuInfo `protobuf:"bytes,2,req,name=tianFuInfo" json:"tianFuInfo,omitempty"`
	Sucess           *bool       `protobuf:"varint,3,req,name=sucess" json:"sucess,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *SCSkillTianFuUpgrade) Reset()                    { *m = SCSkillTianFuUpgrade{} }
func (m *SCSkillTianFuUpgrade) String() string            { return proto.CompactTextString(m) }
func (*SCSkillTianFuUpgrade) ProtoMessage()               {}
func (*SCSkillTianFuUpgrade) Descriptor() ([]byte, []int) { return fileDescriptor105, []int{16} }

func (m *SCSkillTianFuUpgrade) GetSkillId() int32 {
	if m != nil && m.SkillId != nil {
		return *m.SkillId
	}
	return 0
}

func (m *SCSkillTianFuUpgrade) GetTianFuInfo() *TianFuInfo {
	if m != nil {
		return m.TianFuInfo
	}
	return nil
}

func (m *SCSkillTianFuUpgrade) GetSucess() bool {
	if m != nil && m.Sucess != nil {
		return *m.Sucess
	}
	return false
}

type SCSkillTianFuGet struct {
	SkillTianFuList  []*SkillTianFuInfo `protobuf:"bytes,1,rep,name=skillTianFuList" json:"skillTianFuList,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *SCSkillTianFuGet) Reset()                    { *m = SCSkillTianFuGet{} }
func (m *SCSkillTianFuGet) String() string            { return proto.CompactTextString(m) }
func (*SCSkillTianFuGet) ProtoMessage()               {}
func (*SCSkillTianFuGet) Descriptor() ([]byte, []int) { return fileDescriptor105, []int{17} }

func (m *SCSkillTianFuGet) GetSkillTianFuList() []*SkillTianFuInfo {
	if m != nil {
		return m.SkillTianFuList
	}
	return nil
}

func init() {
	proto.RegisterType((*TianFuInfo)(nil), "ui.TianFuInfo")
	proto.RegisterType((*SkillTianFuInfo)(nil), "ui.SkillTianFuInfo")
	proto.RegisterType((*SkillCdInfo)(nil), "ui.SkillCdInfo")
	proto.RegisterType((*SkillInfo)(nil), "ui.SkillInfo")
	proto.RegisterType((*SCSkillGet)(nil), "ui.SCSkillGet")
	proto.RegisterType((*SCSkillAdd)(nil), "ui.SCSkillAdd")
	proto.RegisterType((*CSSkillUpgrade)(nil), "ui.CSSkillUpgrade")
	proto.RegisterType((*SCSkillUpgrade)(nil), "ui.SCSkillUpgrade")
	proto.RegisterType((*CSSkillUpgradeAll)(nil), "ui.CSSkillUpgradeAll")
	proto.RegisterType((*SCSkillUpgradeAll)(nil), "ui.SCSkillUpgradeAll")
	proto.RegisterType((*SCSkillRemove)(nil), "ui.SCSkillRemove")
	proto.RegisterType((*SCSkillCdTime)(nil), "ui.SCSkillCdTime")
	proto.RegisterType((*SCSkillLearn)(nil), "ui.SCSkillLearn")
	proto.RegisterType((*CSSkillTianFuAwaken)(nil), "ui.CSSkillTianFuAwaken")
	proto.RegisterType((*SCSkillTianFuAwaken)(nil), "ui.SCSkillTianFuAwaken")
	proto.RegisterType((*CSSkillTianFuUpgrade)(nil), "ui.CSSkillTianFuUpgrade")
	proto.RegisterType((*SCSkillTianFuUpgrade)(nil), "ui.SCSkillTianFuUpgrade")
	proto.RegisterType((*SCSkillTianFuGet)(nil), "ui.SCSkillTianFuGet")
}

func init() { proto.RegisterFile("skill.proto", fileDescriptor105) }

var fileDescriptor105 = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xc1, 0x6b, 0xe2, 0x40,
	0x18, 0xc5, 0x31, 0xe2, 0xae, 0x3e, 0xd7, 0x44, 0x27, 0xb2, 0xe4, 0x98, 0x1d, 0x3c, 0x08, 0xba,
	0xd9, 0xa5, 0x50, 0x68, 0x6f, 0x0d, 0x01, 0x4b, 0xc1, 0x53, 0x63, 0x2f, 0xed, 0x29, 0x74, 0xa6,
	0x25, 0x38, 0x26, 0x62, 0x12, 0xfb, 0xef, 0x97, 0x4c, 0xd2, 0x89, 0xa9, 0xb1, 0x42, 0x8f, 0x09,
	0xef, 0xf7, 0xbe, 0x37, 0xdf, 0xfb, 0xd0, 0x4f, 0xd6, 0xa1, 0x10, 0xce, 0x76, 0x17, 0xa7, 0x31,
	0xd1, 0xb2, 0x90, 0xfe, 0x05, 0x56, 0x61, 0x10, 0x2d, 0xb2, 0xbb, 0xe8, 0x25, 0x26, 0x43, 0x74,
	0xd3, 0xe2, 0x8b, 0x59, 0x2d, 0x5b, 0x9b, 0x76, 0xc8, 0x00, 0x1d, 0xc1, 0xf7, 0x5c, 0x58, 0x5a,
	0xfe, 0x49, 0x17, 0x30, 0xfc, 0xdc, 0xe1, 0x80, 0x31, 0xf0, 0x53, 0x9a, 0x2a, 0x84, 0x02, 0x85,
	0xc9, 0x32, 0x4c, 0x52, 0x4b, 0xb3, 0xdb, 0xd3, 0xfe, 0x85, 0xee, 0x64, 0xa1, 0x53, 0x41, 0xf4,
	0x3f, 0xfa, 0xd2, 0xc7, 0x63, 0xcd, 0x1e, 0x43, 0x74, 0x45, 0x90, 0xa4, 0xab, 0x70, 0xc3, 0xe5,
	0xe4, 0x36, 0x9d, 0xa1, 0x27, 0x89, 0x66, 0xfd, 0xa7, 0x98, 0x0e, 0xe0, 0x7b, 0x52, 0x7e, 0xcb,
	0x53, 0x62, 0xa3, 0x27, 0xd5, 0x32, 0x4f, 0x4b, 0xe6, 0x19, 0xe4, 0x79, 0x94, 0x1f, 0x9d, 0x2b,
	0xbd, 0xcb, 0xd8, 0x59, 0xf7, 0x3f, 0xd0, 0x3d, 0x5f, 0xaa, 0x1f, 0xb6, 0xaf, 0xbb, 0x80, 0xf1,
	0x23, 0x82, 0x4e, 0xa0, 0x97, 0x86, 0x1f, 0x12, 0x02, 0xc4, 0x82, 0xf9, 0x35, 0x95, 0x89, 0x51,
	0xdd, 0xc8, 0x15, 0x82, 0xce, 0x30, 0xaa, 0xa3, 0xae, 0x10, 0xe4, 0x37, 0xf4, 0x8a, 0x56, 0xef,
	0xe8, 0xd0, 0x7f, 0x18, 0x94, 0xe2, 0x7b, 0xbe, 0x89, 0xf7, 0xfc, 0x6c, 0xf6, 0x4b, 0x05, 0x78,
	0x2c, 0xdf, 0x2e, 0x99, 0x94, 0x37, 0xe1, 0xb1, 0x83, 0xf5, 0x18, 0x6a, 0x3d, 0x45, 0x41, 0xd4,
	0xc1, 0xaf, 0x12, 0x5b, 0xf2, 0x60, 0x17, 0x9d, 0x1d, 0x73, 0x05, 0xb3, 0x7c, 0x59, 0x51, 0xba,
	0xfb, 0x16, 0xac, 0x79, 0xd4, 0xd8, 0xb3, 0x3a, 0xb8, 0x82, 0x7c, 0x84, 0x59, 0x4e, 0xfa, 0x9a,
	0x54, 0x57, 0x96, 0xe7, 0x93, 0xec, 0xd1, 0x95, 0x11, 0x1d, 0x3f, 0x92, 0xec, 0x99, 0x27, 0x89,
	0xd5, 0xb6, 0xb5, 0x69, 0x97, 0x5e, 0x63, 0x5c, 0x4b, 0x75, 0xaa, 0xbe, 0x86, 0x58, 0x4f, 0x18,
	0xd7, 0x62, 0x9d, 0x44, 0xbf, 0x93, 0xeb, 0x06, 0xc3, 0x9a, 0x79, 0x7e, 0xb4, 0x73, 0x18, 0x49,
	0xf5, 0xe7, 0xa0, 0x1b, 0x53, 0x75, 0x53, 0x39, 0xbe, 0x07, 0x00, 0x00, 0xff, 0xff, 0xf3, 0x53,
	0x6a, 0xd6, 0xd8, 0x03, 0x00, 0x00,
}
