// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transportation.proto

package ui

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CSPersonalTransportation struct {
	Typ              *int32 `protobuf:"varint,1,req,name=typ" json:"typ,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSPersonalTransportation) Reset()                    { *m = CSPersonalTransportation{} }
func (m *CSPersonalTransportation) String() string            { return proto.CompactTextString(m) }
func (*CSPersonalTransportation) ProtoMessage()               {}
func (*CSPersonalTransportation) Descriptor() ([]byte, []int) { return fileDescriptor119, []int{0} }

func (m *CSPersonalTransportation) GetTyp() int32 {
	if m != nil && m.Typ != nil {
		return *m.Typ
	}
	return 0
}

type SCPersonalTransportation struct {
	StartTime        *int64 `protobuf:"varint,1,req,name=startTime" json:"startTime,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCPersonalTransportation) Reset()                    { *m = SCPersonalTransportation{} }
func (m *SCPersonalTransportation) String() string            { return proto.CompactTextString(m) }
func (*SCPersonalTransportation) ProtoMessage()               {}
func (*SCPersonalTransportation) Descriptor() ([]byte, []int) { return fileDescriptor119, []int{1} }

func (m *SCPersonalTransportation) GetStartTime() int64 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

type CSAllianceTransportation struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSAllianceTransportation) Reset()                    { *m = CSAllianceTransportation{} }
func (m *CSAllianceTransportation) String() string            { return proto.CompactTextString(m) }
func (*CSAllianceTransportation) ProtoMessage()               {}
func (*CSAllianceTransportation) Descriptor() ([]byte, []int) { return fileDescriptor119, []int{2} }

type SCAllianceTransportation struct {
	StartTime        *int64 `protobuf:"varint,1,req,name=startTime" json:"startTime,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCAllianceTransportation) Reset()                    { *m = SCAllianceTransportation{} }
func (m *SCAllianceTransportation) String() string            { return proto.CompactTextString(m) }
func (*SCAllianceTransportation) ProtoMessage()               {}
func (*SCAllianceTransportation) Descriptor() ([]byte, []int) { return fileDescriptor119, []int{3} }

func (m *SCAllianceTransportation) GetStartTime() int64 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

type CSDistressSignal struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSDistressSignal) Reset()                    { *m = CSDistressSignal{} }
func (m *CSDistressSignal) String() string            { return proto.CompactTextString(m) }
func (*CSDistressSignal) ProtoMessage()               {}
func (*CSDistressSignal) Descriptor() ([]byte, []int) { return fileDescriptor119, []int{4} }

type SCDistressSignal struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCDistressSignal) Reset()                    { *m = SCDistressSignal{} }
func (m *SCDistressSignal) String() string            { return proto.CompactTextString(m) }
func (*SCDistressSignal) ProtoMessage()               {}
func (*SCDistressSignal) Descriptor() ([]byte, []int) { return fileDescriptor119, []int{5} }

type SCDistressSignalBroadcast struct {
	TargetId         *int64 `protobuf:"varint,1,req,name=targetId" json:"targetId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCDistressSignalBroadcast) Reset()                    { *m = SCDistressSignalBroadcast{} }
func (m *SCDistressSignalBroadcast) String() string            { return proto.CompactTextString(m) }
func (*SCDistressSignalBroadcast) ProtoMessage()               {}
func (*SCDistressSignalBroadcast) Descriptor() ([]byte, []int) { return fileDescriptor119, []int{6} }

func (m *SCDistressSignalBroadcast) GetTargetId() int64 {
	if m != nil && m.TargetId != nil {
		return *m.TargetId
	}
	return 0
}

type CSAgreeDistressSignal struct {
	TargetId         *int64 `protobuf:"varint,2,req,name=targetId" json:"targetId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSAgreeDistressSignal) Reset()                    { *m = CSAgreeDistressSignal{} }
func (m *CSAgreeDistressSignal) String() string            { return proto.CompactTextString(m) }
func (*CSAgreeDistressSignal) ProtoMessage()               {}
func (*CSAgreeDistressSignal) Descriptor() ([]byte, []int) { return fileDescriptor119, []int{7} }

func (m *CSAgreeDistressSignal) GetTargetId() int64 {
	if m != nil && m.TargetId != nil {
		return *m.TargetId
	}
	return 0
}

type SCAgreeDistressSignal struct {
	TargetPosition   *Position `protobuf:"bytes,1,req,name=targetPosition" json:"targetPosition,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *SCAgreeDistressSignal) Reset()                    { *m = SCAgreeDistressSignal{} }
func (m *SCAgreeDistressSignal) String() string            { return proto.CompactTextString(m) }
func (*SCAgreeDistressSignal) ProtoMessage()               {}
func (*SCAgreeDistressSignal) Descriptor() ([]byte, []int) { return fileDescriptor119, []int{8} }

func (m *SCAgreeDistressSignal) GetTargetPosition() *Position {
	if m != nil {
		return m.TargetPosition
	}
	return nil
}

type CSPlayerTransportInfo struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSPlayerTransportInfo) Reset()                    { *m = CSPlayerTransportInfo{} }
func (m *CSPlayerTransportInfo) String() string            { return proto.CompactTextString(m) }
func (*CSPlayerTransportInfo) ProtoMessage()               {}
func (*CSPlayerTransportInfo) Descriptor() ([]byte, []int) { return fileDescriptor119, []int{9} }

type SCPlayerTransportInfo struct {
	PersonalTransportTimes *int32 `protobuf:"varint,1,req,name=personalTransportTimes" json:"personalTransportTimes,omitempty"`
	AllianceTransportTimes *int32 `protobuf:"varint,2,req,name=allianceTransportTimes" json:"allianceTransportTimes,omitempty"`
	XXX_unrecognized       []byte `json:"-"`
}

func (m *SCPlayerTransportInfo) Reset()                    { *m = SCPlayerTransportInfo{} }
func (m *SCPlayerTransportInfo) String() string            { return proto.CompactTextString(m) }
func (*SCPlayerTransportInfo) ProtoMessage()               {}
func (*SCPlayerTransportInfo) Descriptor() ([]byte, []int) { return fileDescriptor119, []int{10} }

func (m *SCPlayerTransportInfo) GetPersonalTransportTimes() int32 {
	if m != nil && m.PersonalTransportTimes != nil {
		return *m.PersonalTransportTimes
	}
	return 0
}

func (m *SCPlayerTransportInfo) GetAllianceTransportTimes() int32 {
	if m != nil && m.AllianceTransportTimes != nil {
		return *m.AllianceTransportTimes
	}
	return 0
}

type SCTransportationProtectNotice struct {
	TargetPosition   *Position `protobuf:"bytes,1,req,name=targetPosition" json:"targetPosition,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *SCTransportationProtectNotice) Reset()         { *m = SCTransportationProtectNotice{} }
func (m *SCTransportationProtectNotice) String() string { return proto.CompactTextString(m) }
func (*SCTransportationProtectNotice) ProtoMessage()    {}
func (*SCTransportationProtectNotice) Descriptor() ([]byte, []int) {
	return fileDescriptor119, []int{11}
}

func (m *SCTransportationProtectNotice) GetTargetPosition() *Position {
	if m != nil {
		return m.TargetPosition
	}
	return nil
}

type CSTransportationProtect struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSTransportationProtect) Reset()                    { *m = CSTransportationProtect{} }
func (m *CSTransportationProtect) String() string            { return proto.CompactTextString(m) }
func (*CSTransportationProtect) ProtoMessage()               {}
func (*CSTransportationProtect) Descriptor() ([]byte, []int) { return fileDescriptor119, []int{12} }

type SCTransportationProtect struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCTransportationProtect) Reset()                    { *m = SCTransportationProtect{} }
func (m *SCTransportationProtect) String() string            { return proto.CompactTextString(m) }
func (*SCTransportationProtect) ProtoMessage()               {}
func (*SCTransportationProtect) Descriptor() ([]byte, []int) { return fileDescriptor119, []int{13} }

type SCTransportBriefInfoNotice struct {
	RobName          *string   `protobuf:"bytes,1,req,name=robName" json:"robName,omitempty"`
	State            *int32    `protobuf:"varint,2,req,name=state" json:"state,omitempty"`
	TransportType    *int32    `protobuf:"varint,3,req,name=transportType" json:"transportType,omitempty"`
	TargetPosition   *Position `protobuf:"bytes,4,req,name=targetPosition" json:"targetPosition,omitempty"`
	MoveId           *int32    `protobuf:"varint,5,req,name=moveId" json:"moveId,omitempty"`
	StartTime        *int64    `protobuf:"varint,6,req,name=startTime" json:"startTime,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *SCTransportBriefInfoNotice) Reset()                    { *m = SCTransportBriefInfoNotice{} }
func (m *SCTransportBriefInfoNotice) String() string            { return proto.CompactTextString(m) }
func (*SCTransportBriefInfoNotice) ProtoMessage()               {}
func (*SCTransportBriefInfoNotice) Descriptor() ([]byte, []int) { return fileDescriptor119, []int{14} }

func (m *SCTransportBriefInfoNotice) GetRobName() string {
	if m != nil && m.RobName != nil {
		return *m.RobName
	}
	return ""
}

func (m *SCTransportBriefInfoNotice) GetState() int32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

func (m *SCTransportBriefInfoNotice) GetTransportType() int32 {
	if m != nil && m.TransportType != nil {
		return *m.TransportType
	}
	return 0
}

func (m *SCTransportBriefInfoNotice) GetTargetPosition() *Position {
	if m != nil {
		return m.TargetPosition
	}
	return nil
}

func (m *SCTransportBriefInfoNotice) GetMoveId() int32 {
	if m != nil && m.MoveId != nil {
		return *m.MoveId
	}
	return 0
}

func (m *SCTransportBriefInfoNotice) GetStartTime() int64 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

type CSReceiveTransportRew struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSReceiveTransportRew) Reset()                    { *m = CSReceiveTransportRew{} }
func (m *CSReceiveTransportRew) String() string            { return proto.CompactTextString(m) }
func (*CSReceiveTransportRew) ProtoMessage()               {}
func (*CSReceiveTransportRew) Descriptor() ([]byte, []int) { return fileDescriptor119, []int{15} }

type SCReceiveTransportRew struct {
	RewGold          *int32 `protobuf:"varint,1,req,name=rewGold" json:"rewGold,omitempty"`
	RewSilver        *int32 `protobuf:"varint,2,req,name=rewSilver" json:"rewSilver,omitempty"`
	TransportType    *int32 `protobuf:"varint,3,req,name=transportType" json:"transportType,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCReceiveTransportRew) Reset()                    { *m = SCReceiveTransportRew{} }
func (m *SCReceiveTransportRew) String() string            { return proto.CompactTextString(m) }
func (*SCReceiveTransportRew) ProtoMessage()               {}
func (*SCReceiveTransportRew) Descriptor() ([]byte, []int) { return fileDescriptor119, []int{16} }

func (m *SCReceiveTransportRew) GetRewGold() int32 {
	if m != nil && m.RewGold != nil {
		return *m.RewGold
	}
	return 0
}

func (m *SCReceiveTransportRew) GetRewSilver() int32 {
	if m != nil && m.RewSilver != nil {
		return *m.RewSilver
	}
	return 0
}

func (m *SCReceiveTransportRew) GetTransportType() int32 {
	if m != nil && m.TransportType != nil {
		return *m.TransportType
	}
	return 0
}

type SCRobSuccessNotice struct {
	RewGold          *int32 `protobuf:"varint,1,req,name=rewGold" json:"rewGold,omitempty"`
	RewSilver        *int32 `protobuf:"varint,2,req,name=rewSilver" json:"rewSilver,omitempty"`
	TransportType    *int32 `protobuf:"varint,3,req,name=transportType" json:"transportType,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCRobSuccessNotice) Reset()                    { *m = SCRobSuccessNotice{} }
func (m *SCRobSuccessNotice) String() string            { return proto.CompactTextString(m) }
func (*SCRobSuccessNotice) ProtoMessage()               {}
func (*SCRobSuccessNotice) Descriptor() ([]byte, []int) { return fileDescriptor119, []int{17} }

func (m *SCRobSuccessNotice) GetRewGold() int32 {
	if m != nil && m.RewGold != nil {
		return *m.RewGold
	}
	return 0
}

func (m *SCRobSuccessNotice) GetRewSilver() int32 {
	if m != nil && m.RewSilver != nil {
		return *m.RewSilver
	}
	return 0
}

func (m *SCRobSuccessNotice) GetTransportType() int32 {
	if m != nil && m.TransportType != nil {
		return *m.TransportType
	}
	return 0
}

func init() {
	proto.RegisterType((*CSPersonalTransportation)(nil), "ui.CSPersonalTransportation")
	proto.RegisterType((*SCPersonalTransportation)(nil), "ui.SCPersonalTransportation")
	proto.RegisterType((*CSAllianceTransportation)(nil), "ui.CSAllianceTransportation")
	proto.RegisterType((*SCAllianceTransportation)(nil), "ui.SCAllianceTransportation")
	proto.RegisterType((*CSDistressSignal)(nil), "ui.CSDistressSignal")
	proto.RegisterType((*SCDistressSignal)(nil), "ui.SCDistressSignal")
	proto.RegisterType((*SCDistressSignalBroadcast)(nil), "ui.SCDistressSignalBroadcast")
	proto.RegisterType((*CSAgreeDistressSignal)(nil), "ui.CSAgreeDistressSignal")
	proto.RegisterType((*SCAgreeDistressSignal)(nil), "ui.SCAgreeDistressSignal")
	proto.RegisterType((*CSPlayerTransportInfo)(nil), "ui.CSPlayerTransportInfo")
	proto.RegisterType((*SCPlayerTransportInfo)(nil), "ui.SCPlayerTransportInfo")
	proto.RegisterType((*SCTransportationProtectNotice)(nil), "ui.SCTransportationProtectNotice")
	proto.RegisterType((*CSTransportationProtect)(nil), "ui.CSTransportationProtect")
	proto.RegisterType((*SCTransportationProtect)(nil), "ui.SCTransportationProtect")
	proto.RegisterType((*SCTransportBriefInfoNotice)(nil), "ui.SCTransportBriefInfoNotice")
	proto.RegisterType((*CSReceiveTransportRew)(nil), "ui.CSReceiveTransportRew")
	proto.RegisterType((*SCReceiveTransportRew)(nil), "ui.SCReceiveTransportRew")
	proto.RegisterType((*SCRobSuccessNotice)(nil), "ui.SCRobSuccessNotice")
}

func init() { proto.RegisterFile("transportation.proto", fileDescriptor119) }

var fileDescriptor119 = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x4d, 0x6f, 0xd3, 0x40,
	0x14, 0x54, 0x13, 0x52, 0xc8, 0xeb, 0x07, 0xed, 0x8a, 0x50, 0x37, 0x12, 0x08, 0x59, 0x48, 0xc0,
	0xa1, 0x39, 0x70, 0xe7, 0xd0, 0x2e, 0x08, 0xe5, 0x52, 0xa2, 0x6c, 0x24, 0xce, 0x5b, 0xfb, 0x35,
	0x5a, 0xc9, 0xf1, 0xb3, 0xde, 0xbe, 0x24, 0xca, 0x7f, 0xe1, 0xc7, 0xa2, 0x5d, 0xa7, 0xa5, 0x4e,
	0x5d, 0x84, 0xb8, 0x59, 0x33, 0xb3, 0xb3, 0xe3, 0x99, 0x85, 0x57, 0xc2, 0xb6, 0xf4, 0x15, 0xb1,
	0x58, 0x71, 0x54, 0x8e, 0x2a, 0x26, 0x21, 0xd5, 0x59, 0xba, 0xe1, 0x61, 0x46, 0x8b, 0xc5, 0x1d,
	0x32, 0x84, 0x9c, 0xa9, 0xaa, 0xbf, 0xd3, 0x0f, 0x90, 0x68, 0x33, 0x41, 0xf6, 0x54, 0xda, 0x62,
	0xd6, 0x38, 0xaf, 0x0e, 0xa0, 0x2b, 0x9b, 0x2a, 0xd9, 0x7b, 0xd7, 0xf9, 0xd8, 0x4b, 0x2f, 0x20,
	0x31, 0xfa, 0x09, 0xe1, 0x29, 0xf4, 0xbd, 0x58, 0x96, 0x99, 0x5b, 0x60, 0x94, 0x77, 0xd3, 0x61,
	0xf0, 0xbd, 0x2c, 0x0a, 0x67, 0xcb, 0x0c, 0x9b, 0xf2, 0xda, 0xaa, 0x9d, 0x6b, 0xb3, 0x52, 0x70,
	0xa2, 0xcd, 0x57, 0xe7, 0x85, 0xd1, 0x7b, 0xe3, 0xe6, 0xa5, 0x2d, 0x02, 0x66, 0xf4, 0x0e, 0x76,
	0x01, 0xe7, 0xbb, 0xd8, 0x15, 0x93, 0xcd, 0x33, 0xeb, 0x45, 0x9d, 0xc0, 0x0b, 0xb1, 0x3c, 0x47,
	0x19, 0xe7, 0x5b, 0xdb, 0x4f, 0x30, 0xd0, 0xe6, 0x72, 0xce, 0x88, 0xcd, 0x33, 0x0d, 0x69, 0x27,
	0x4a, 0xbf, 0xc0, 0xc0, 0xe8, 0x36, 0xe9, 0x7b, 0x38, 0xae, 0xa5, 0x13, 0xf2, 0x2e, 0xe4, 0x8f,
	0xde, 0x07, 0x9f, 0x0f, 0x47, 0x4b, 0x37, 0xba, 0xc3, 0xd2, 0xb3, 0x70, 0xd3, 0xa4, 0xb0, 0x1b,
	0xe4, 0xfb, 0xbf, 0x1d, 0x97, 0xb7, 0x94, 0xfe, 0x0c, 0xbe, 0x2d, 0x84, 0x7a, 0x0b, 0xaf, 0xab,
	0xdd, 0xaa, 0x43, 0x23, 0xbe, 0x1e, 0x23, 0xf0, 0x76, 0xb7, 0xbf, 0x9a, 0xef, 0xc4, 0xb1, 0xbe,
	0xc1, 0x1b, 0xa3, 0x9b, 0xcd, 0x4e, 0x98, 0x04, 0x33, 0xb9, 0x26, 0x71, 0x19, 0xfe, 0x63, 0xf0,
	0x73, 0x38, 0xd3, 0xa6, 0xd5, 0x26, 0x50, 0x4f, 0xdc, 0x90, 0xfe, 0xda, 0x83, 0xe1, 0x03, 0xee,
	0x8a, 0x1d, 0xde, 0x86, 0xbf, 0xda, 0x5e, 0xfd, 0x12, 0x9e, 0x33, 0xdd, 0x5c, 0xdb, 0xed, 0xbe,
	0x7d, 0x75, 0x04, 0x3d, 0x2f, 0x56, 0xb0, 0xce, 0xae, 0x06, 0x70, 0x74, 0xff, 0x8e, 0x67, 0x9b,
	0x0a, 0x93, 0x6e, 0x84, 0x1f, 0x27, 0x7e, 0xf6, 0x38, 0xb1, 0x3a, 0x86, 0xfd, 0x05, 0xad, 0x70,
	0x9c, 0x27, 0xbd, 0x78, 0xaa, 0xf1, 0x9c, 0xf6, 0xe3, 0x98, 0x71, 0x8d, 0x29, 0x66, 0xe8, 0x56,
	0x7f, 0xca, 0x9b, 0xe2, 0x3a, 0x9d, 0x86, 0x35, 0x5a, 0x88, 0x98, 0x18, 0xd7, 0xdf, 0xa9, 0xc8,
	0xb7, 0xf5, 0x9f, 0x42, 0x9f, 0x71, 0x6d, 0x5c, 0xb1, 0x42, 0xfe, 0x6b, 0xea, 0xf4, 0x07, 0x28,
	0xa3, 0xa7, 0x74, 0x63, 0x96, 0x59, 0x86, 0xde, 0x3f, 0xa8, 0xe0, 0xff, 0x0c, 0x7f, 0x07, 0x00,
	0x00, 0xff, 0xff, 0x4a, 0x26, 0xe9, 0xf3, 0xe4, 0x03, 0x00, 0x00,
}
