// Code generated by protoc-gen-go. DO NOT EDIT.
// source: xianti.proto

package ui

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type XiantiInfo struct {
	AdvancedId       *int32            `protobuf:"varint,1,req,name=advancedId" json:"advancedId,omitempty"`
	XiantiId         *int32            `protobuf:"varint,2,req,name=xiantiId" json:"xiantiId,omitempty"`
	UnrealLevel      *int32            `protobuf:"varint,3,req,name=unrealLevel" json:"unrealLevel,omitempty"`
	UnrealPro        *int32            `protobuf:"varint,4,req,name=unrealPro" json:"unrealPro,omitempty"`
	SkinList         []*XiantiSkinInfo `protobuf:"bytes,5,rep,name=skinList" json:"skinList,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *XiantiInfo) Reset()                    { *m = XiantiInfo{} }
func (m *XiantiInfo) String() string            { return proto.CompactTextString(m) }
func (*XiantiInfo) ProtoMessage()               {}
func (*XiantiInfo) Descriptor() ([]byte, []int) { return fileDescriptor135, []int{0} }

func (m *XiantiInfo) GetAdvancedId() int32 {
	if m != nil && m.AdvancedId != nil {
		return *m.AdvancedId
	}
	return 0
}

func (m *XiantiInfo) GetXiantiId() int32 {
	if m != nil && m.XiantiId != nil {
		return *m.XiantiId
	}
	return 0
}

func (m *XiantiInfo) GetUnrealLevel() int32 {
	if m != nil && m.UnrealLevel != nil {
		return *m.UnrealLevel
	}
	return 0
}

func (m *XiantiInfo) GetUnrealPro() int32 {
	if m != nil && m.UnrealPro != nil {
		return *m.UnrealPro
	}
	return 0
}

func (m *XiantiInfo) GetSkinList() []*XiantiSkinInfo {
	if m != nil {
		return m.SkinList
	}
	return nil
}

type XiantiSkinInfo struct {
	XiantiId         *int32 `protobuf:"varint,1,req,name=xiantiId" json:"xiantiId,omitempty"`
	Level            *int32 `protobuf:"varint,2,req,name=level" json:"level,omitempty"`
	Pro              *int32 `protobuf:"varint,3,req,name=pro" json:"pro,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *XiantiSkinInfo) Reset()                    { *m = XiantiSkinInfo{} }
func (m *XiantiSkinInfo) String() string            { return proto.CompactTextString(m) }
func (*XiantiSkinInfo) ProtoMessage()               {}
func (*XiantiSkinInfo) Descriptor() ([]byte, []int) { return fileDescriptor135, []int{1} }

func (m *XiantiSkinInfo) GetXiantiId() int32 {
	if m != nil && m.XiantiId != nil {
		return *m.XiantiId
	}
	return 0
}

func (m *XiantiSkinInfo) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *XiantiSkinInfo) GetPro() int32 {
	if m != nil && m.Pro != nil {
		return *m.Pro
	}
	return 0
}

type CSXiantiGet struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSXiantiGet) Reset()                    { *m = CSXiantiGet{} }
func (m *CSXiantiGet) String() string            { return proto.CompactTextString(m) }
func (*CSXiantiGet) ProtoMessage()               {}
func (*CSXiantiGet) Descriptor() ([]byte, []int) { return fileDescriptor135, []int{2} }

type SCXiantiGet struct {
	AdvancedId       *int32            `protobuf:"varint,1,req,name=advancedId" json:"advancedId,omitempty"`
	XiantiId         *int32            `protobuf:"varint,2,req,name=xiantiId" json:"xiantiId,omitempty"`
	UnrealLevel      *int32            `protobuf:"varint,3,req,name=unrealLevel" json:"unrealLevel,omitempty"`
	UnrealPro        *int32            `protobuf:"varint,4,req,name=unrealPro" json:"unrealPro,omitempty"`
	UnrealList       []int32           `protobuf:"varint,5,rep,name=unrealList" json:"unrealList,omitempty"`
	Bless            *int32            `protobuf:"varint,6,opt,name=bless" json:"bless,omitempty"`
	BlessTime        *int64            `protobuf:"varint,7,opt,name=blessTime" json:"blessTime,omitempty"`
	Hidden           *bool             `protobuf:"varint,8,req,name=hidden" json:"hidden,omitempty"`
	XiantiSkinList   []*XiantiSkinInfo `protobuf:"bytes,9,rep,name=xiantiSkinList" json:"xiantiSkinList,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *SCXiantiGet) Reset()                    { *m = SCXiantiGet{} }
func (m *SCXiantiGet) String() string            { return proto.CompactTextString(m) }
func (*SCXiantiGet) ProtoMessage()               {}
func (*SCXiantiGet) Descriptor() ([]byte, []int) { return fileDescriptor135, []int{3} }

func (m *SCXiantiGet) GetAdvancedId() int32 {
	if m != nil && m.AdvancedId != nil {
		return *m.AdvancedId
	}
	return 0
}

func (m *SCXiantiGet) GetXiantiId() int32 {
	if m != nil && m.XiantiId != nil {
		return *m.XiantiId
	}
	return 0
}

func (m *SCXiantiGet) GetUnrealLevel() int32 {
	if m != nil && m.UnrealLevel != nil {
		return *m.UnrealLevel
	}
	return 0
}

func (m *SCXiantiGet) GetUnrealPro() int32 {
	if m != nil && m.UnrealPro != nil {
		return *m.UnrealPro
	}
	return 0
}

func (m *SCXiantiGet) GetUnrealList() []int32 {
	if m != nil {
		return m.UnrealList
	}
	return nil
}

func (m *SCXiantiGet) GetBless() int32 {
	if m != nil && m.Bless != nil {
		return *m.Bless
	}
	return 0
}

func (m *SCXiantiGet) GetBlessTime() int64 {
	if m != nil && m.BlessTime != nil {
		return *m.BlessTime
	}
	return 0
}

func (m *SCXiantiGet) GetHidden() bool {
	if m != nil && m.Hidden != nil {
		return *m.Hidden
	}
	return false
}

func (m *SCXiantiGet) GetXiantiSkinList() []*XiantiSkinInfo {
	if m != nil {
		return m.XiantiSkinList
	}
	return nil
}

type CSXiantiUnrealDan struct {
	Num              *int32 `protobuf:"varint,1,req,name=num" json:"num,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSXiantiUnrealDan) Reset()                    { *m = CSXiantiUnrealDan{} }
func (m *CSXiantiUnrealDan) String() string            { return proto.CompactTextString(m) }
func (*CSXiantiUnrealDan) ProtoMessage()               {}
func (*CSXiantiUnrealDan) Descriptor() ([]byte, []int) { return fileDescriptor135, []int{4} }

func (m *CSXiantiUnrealDan) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

type SCXiantiUnrealDan struct {
	Level            *int32 `protobuf:"varint,1,req,name=level" json:"level,omitempty"`
	Progress         *int32 `protobuf:"varint,2,req,name=progress" json:"progress,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCXiantiUnrealDan) Reset()                    { *m = SCXiantiUnrealDan{} }
func (m *SCXiantiUnrealDan) String() string            { return proto.CompactTextString(m) }
func (*SCXiantiUnrealDan) ProtoMessage()               {}
func (*SCXiantiUnrealDan) Descriptor() ([]byte, []int) { return fileDescriptor135, []int{5} }

func (m *SCXiantiUnrealDan) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *SCXiantiUnrealDan) GetProgress() int32 {
	if m != nil && m.Progress != nil {
		return *m.Progress
	}
	return 0
}

type CSXiantiUnreal struct {
	XiantiId         *int32 `protobuf:"varint,1,req,name=xiantiId" json:"xiantiId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSXiantiUnreal) Reset()                    { *m = CSXiantiUnreal{} }
func (m *CSXiantiUnreal) String() string            { return proto.CompactTextString(m) }
func (*CSXiantiUnreal) ProtoMessage()               {}
func (*CSXiantiUnreal) Descriptor() ([]byte, []int) { return fileDescriptor135, []int{6} }

func (m *CSXiantiUnreal) GetXiantiId() int32 {
	if m != nil && m.XiantiId != nil {
		return *m.XiantiId
	}
	return 0
}

type SCXiantiUnreal struct {
	XiantiId         *int32 `protobuf:"varint,1,opt,name=xiantiId" json:"xiantiId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCXiantiUnreal) Reset()                    { *m = SCXiantiUnreal{} }
func (m *SCXiantiUnreal) String() string            { return proto.CompactTextString(m) }
func (*SCXiantiUnreal) ProtoMessage()               {}
func (*SCXiantiUnreal) Descriptor() ([]byte, []int) { return fileDescriptor135, []int{7} }

func (m *SCXiantiUnreal) GetXiantiId() int32 {
	if m != nil && m.XiantiId != nil {
		return *m.XiantiId
	}
	return 0
}

type CSXiantiUnload struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSXiantiUnload) Reset()                    { *m = CSXiantiUnload{} }
func (m *CSXiantiUnload) String() string            { return proto.CompactTextString(m) }
func (*CSXiantiUnload) ProtoMessage()               {}
func (*CSXiantiUnload) Descriptor() ([]byte, []int) { return fileDescriptor135, []int{8} }

type SCXiantiUnload struct {
	XiantiId         *int32 `protobuf:"varint,1,req,name=xiantiId" json:"xiantiId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCXiantiUnload) Reset()                    { *m = SCXiantiUnload{} }
func (m *SCXiantiUnload) String() string            { return proto.CompactTextString(m) }
func (*SCXiantiUnload) ProtoMessage()               {}
func (*SCXiantiUnload) Descriptor() ([]byte, []int) { return fileDescriptor135, []int{9} }

func (m *SCXiantiUnload) GetXiantiId() int32 {
	if m != nil && m.XiantiId != nil {
		return *m.XiantiId
	}
	return 0
}

type CSXiantiAdvanced struct {
	AutoFlag         *bool  `protobuf:"varint,1,req,name=autoFlag" json:"autoFlag,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSXiantiAdvanced) Reset()                    { *m = CSXiantiAdvanced{} }
func (m *CSXiantiAdvanced) String() string            { return proto.CompactTextString(m) }
func (*CSXiantiAdvanced) ProtoMessage()               {}
func (*CSXiantiAdvanced) Descriptor() ([]byte, []int) { return fileDescriptor135, []int{10} }

func (m *CSXiantiAdvanced) GetAutoFlag() bool {
	if m != nil && m.AutoFlag != nil {
		return *m.AutoFlag
	}
	return false
}

type SCXiantiAdvanced struct {
	AdvancedId       *int32 `protobuf:"varint,1,req,name=advancedId" json:"advancedId,omitempty"`
	XiantiId         *int32 `protobuf:"varint,2,req,name=xiantiId" json:"xiantiId,omitempty"`
	Bless            *int32 `protobuf:"varint,3,opt,name=bless" json:"bless,omitempty"`
	BlessTime        *int64 `protobuf:"varint,4,opt,name=blessTime" json:"blessTime,omitempty"`
	AdvancedType     *int32 `protobuf:"varint,5,req,name=advancedType" json:"advancedType,omitempty"`
	IsDouble         *bool  `protobuf:"varint,6,opt,name=isDouble,def=0" json:"isDouble,omitempty"`
	TotalBless       *int32 `protobuf:"varint,7,opt,name=totalBless" json:"totalBless,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCXiantiAdvanced) Reset()                    { *m = SCXiantiAdvanced{} }
func (m *SCXiantiAdvanced) String() string            { return proto.CompactTextString(m) }
func (*SCXiantiAdvanced) ProtoMessage()               {}
func (*SCXiantiAdvanced) Descriptor() ([]byte, []int) { return fileDescriptor135, []int{11} }

const Default_SCXiantiAdvanced_IsDouble bool = false

func (m *SCXiantiAdvanced) GetAdvancedId() int32 {
	if m != nil && m.AdvancedId != nil {
		return *m.AdvancedId
	}
	return 0
}

func (m *SCXiantiAdvanced) GetXiantiId() int32 {
	if m != nil && m.XiantiId != nil {
		return *m.XiantiId
	}
	return 0
}

func (m *SCXiantiAdvanced) GetBless() int32 {
	if m != nil && m.Bless != nil {
		return *m.Bless
	}
	return 0
}

func (m *SCXiantiAdvanced) GetBlessTime() int64 {
	if m != nil && m.BlessTime != nil {
		return *m.BlessTime
	}
	return 0
}

func (m *SCXiantiAdvanced) GetAdvancedType() int32 {
	if m != nil && m.AdvancedType != nil {
		return *m.AdvancedType
	}
	return 0
}

func (m *SCXiantiAdvanced) GetIsDouble() bool {
	if m != nil && m.IsDouble != nil {
		return *m.IsDouble
	}
	return Default_SCXiantiAdvanced_IsDouble
}

func (m *SCXiantiAdvanced) GetTotalBless() int32 {
	if m != nil && m.TotalBless != nil {
		return *m.TotalBless
	}
	return 0
}

type CSXiantiHidden struct {
	Hidden           *bool  `protobuf:"varint,1,req,name=hidden" json:"hidden,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSXiantiHidden) Reset()                    { *m = CSXiantiHidden{} }
func (m *CSXiantiHidden) String() string            { return proto.CompactTextString(m) }
func (*CSXiantiHidden) ProtoMessage()               {}
func (*CSXiantiHidden) Descriptor() ([]byte, []int) { return fileDescriptor135, []int{12} }

func (m *CSXiantiHidden) GetHidden() bool {
	if m != nil && m.Hidden != nil {
		return *m.Hidden
	}
	return false
}

type SCXiantiHidden struct {
	Hidden           *bool  `protobuf:"varint,1,req,name=hidden" json:"hidden,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCXiantiHidden) Reset()                    { *m = SCXiantiHidden{} }
func (m *SCXiantiHidden) String() string            { return proto.CompactTextString(m) }
func (*SCXiantiHidden) ProtoMessage()               {}
func (*SCXiantiHidden) Descriptor() ([]byte, []int) { return fileDescriptor135, []int{13} }

func (m *SCXiantiHidden) GetHidden() bool {
	if m != nil && m.Hidden != nil {
		return *m.Hidden
	}
	return false
}

type CSXiantiUpstar struct {
	XiantiId         *int32 `protobuf:"varint,1,req,name=xiantiId" json:"xiantiId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CSXiantiUpstar) Reset()                    { *m = CSXiantiUpstar{} }
func (m *CSXiantiUpstar) String() string            { return proto.CompactTextString(m) }
func (*CSXiantiUpstar) ProtoMessage()               {}
func (*CSXiantiUpstar) Descriptor() ([]byte, []int) { return fileDescriptor135, []int{14} }

func (m *CSXiantiUpstar) GetXiantiId() int32 {
	if m != nil && m.XiantiId != nil {
		return *m.XiantiId
	}
	return 0
}

type SCXiantiUpstar struct {
	XiantiId         *int32 `protobuf:"varint,1,req,name=xiantiId" json:"xiantiId,omitempty"`
	Level            *int32 `protobuf:"varint,2,req,name=level" json:"level,omitempty"`
	UpPro            *int32 `protobuf:"varint,3,req,name=upPro" json:"upPro,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCXiantiUpstar) Reset()                    { *m = SCXiantiUpstar{} }
func (m *SCXiantiUpstar) String() string            { return proto.CompactTextString(m) }
func (*SCXiantiUpstar) ProtoMessage()               {}
func (*SCXiantiUpstar) Descriptor() ([]byte, []int) { return fileDescriptor135, []int{15} }

func (m *SCXiantiUpstar) GetXiantiId() int32 {
	if m != nil && m.XiantiId != nil {
		return *m.XiantiId
	}
	return 0
}

func (m *SCXiantiUpstar) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *SCXiantiUpstar) GetUpPro() int32 {
	if m != nil && m.UpPro != nil {
		return *m.UpPro
	}
	return 0
}

func init() {
	proto.RegisterType((*XiantiInfo)(nil), "ui.XiantiInfo")
	proto.RegisterType((*XiantiSkinInfo)(nil), "ui.XiantiSkinInfo")
	proto.RegisterType((*CSXiantiGet)(nil), "ui.CSXiantiGet")
	proto.RegisterType((*SCXiantiGet)(nil), "ui.SCXiantiGet")
	proto.RegisterType((*CSXiantiUnrealDan)(nil), "ui.CSXiantiUnrealDan")
	proto.RegisterType((*SCXiantiUnrealDan)(nil), "ui.SCXiantiUnrealDan")
	proto.RegisterType((*CSXiantiUnreal)(nil), "ui.CSXiantiUnreal")
	proto.RegisterType((*SCXiantiUnreal)(nil), "ui.SCXiantiUnreal")
	proto.RegisterType((*CSXiantiUnload)(nil), "ui.CSXiantiUnload")
	proto.RegisterType((*SCXiantiUnload)(nil), "ui.SCXiantiUnload")
	proto.RegisterType((*CSXiantiAdvanced)(nil), "ui.CSXiantiAdvanced")
	proto.RegisterType((*SCXiantiAdvanced)(nil), "ui.SCXiantiAdvanced")
	proto.RegisterType((*CSXiantiHidden)(nil), "ui.CSXiantiHidden")
	proto.RegisterType((*SCXiantiHidden)(nil), "ui.SCXiantiHidden")
	proto.RegisterType((*CSXiantiUpstar)(nil), "ui.CSXiantiUpstar")
	proto.RegisterType((*SCXiantiUpstar)(nil), "ui.SCXiantiUpstar")
}

func init() { proto.RegisterFile("xianti.proto", fileDescriptor135) }

var fileDescriptor135 = []byte{
	// 436 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4d, 0x6f, 0xd4, 0x30,
	0x14, 0x54, 0x92, 0xa6, 0x4d, 0x5f, 0xba, 0x51, 0xd6, 0x20, 0xe1, 0xa3, 0x65, 0xf5, 0x10, 0x71,
	0xd8, 0x03, 0xe2, 0xc4, 0x01, 0x01, 0xad, 0x80, 0x95, 0x7a, 0xa8, 0xb4, 0x45, 0xe2, 0xea, 0x12,
	0xb7, 0x58, 0x75, 0xed, 0x28, 0x71, 0xaa, 0x72, 0xe3, 0x8f, 0xf0, 0x93, 0xf8, 0x4f, 0x28, 0xcf,
	0x4d, 0x36, 0xd9, 0x0f, 0x89, 0x43, 0x8f, 0x7e, 0x9a, 0x37, 0xf3, 0x66, 0x46, 0x86, 0x93, 0x47,
	0x25, 0x8c, 0x53, 0x8b, 0xaa, 0xb6, 0xce, 0x92, 0xb0, 0x55, 0xfc, 0x77, 0x00, 0xf0, 0x1d, 0x87,
	0x4b, 0x73, 0x63, 0x09, 0x01, 0x10, 0xe5, 0x83, 0x30, 0x3f, 0x64, 0xb9, 0x2c, 0x69, 0xc0, 0xc2,
	0x22, 0x26, 0x39, 0x24, 0x7e, 0x6d, 0x59, 0xd2, 0x10, 0x27, 0x2f, 0x20, 0x6d, 0x4d, 0x2d, 0x85,
	0xbe, 0x90, 0x0f, 0x52, 0xd3, 0x08, 0x87, 0x73, 0x38, 0xf6, 0xc3, 0xcb, 0xda, 0xd2, 0x03, 0x1c,
	0x9d, 0x42, 0xd2, 0xdc, 0x29, 0x73, 0xa1, 0x1a, 0x47, 0x63, 0x16, 0x15, 0xe9, 0x1b, 0xb2, 0x68,
	0xd5, 0xc2, 0xeb, 0xad, 0xee, 0x94, 0xe9, 0x34, 0xf9, 0x7b, 0xc8, 0xa6, 0x93, 0x89, 0xa2, 0xbf,
	0x61, 0x06, 0xb1, 0x46, 0x2d, 0x7f, 0x40, 0x0a, 0x51, 0x55, 0x5b, 0x2f, 0xcc, 0x67, 0x90, 0x9e,
	0xad, 0x3c, 0xc3, 0x17, 0xe9, 0xf8, 0xdf, 0x00, 0xd2, 0xd5, 0xd9, 0xf0, 0x7e, 0x66, 0x4b, 0x04,
	0xe0, 0x09, 0xd7, 0x9b, 0xc2, 0xe3, 0xae, 0xb5, 0x6c, 0x1a, 0x7a, 0xc8, 0x02, 0xbf, 0x85, 0xcf,
	0x2b, 0x75, 0x2f, 0xe9, 0x11, 0x0b, 0x8a, 0x88, 0x64, 0x70, 0xf8, 0x53, 0x95, 0xa5, 0x34, 0x34,
	0x61, 0x61, 0x91, 0x90, 0xd7, 0x90, 0x3d, 0x0e, 0x96, 0x91, 0xe9, 0x78, 0x6f, 0x3c, 0x0c, 0xe6,
	0xbd, 0xbd, 0x6f, 0xa8, 0x7c, 0x2e, 0x4c, 0x17, 0x80, 0x69, 0xef, 0xbd, 0x1b, 0xfe, 0x16, 0xe6,
	0xbd, 0xe1, 0x35, 0x62, 0x48, 0x6c, 0x70, 0x5c, 0xd5, 0xf6, 0xb6, 0xee, 0xce, 0x44, 0xc7, 0x9c,
	0x43, 0x36, 0xe5, 0xdd, 0x8e, 0xbd, 0xc3, 0x4c, 0x99, 0x37, 0x30, 0x41, 0x11, 0xf3, 0x7c, 0xcc,
	0xa3, 0xad, 0x28, 0xa7, 0x5b, 0xdd, 0x64, 0x07, 0xf3, 0x29, 0xe4, 0xfd, 0xd6, 0xc7, 0xa7, 0x76,
	0x3a, 0x94, 0x68, 0x9d, 0xfd, 0xac, 0xc5, 0x2d, 0xa2, 0x12, 0xfe, 0x27, 0x80, 0xbc, 0xa7, 0x1a,
	0x60, 0xff, 0x57, 0xe8, 0x50, 0x4a, 0xb4, 0x5d, 0xca, 0x01, 0x96, 0xf2, 0x12, 0x4e, 0x7a, 0x9e,
	0xab, 0x5f, 0x95, 0xa4, 0x31, 0xee, 0xbd, 0x82, 0x44, 0x35, 0xe7, 0xb6, 0xbd, 0xd6, 0x12, 0xfb,
	0x4c, 0xde, 0xc5, 0x37, 0x42, 0x37, 0xb2, 0x93, 0x75, 0xd6, 0x09, 0xfd, 0x09, 0x59, 0x8f, 0xd0,
	0x3b, 0x5b, 0x7b, 0xff, 0x8a, 0xfd, 0x8e, 0x9a, 0xf6, 0x0e, 0xd8, 0x3a, 0x8b, 0x3d, 0x88, 0x71,
	0x0f, 0x55, 0xe3, 0x44, 0xbd, 0x23, 0xad, 0x0f, 0xa3, 0x44, 0xf7, 0x60, 0x36, 0xbf, 0xc8, 0x0c,
	0xe2, 0xb6, 0xba, 0xec, 0x3f, 0xc9, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x2a, 0x3f, 0x3c,
	0xfa, 0x03, 0x00, 0x00,
}
